### PR TITLE
cloudflare access documentation

### PR DESCRIPTION
**Pull request by matejkramny**
complements PR #10588 

adds documentation section under Guides for cloudflare access, detailing how to set up cloudflare to work with Immich and how to set up headers in the app

### CODE REVIEW

**Review by danieldietzler — CHANGES_REQUESTED** [review]
As this is prone to be outdated, I'd prefer this to be a community guide. (like setting up cloudflare tunnel)

**Comment by mmomjian** [comment]
I think we already have this? [Cloudflare Tunnels with SSO/OAuth](https://immich.app/docs/community-guides/)

I'd recommend any changes as a PR to that project

**Comment by matejkramny** [comment]
Hi, I've added the content to https://github.com/matejkramny/immich-guides/tree/main
It might not get through, as there's no activity from the guide creator. https://github.com/ppr88/immich-guides/issues/1

I'll give the original creator some time to see the PR, if not, would you be ok replacing the community guide with my fork?

**Comment by danieldietzler** [comment]
> I'll give the original creator some time to see the PR, if not, would you be ok replacing the community guide with my fork?

**Comment by alextran1502** [comment]
Let's add the community guide with your fork. Thanks

**Pull request closed without merging**
