### PR TITLE
Update kubernetes.md

### PR DESCRIPTION
**Pull request by gregwalters**
Adds info about ndots container paramater

### CODE REVIEW

**Comment by gregwalters** [comment]
Closing because the immich-charts repo exists

**Comment by bo0tzz** [comment]
I'm not sure how I feel about the ndots solution. It does technically fix the geocoder, but it's likely to break other in-cluster dns lookups for eg. a database I  another namespace.

**Comment by gregwalters** [comment]
> I'm not sure how I feel about the ndots solution. It does technically fix the geocoder, but it's likely to break other in-cluster dns lookups for eg. a database I another namespace.

Sure, but none of the solutions outlined in the documentation are ideal. Might as well have another option available in the pile of less than stellar options.

**Comment by bo0tzz** [comment]
What's wrong with the searchdomain fix? That's the general-purpose solution that also removes the issue for any other alpine containers.

**Comment by gregwalters** [comment]
In my case, the search domain is set via DHCP and removing it from my nodes would remove it from everything on my network and that's a no-go. I enjoy not having to type fully-qualified hostnames in various configs and such. Even if I were to set my nodes to ignore the search domain, I'd still rather not.

Asking "what's wrong with removing the search domain" is ignoring every valid use case for having a search domain and the existence of that option in general.

**Comment by gregwalters** [comment]
Unfortunate that this was closed. It seems to ignore my reasoning, doesn't describe why my suggestion isn't acceptable, and leaves a bad taste in my mouth that'll influence my decision to make future contributions or not.

**Pull request closed without merging**
