### PR TITLE
Added font support for CJK

### PR DESCRIPTION
**Pull request by hismethod**
- Added CJK support fonts.
for Korean/Japanese, apply a font style similar to the existing font as much as possible.
- Modify main.dart, immich_app_theme.dart
modified some files to create ThemeData with CJK support fonts.

### CODE REVIEW

**Comment by alextran1502** [comment]
Hello, thank you for the PR. Does this mean that the current WorkSans font doesn't support Korean and Japanese font?

**Comment by hismethod** [comment]
> Hello, thank you for the PR. Does this mean that the current WorkSans font doesn't support Korean and Japanese font?

Hello. Thank you for reviewing PR.
As you said, worksans and most Latin fonts are not supported because CJK support is not default.
You can refer to the screenshot below.
스크린샷 2022-08-30 오후 12 44 03

I don't know much about Japanese and Chinese, but Korean is not supported by worksans, so the system font seems to work as a fallback.

Even if the system font works, it is mixed with some supported characters, such as numbers. The font style displayed in the end is not fancy.

**Comment by alextran1502** [comment]
Thank you for the feedback! When originally developing the app, I didn't consider the wide adoption to other languages, thus the font choice. 

Let me do some experimentation with changing the font for the app as a whole to support other languages and preserve the branding of the app

**Comment by hismethod** [comment]
> Thank you for the feedback! When originally developing the app, I didn't consider the wide adoption to other languages, thus the font choice.
> 
> Let me do some experimentation with changing the font for the app as a whole to support other languages and preserve the branding of the app

Thank you for your consideration.
I posted a PR, but my commit did not fit the overall code style, so I was not satisfied with myself.
If you think of it simply, it is similar to a situation where you need to use only the arial font in a fancy app.

Koreans are also accustomed to beautiful and concise fonts. Of course, the same goes for Japan and China.
If the font system is improved, I think it will be a much more complete product.

Not only that, but there are also many great developers.
If there is anything I can do, such as multilingual application or document localization, please request it at any time.

thank you

**Comment by alextran1502** [comment]
Close, will be implemented in a separated PR to change the app's font

**Pull request closed without merging**
