### PR TITLE
feat(web): allow tags to be applied in bulk on search, personID, and memory-viewer pages

### PR DESCRIPTION
**Pull request by Menghini**
I have been adding a lot of tags to my photos on my Immich server to help organize photos. However, when I try to add tags based upon a PersonID or when using the search function, I am forced right now to add it to a temporary album and then open the album to then apply the tag. This PR would solve that issue.

Close #14106

### CODE REVIEW

**Comment by Menghini** [comment]
This PR would solve #14106.

Although #14213 added some great features, it still was missing the tag option in the menu.

**Comment by danieldietzler** [comment]
Please fix the formatting errors

**Comment by Menghini** [comment]
> Please fix the formatting errors

Should be fixed now, I believe.

**Comment by Menghini** [comment]
Now also includes the Memory-Viewer page as well.

**Review by danieldietzler — APPROVED** [review]
LGTM

**Comment by Menghini** [comment]
> I have tags enabled and I am the owner of all the images in the library but I cannot see the tag search. Am I missing something? Does this feature not work with external libraries?

This PR allows you to add a tag to a bulk of images that was on the search, personID, and memory-viewer pages, but doesn't cover the /tag page. Right now, as far as I know, the /tag page doesn't have any controls or search.

**Comment by Hixxey** [comment]
> > I have tags enabled and I am the owner of all the images in the library but I cannot see the tag search. Am I missing something? Does this feature not work with external libraries?
> 
> This PR allows you to add a tag to a bulk of images that was on the search, personID, and memory-viewer pages, but doesn't cover the /tag page. Right now, as far as I know, the /tag page doesn't have any controls or search.

Got it, thank you. I misunderstood the PR

**Pull request merged**
