### PR TITLE
fix(server): not in album filter with context search

### LINKED ISSUE #7268: BUG(Server): Search with parameter "Not in any album" returns images that appear in an album
### The bug

Search with parameter "Not in any album" returns images that appear in an album

image

The image shown on the first screenshot appears in an album.
image

### The OS that Immich Server is running on

UnRaid

### Version of Immich Server

v1.95

### Version of Immich Mobile App

not needed

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
aio image
```

### Your .env content

```Shell
aio image
```

### Reproduction steps

```bash
1. Open the search
2. Type in some context
3. Check display option: Not in any album
4. Images that appear in an album are returned
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by alextran1502**
fix #7268

### CODE REVIEW

**Review by mertalev — APPROVED** [review]

**Review by mertalev — CHANGES_REQUESTED** [review]
Ah wait, I don't think this will work

**Comment by mertalev** [comment]
We can't join on albums with smart search since it isn't a one-to-one or many-to-one relation

**Comment by alextran1502** [comment]
I tested this and it works 😅

**Comment by mertalev** [comment]
After looking at this again, I think this will work since this is effectively an anti-join that excludes assets in albums. It shouldn't have the duplicate row issue in this case.

**Review by mertalev — APPROVED** [review]

**Pull request merged**
