### PR TITLE
feat(server): Support TypeSense High-Availibility configuration

### PR DESCRIPTION
**Pull request by samip5**
I'm not sure how this should be done without duplicating the last 4 lines, for apikey etc.

### CODE REVIEW

**Review by jrasm91 — COMMENTED** [review]
You can create an object at the top of the function that holds the common keys and then use that in both return objects via `...common`. Or, do like we do in the database config file and only return the node configuration and merge that into the rest of the (common) config. Ping me in discord if that doesn't make sense.

**Comment by michelheusschen** [comment]
I also wanted to ask this in your redis PR, but it was already merged: why is the config value base64 encoded?

**Comment by samip5** [comment]
> I also wanted to ask this in your redis PR, but it was already merged: why is the config value base64 encoded?

Simpler to parse mainly and in redis the whole object is given to ioredis.

**Comment by michelheusschen** [comment]
It only seems like an extra conversion step, or am I missing something? Why not use something like this:

```ts
// Set this in .env or however you want to
TYPESENSE_NODES=[{"host":"typesense-1"},{"host":"typesense-2"}]

// Parse config in infra.config.ts
const nodes = JSON.parse(process.env.TYPESENSE_NODES);
```

**Comment by samip5** [comment]
> It only seems like an extra conversion step, or am I missing something? Why not use something like this:
> 
> ```ts
> // Set this in .env or however you want to
> TYPESENSE_NODES=[{"host":"typesense-1"},{"host":"typesense-2"}]
> 
> // Parse config in infra.config.ts
> const nodes = JSON.parse(process.env.TYPESENSE_NODES);
> ```

I don't think ENV vars like RAW JSON... or at least haven't seen it.


Let's ask the other way, why not base64 encoded?

**Comment by michelheusschen** [comment]
It's perfectly fine to keep the TypeSense configuration as a single variable, that was just an example. I have seen JSON being used in env variables and from a quick test it works just fine. I'm not completely against using base64, but sticking with JSON only seems more user-friendly because you don't have the extra conversion step and it simplifies troubleshooting any configuration issues.

Regardless, it's important to document the new environment variable and if base64 encoding is chosen, a note should be provided for users who may not be familiar with it.

**Review by jrasm91 — APPROVED** [review]

**Pull request merged**
