### PR TITLE
feat(deployment): support docker secrets

### LINKED ISSUE #14: Support docker secrets
Hi!

Would you please implement extra Docker environment variables called `*_FILE` or something in that fashion, and feed them `/run/secrets/immich_*`, at least for the database password and the jwt secret?
Doing otherwise can be unsafe. Ideally, the database name and username can also be read as secrets.

The docker-compose.yml would look like (only included the relevant parts)
```yaml
services:
  server:
    environment:
      # STAGE
      NODE_ENV: development

      # Database
      DB_USERNAME_FILE: /run/secrets/immich_db_user
      DB_PASSWORD_FILE: /run/secrets/immich_db_password
      DB_DATABASE_NAME_FILE: /run/secrets/immich_db_db

      # Upload File Config
      UPLOAD_LOCATION: ./upload

      # JWT SECRET
      JWT_SECRET_FILE: /run/secrets/immich_jwt
    secrets:
      - immich_db_db
      - immich_db_user
      - immich_db_password
      - immich_jwt

  database:
    environment:
      TZ: ${TZ}
      POSTGRES_DB_FILE: /run/secrets/immich_db_db
      POSTGRES_USER: /run/secrets/immich_db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/immich_db_password
    secrets:
      - immich_db_db
      - immich_db_user
      - immich_db_password

secrets:
  immich_db_db:
    file: /secrets_path/immich_db_db
  immich_db_user:
    file: /secrets_path/immich_db_user
  immich_db_password:
    file: /secrets_path/immich_db_password
  immich_jwt:
    file: /secrets_path/immich_jwt
```

I don't know Dart and TypeScript, but some possible code to read them in bash and store the contents in variables is:
```bash
[[ -z "${JWT_SECRET_FILE}" ]] && [[ -f "${JWT_SECRET_FILE}" ]] && JWT_SECRET='$(head -n 1 "${JWT_SECRET_FILE}")'
```
Hopefully this helps

### PR DESCRIPTION
**Pull request by EnochPrime**
Adds support for docker secrets with `*_FILE` environmental variables to server and microservices for the following variables:
- `DB_HOSTNAME`
- `DB_DATABASE_NAME`
- `DB_USERNAME`
- `DB_PASSWORD`

Closes #14

### CODE REVIEW

**Comment by bo0tzz** [comment]
Isn't the idea behind secret files that they are read directly by the application, to avoid a chance of environment variables leakage? With this setup, why not just use normal env vars?

**Comment by EnochPrime** [comment]
> Isn't the idea behind secret files that they are read directly by the application, to avoid a chance of environment variables leakage? With this setup, why not just use normal env vars?

With the variables as-is the end user would need to define them in their docker-compose or .env files which then could not be published to a public repository. Using secret variables in this way will protect the end-users configuration. As far as the application using the secret vs the entry-point script: I can't answer that. I did some more digging and haven't yet found an example that doesn't do this in the entry-point. All of these put the file contents into the environmental variable.
- All linuxserver.io images
- MariabDB
- MySQL
- Wordpress
- Postgres

**Comment by bo0tzz** [comment]
> With the variables as-is the end user would need to define them in their docker-compose or .env files which then could not be published to a public repository.

You can use multiple env files with docker compose's [env_file](https://docs.docker.com/compose/compose-file/compose-file-v3/#env_file) option, for example:
```
env_file:
  - .env
  - secret.env
```
And then just don't commit the latter.

**Comment by EnochPrime** [comment]
This is a good point. In my situation I use docker swarm which does not support `env_file`, however, there is a work around for that. Would moving the use of file-based secrets into the application code be the preferred path forward? I'm not familiar with vulnerabilities of a file vs an env variable to know which is better, but from my perspective it seems it is common to use env vars for docker secrets.

**Comment by kaysond** [comment]
> > With the variables as-is the end user would need to define them in their docker-compose or .env files which then could not be published to a public repository.
> 
> You can use multiple env files with docker compose's [env_file](https://docs.docker.com/compose/compose-file/compose-file-v3/#env_file) option, for example:
> 
> ```
> env_file:
>   - .env
>   - secret.env
> ```
> 
> And then just don't commit the latter.

But then you can't do automated deployments from a repo. The other advantage of secrets (with swarm) is that you can specify the value on the command-line, via stdin, so it's very well secured.

In my case, I have all secrets in an ansible vault, which gets committed, and it gets decrypted on the fly by a service user when the playbook is run. The playbook adds the external secret to swarm via the ansible community docker module (which uses the python docker library), and the secret lives on in the swarm. With this methodology, the secret is always encrypted at rest and never exists in a flat file somewhere that could potentially get leaked.

**Comment by EnochPrime** [comment]
> Isn't the idea behind secret files that they are read directly by the application, to avoid a chance of environment variables leakage? With this setup, why not just use normal env vars?

I looked into this a bit and found the following:
1. Env vars defined by the environment block are visible when running `docker inspect` or from within the running container. This is mitigated with docker secrets as the env var will just be a file path.
2. Any env vars declared inside the entrypoint script are only visible to that running process and not the entire container. Which appears to be the same way the env file works.
3. The default permissions for secrets is 0444 and owned by root, but this is adjustable in compose.

**Comment by bo0tzz** [comment]
> Any env vars declared inside the entrypoint script are only visible to that running process and not the entire container.

As a small nitpick, technically you can get the env vars of another process:
```
ubuntu@box:~$ FOO=BAR sleep 10000 &
[1] 267275
ubuntu@box:~$ cat /proc/267275/environ
FOO=BARSHELL=/bin/bashPWD=/home/ubuntu(...etc)
```

The process directly reading the file would prevent that. That said, I don't know if this applies inside a container and if it's even worth worrying about at that point :P

**Comment by EnochPrime** [comment]
Definitely learn something new everyday. What is the desired path forward on this?

1. Use this approach with `bash`
2. Rewrite it to work with `sh`
3. Rewrite to read files directly by each program

**Comment by bo0tzz** [comment]
@alextran1502 what are your thoughts on this secret file topic?

**Comment by EnochPrime** [comment]
I did a rebase and rewrote the scripts to work with `sh` since I figured using `bash` would be the least likely of the three outcomes.

**Comment by EnochPrime** [comment]
@alextran1502 could you provide some direction when you have a moment? Thanks.

**Comment by EnochPrime** [comment]
> I am not very familiar with the secret file implementation on Docker. From reading the script, it seems like the script is expecting a different variable `DB_HOSTNAME_FILE` then it sets for the expected value `DB_HOSTNAME` in Immich. Instead of doing that, why don't you set the variable file as `DB_HOSTNAME` from the start?

That's the decision point. The script maps the `*_FILE` env var to the expected variable, which appears to be a common pattern used by other projects (i.e. posgres). We could however set the current env vars to file paths, but then each program will need to recognize that it received a file path and load the contents.

**Comment by kaysond** [comment]
> a common pattern used by other projects

And every single LSIO container!

It would be confusing (and potentially problematic/security risky) if you could set an env var both to its value and to a file path where the file contains its value.

**Pull request merged**
