### PR TITLE
fix(server): addAssets and removeAssets handle duplicate assetIds

### LINKED ISSUE #9368: addAssetsToAlbum endpoint does not handle repeated IDs
```bash
curl -X 'PUT' \
  'https://demo.immich.app/api/album/c757a1dc-afae-4cce-8f14-cf0adf5bea8e/assets' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "ids": [
    "7f7e71ab-a630-449d-b7c1-c52fc8b44733",
    "7f7e71ab-a630-449d-b7c1-c52fc8b44733"
  ]
}'
```

Results in
```json
{
  "message": "Failed to add assets to album",
  "error": "Internal Server Error",
  "statusCode": 500
}
```

Because of this server error:
```
demo-immich-server-1            |     at async AlbumService.addAssets (/usr/src/app/dist/services/album.service.js:154:25)] Failed to add assets to album
demo-immich-server-1            | [Nest] 7  - 05/10/2024, 11:52:47 AM   ERROR [QueryFailedError: duplicate key value violates unique constraint "PK_c67bc36fa845fb7b18e0e398180"
demo-immich-server-1            |     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
demo-immich-server-1            |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
demo-immich-server-1            |     at async InsertQueryBuilder.execute (/usr/src/app/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
demo-immich-server-1            |     at async AlbumRepository.addAssetIds (/usr/src/app/dist/repositories/album.repository.js:216:9)
demo-immich-server-1            |     at async addAssets (/usr/src/app/dist/utils/asset.util.js:29:9)
demo-immich-server-1            |     at async AlbumService.addAssets (/usr/src/app/dist/services/album.service.js:154:25)] QueryFailedError: duplicate key value violates unique constraint "PK_c67bc36fa845fb7b18e0e398180"
```

Repeated asset IDs should probably just get removed by using a Set.

### PR DESCRIPTION
**Pull request by eric-barch**
Fixes #9368, where calling `addAssets` with duplicate ids results in an internal server error.

This fix leverages the `existingAssetIds` Set already included in `addAssets`, but I could see the argument that we should keep that reserved for assets that were in the database _before_ calling `addAssets`. If you feel that way I can instead revise this to create a dedicated Set just for uniqueness within `addAssets`.

### Input:

```shell
curl -X 'PUT' \
  'https://demo.immich.app/api/album/c757a1dc-afae-4cce-8f14-cf0adf5bea8e/assets' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "ids": [
    "7f7e71ab-a630-449d-b7c1-c52fc8b44733",
    "7f7e71ab-a630-449d-b7c1-c52fc8b44733"
  ]
}'
```

### Output:

**Before:**
```json
{
  "message": "Failed to add assets to album",
  "error": "Internal Server Error",
  "statusCode": 500
}
```

**After:**
```json
[
  {
    "id": "7f7e71ab-a630-449d-b7c1-c52fc8b44733",
    "success": true
  }, {
    "id": "7f7e71ab-a630-449d-b7c1-c52fc8b44733",
    "success": false,
    "error": "duplicate"
  }
]
```

For consistency, I also made the corresponding change in `removeAssets`. In my opinion the output from this change is more accurate/helpful, but let me know if you disagree.

### Input:

```shell
curl -X 'DELETE' \
  'https://demo.immich.app/api/album/c757a1dc-afae-4cce-8f14-cf0adf5bea8e/assets' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "ids": [
    "7f7e71ab-a630-449d-b7c1-c52fc8b44733",
    "7f7e71ab-a630-449d-b7c1-c52fc8b44733"
  ]
}'
```

### Output:

**Before:**
```json
[
  {
    "id": "7f7e71ab-a630-449d-b7c1-c52fc8b44733",
    "success": true
  }, {
    "id": "7f7e71ab-a630-449d-b7c1-c52fc8b44733",
    "success": true
  }
]
```

**After:**
```json
[
  {
    "id": "7f7e71ab-a630-449d-b7c1-c52fc8b44733",
    "success": true
  }, {
    "id": "7f7e71ab-a630-449d-b7c1-c52fc8b44733",
    "success": false,
    "error": "not_found"
  }
]
```

### CODE REVIEW

**Review by danieldietzler — APPROVED** [review]
I'd say this is fine.

**Review by jrasm91 — APPROVED** [review]
If you are up for it, can you add an e2e test for this? `e2e/src/api/specs/album.e2e-spec.ts`

**Comment by eric-barch** [comment]
Sure, no problem. I added two e2e tests, one for each endpoint I changed. I tried to keep the format as close as possible to the existing tests but let me know if you have any suggestions for improvement.

**Comment by jrasm91** [comment]
Looks perfect! Tyvm

**Pull request merged**
