### PR TITLE
fix(mobile): missing timezones

### PR DESCRIPTION
**Pull request by MatyasK**
Fixing issue #10689  where certain timezones are missing from the app.
Since there is a lot of timezones, I added a searchable dropdown field in order to find the desired timezone easier.

image
image

### CODE REVIEW

**Comment by WhiteWoodenWall** [comment]
Not sure if I'm allowed to comment here, but this would be a much appreciated feature! Trying to find Tokyo every time I change the time of an asset is difficult for me

**Comment by C-Otto** [comment]
While we're at it, could you please have a look at 259bc8a6b051b0d4f0e844c48a32c68fb1da6b78? Ideally, you'd only show time zones that correspond to the selected date (i.e. considering daylight saving). I'd also appreciate having the same style as in the web view:

image

**Comment by MatyasK** [comment]
I can fix this later this week!

**Comment by alextran1502** [comment]
Hello, any update on this PR?

**Comment by zackpollard** [comment]
Hey, I am going to close this PR due to inactivity, but if you get around to making the required changes, please feel free to open a new PR or request for this one to be re-opened with a comment here 🙂

**Pull request closed without merging**
