### PR TITLE
feat(web): Add file path info for owned assets

### PR DESCRIPTION
**Pull request by dpantel**
Add file path information to the asset details panel for External assets. This will allow a user to easily locate said asset in the filesystem, to perform any desired tasks on that asset. Styling was chosen to be as unobtrusive as possible.

### CODE REVIEW

**Comment by alextran1502** [comment]
I think for aesthetic feeling, you can put this as the title of the filename element so that it is only displayed on hover.

**Comment by dpantel** [comment]
Two concerns with your suggestion:
1. It would be too hidden, meaning that most users would not realize that hovering over the filename reveals the path. You could potentially mitigate that by giving a context clue that more info exists, like making the filename appear as a link, or something similar.
2. You can't select and copy text from an on-hover title popup. This path has a potential to be long, and it would be nice to just copy it in Immich and paste it in a file browser.

Honestly, It doesn't seem too obtrusive to me.

Screenshot from 2023-11-09 22-00-55

**Comment by jrasm91** [comment]
Maybe we can add it as a normal item with an icon and then have a user setting to toggle if it is displayed or not.

**Comment by dpantel** [comment]
How about something like this?

[immich_toggle.webm](https://github.com/immich-app/immich/assets/15957402/e8ce8ebf-0e03-470d-981a-014eb126d12c)

**Comment by alextran1502** [comment]
> How about something like this?
> 
>  immich_toggle.webm

Looks good, let's do that

**Comment by dpantel** [comment]
Ok, I think this looks reasonable to me. Ignore the merge from main, I was trying to get the development web server to work (it's broken now).

**Review by alextran1502 — APPROVED** [review]
Looks good, thank you!

**Review by alextran1502 — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
