### PR TITLE
feat(mobile): autofill login form

### LINKED ISSUE #1116: [Feature]: Allow Bitwarden to autofill login screen (Android)
### Feature detail

Bitwarden is currently not able to autofill the login details when opening the Android app.  It appears that the login fields will need to be marked as autofill-able.  

### Platform

Mobile App

### PR DESCRIPTION
**Pull request by EnricoBilla**
I implemented autofill for the login form on the mobile app.

I tested it with Bitwarden, email and password are autofilling correctly. I also added support for the endpoint URL but it's not actually supported natively by Bitwarden as of now.

https://user-images.githubusercontent.com/25234601/208536915-853300ca-13f7-49bc-9a1f-4d399139a87b.mp4

Closes #1116

### CODE REVIEW

**Review by jrasm91 — APPROVED** [review]
The diff looks big, but I think most of it is related to the intention, right? It looks like you basically wrapped it in an auto fill group?

**Comment by EnricoBilla** [comment]
@jrasm91 Yes, GitHub show it really messy but actually I just wrapped Wrap in AutofillGroup

**Comment by eygraber** [comment]
This doesn't work with 1pass on Android 14. Should I file a new issue?

**Comment by EnricoBilla** [comment]
@eygraber yes please, make sure to include as much detail as possible

**Comment by eygraber** [comment]
https://github.com/immich-app/immich/issues/5177

**Pull request merged**
