### PR TITLE
pin image digests

### LINKED ISSUE #2751: [BUG] Container images should use pinned digests
### The bug

All container images should use a specific tag and pinned digest for predictability.

An effort to begin this has been started in https://github.com/immich-app/immich/pull/2736/files#diff-7dcfbc368ef61cdb87ff87938d3901a82097fe398633f995dc4ab1cbee761a40R1.

### The OS that Immich Server is running on

N/A

### Version of Immich Server

N/A

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

### Additional information

_No response_

### LINKED ISSUE #2752: [BUG] machine-learning and nginx should use alpine
### The bug

Given everything else in Immich uses alpine, the machine-learning and nginx images should remain consistent. 

### The OS that Immich Server is running on

N/A

### Version of Immich Server

N/A

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by uhthomas**
Manifest list digests can be found with:

```sh
docker buildx imagetools inspect python:3.11.4-bullseye
docker buildx imagetools inspect python:3.11.4-slim-bullseye
docker buildx imagetools inspect ghcr.io/nginxinc/nginx-unprivileged:1.25.0-alpine3.17
```

The node images are pinned in #2736

Fixes #2751
Partially fixes #2752

### CODE REVIEW

**Comment by alextran1502** [comment]
What is the benefit of this change?

**Comment by uhthomas** [comment]
> What is the benefit of this change?

Reproducibility and supply chain security. The current tag `python:3.11` could refer to `python:3.11.0`, `python:3.11.123` or anything in between which is not ideal. It also protects against bad changes to an existing tag, for example someone could push a new image to the tag `3.11` and Immich would pull that bad image in with the new update. Clear tags and digests show exactly what we intend to build and allow for selective updates. It's the same reason a `package-lock.json` exists along with a `package.json`.

Renovate will take care of automatic tag/digest updates in future, so it shouldn't be too burdensome to maintain.

**Comment by alextran1502** [comment]
Have you had a chance to test a production build with the pump version of NGINX image?

**Comment by uhthomas** [comment]
> Have you had a chance to test a production build with the pump version of NGINX image?

I haven't.

**Comment by alextran1502** [comment]
For these PRs of Dockerfile's content changes, I would like to have the production build test for the functional level of the application.

Can you help me do so?

**Review by alextran1502 — APPROVED** [review]

**Pull request merged**
