### PR TITLE
chore(web): auto sort imports

### PR DESCRIPTION
**Pull request by jrasm91**
Doesn't look like this plugin supports `.svelte` files yet, but it'll require and auto-fix `.ts` ones.

### CODE REVIEW

**Review by danieldietzler — APPROVED** [review]

**Review by benmccann — APPROVED** [review]

**Comment by benmccann** [comment]
Looks like there's a feature request for Svelte support: https://github.com/simonhaenisch/prettier-plugin-organize-imports/issues/39

**Comment by benmccann** [comment]
I'll note that this may make formatting quite a bit slower judging from their issue tracker: https://github.com/simonhaenisch/prettier-plugin-organize-imports/issues/114

**Comment by benmccann** [comment]
I checked with the Svelte maintainers about Svelte support for the prettier plugin and one suggested that it'd be better to focus on getting something https://github.com/lydell/eslint-plugin-simple-import-sort working since it has more advanced sorting capabilities. E.g. it will put `node:`-prefixed imports into a separate group as opposed to intermixing with the other imports

**Comment by jrasm91** [comment]
I looked at that briefly, but auto fixing eslinting errors seems quite a bit different than "format on save" functionality.

**Pull request merged**
