### PR TITLE
feat/fix(mobile): add translations (en-fr) and fix some UI glitch

### PR DESCRIPTION
**Pull request by clementdelestre**
Hello,

Here is the content of this PR:

- I added several missing translations (throughout the application), in English and French.
- I fixed some widget overflows (often due to long text overflow)
- I fixed text breaks in the ControlBottomAppBar options for some languages
- I rounded the edges of certain dialogs so that they fit better into UI (delete_dialog and confirm_dialog).

Thanks

### CODE REVIEW

**Comment by alextran1502** [comment]
Can you help include the screenshot of before and after for the UI modification?

**Comment by clementdelestre** [comment]
Yep!

Screenshots of the control bottom appbar before the MR:
Screenshot_2024-04-23-18-01-17-62_d8aea95ef633eb6b7eb1cae13c34b40e

Screenshots of the control bottom appbar after:
Screenshot_2024-04-23-17-59-31-33_a4ee5a0983f94a7f943cf21da7475e31
Screenshot_2024-04-23-18-00-33-70_a4ee5a0983f94a7f943cf21da7475e31

Screenshots of the dialog before:
Screenshot_2024-04-23-18-02-40-21_d8aea95ef633eb6b7eb1cae13c34b40e

Screenshots of the dialog after:
Screenshot_2024-04-23-18-08-17-57_a4ee5a0983f94a7f943cf21da7475e31

**Comment by benmccann** [comment]
Can you fix the failing formatting job?

**Comment by alextran1502** [comment]
Please send me an email so I can invite you to the translation platform we use for mobile

**Pull request closed without merging**
