### PR TITLE
chore(deps): update pydantic to v2

### PR DESCRIPTION
**Pull request by dotlambda**
see https://docs.pydantic.dev/latest/migration/

### CODE REVIEW

**Review by mertalev — APPROVED** [review]
Thanks for the PR! I didn't know there was a v1 module for easier migration.

**Comment by alextran1502** [comment]
@dotlambda This is causing an issue with the ML service not being able to start up. I am reverting this to prep for the release and we will look into removing Pydantic soon

**Comment by jvanbruegge** [comment]
That's surprising, because I run immich with basically this patch without issue

**Comment by mertalev** [comment]
The `/` and `/ping` endpoints throw errors because they use Pydantic. The latter in particular is used for health checks. The `/predict` endpoint doesn't use Pydantic so isn't affected.

**Comment by dotlambda** [comment]
> This is causing an issue with the ML service not being able to start up.

Can you add a unittest catching this?

**Comment by mertalev** [comment]
> > This is causing an issue with the ML service not being able to start up.
> 
> 
> 
> Can you add a unit test catching this?

Adding tests for this is a good idea. There's a general lack of e2e tests for machine learning pending a base image with (dummy) models, but the `/` and `/ping` endpoints don't need to wait on that.

**Pull request merged**
