### PR TITLE
feat(server): Add OAuth auto-redirect enable/disable CLI commands

### PR DESCRIPTION
**Pull request by ddshd**
Cannot use password login if OAuth auto-redirect is enabled and there is an issue with OAuth

### CODE REVIEW

**Comment by ddshd** [comment]
Lmk if a main oauth enable/disable would be bettter

**Review by jrasm91 — COMMENTED** [review]
I'm ok with adding this, although you can usually hit the back button and it will take you back to the login page. Also it should be OAuth everywhere instead of Oauth

**Comment by jrasm91** [comment]
And I think just disabling it entirely might be better.

**Comment by ddshd** [comment]
> And I think just disabling it entirely might be better.

Done

> I'm ok with adding this, although you can usually hit the back button and it will take you back to the login page. Also it should be OAuth everywhere instead of Oauth

Weird doesn't work for me, it just redirects back - maybe it's my oauth

**Comment by jrasm91** [comment]
There is a url param autoLaunch that you can set to 0 I think to disable the auto launching.

**Review by jrasm91 — APPROVED** [review]
I think everything looks good, but could you rename the file to just oauth login?

**Pull request merged**
