### PR TITLE
fix(mobile): album date range while adding or removing assets

### LINKED ISSUE #7643: [BUG] (add to/remove from) album - sorting
### The bug

When a new asset is uploaded and added/removed to/from an already existing album, that albums is not sorted according sorting settings on mobile. Web interface accepts that settings (Most recent photo).
Workaround is to reload all assets from server by double swipe down on Photos page. Then albums are sorted properly.

### The OS that Immich Server is running on

Fedora 39

### Version of Immich Server

v.1.97.0

### Version of Immich Mobile App

v.1.97.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
1. sort albums by "Most recent photo", album with the newest photo at top.
2. take a photo
3. add it to some older albums (not at the first place)
4. album stays at the original position - at top expected
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by waclaw66**
Fixes https://github.com/immich-app/immich/issues/7643

### CODE REVIEW

**Comment by shenlong-tanwen** [comment]
@waclaw66 Thank you for working on this. Can't we call the `refreshRemoteAlbums` method in `AlbumService` to handle this? This pulls in changes made to other albums as well, but that shouldn't be an issue.

**Comment by waclaw66** [comment]
@shenlong-tanwen sure, I can try, however I'm out until next Monday, feel free to handle it if you want, thanks

**Comment by waclaw66** [comment]
@shenlong-tanwen: I've looked into it and refreshing all albums doesn't seem like good idea, reloading hundreds of albums in my case takes quite long. I would prefer to refresh current album only. Maybee there is a better way how to do that, feel free to make a suggestion.

**Comment by waclaw66** [comment]
@shenlong-tanwen I've reworked sync mechanism of a single album. There was also fixed missing update of `startDate` and `endDate` within `_syncRemoteAlbum`.

**Comment by waclaw66** [comment]
@shenlong-tanwen: I've reworked single album sync and fixed missing `startDate` and `endDate` within `_syncRemoteAlbum`.

**Comment by waclaw66** [comment]
Can anyone help me with reopening this PR, I accidentally closed it with forced branch reset.

**Comment by alextran1502** [comment]
@waclaw66 you removed the branch so I cannot reopen it T_T

**Pull request closed without merging**
