### PR TITLE
feat: align compose ports

### PR DESCRIPTION
**Pull request by jrasm91**
Change the internal port from 3001 to 2283, to align with the external port.

### CODE REVIEW

**Comment by Miladiir** [comment]
👎

**Review by danieldietzler — APPROVED** [review]

**Comment by HybridSarcasm** [comment]
Why was this important to change? I don’t see any supporting issue stating why this was necessary. As it is, this seems like a “we wanted to” change. If so, seems like a poor reason for such a breaking change.

**Comment by bo0tzz** [comment]
Immich is still unstable beta software, and we're taking the liberty to change things to be better and cleaner even if it's not strictly necessary.

**Comment by jrasm91** [comment]
> to align with the external port.

Which has implications with troubleshooting, support, install instructions, demos, etc.

**Pull request merged**
