### PR TITLE
Update dependency

### PR DESCRIPTION
**Pull request by xpwmaosldk**
Update gradle and fix gradle warning,
Update dependency in pubspec.yaml

### CODE REVIEW

**Comment by xpwmaosldk** [comment]
It will be fix some bugs and optimize performance

**Comment by alextran1502** [comment]
Hello, is there a reason that the `pubspec.yml` is not included since you would update the library in `pubspec.yml` instead of the generated `pubspec.lock`?

**Comment by alextran1502** [comment]
We will also need to update `distributionSha256Sum=cd5c2958a107ee7f0722004a12d0f8559b4564c34daad7df06cffd4d12a426d0` in `mobile/android/gradle/wrapper/gradle-wrapper.properties` as well for the build to check and run

**Comment by xpwmaosldk** [comment]
thank for your guid, 
It changed version in yaml and distributionSha256Sum

**Comment by alextran1502** [comment]
There are several conflicts in updating these dependencies because some have major versions changed. I will leave this PR open until I have a chance to fix all of those.

**Comment by xpwmaosldk** [comment]
Hi again @alextran1502
I looked at the change log of the changed packages, and most minor version updates were bug fixes.
And the major version update had breaking changes, but it didn't affect the project.

Is there anything I missed?

**Comment by alextran1502** [comment]
Hey, @xpwmaosldk I pull your PR and try to run the app. The progress bar in the backup screen doesn't show up for some reason, I checked the API, and it looks the same though, so we need to investigate this. When I created the album and chose the photos/videos to add to the albums, each asset is duplicated. Those are the two prominent errors that I saw, so I am planning to investigate those.

Thank you for the PR though, I've noticed that some of the packages are out of date, and as you said, it gets rid of the error/warning when running on Android.

**Comment by xpwmaosldk** [comment]
Unfortunately(?), today flutter 3.0 was released. Are you planning to update 3.0? 
Then, I will close this PR and change the package version when the packages support 3.0, and open the PR again.

Additionally, I found some performance optimization points in the code (such as helper methods).
ref: [https://www.youtube.com/watch?v=IOyq-eTRhvo&t=5s](https://www.youtube.com/watch?v=IOyq-eTRhvo&t=5s)

Lastly, thank you for making a great app.

**Comment by alextran1502** [comment]
@xpwmaosldk Yes, I am planning to update to Flutter 3.0 as earliest as possible. 

Thank you for the pointer, I will take a look :)

**Pull request closed without merging**
