### PR TITLE
feat(docs): Template script for 3-2-1 backup of the assets and database

### PR DESCRIPTION
**Pull request by thariq-shanavas**
I added the script I use for 3-2-1 backup of Immich. Hopefully, it saves someone from losing their database or data entirely.
Let me know if any changes are needed, I'll be happy to make them!

### CODE REVIEW

**Review by danieldietzler — COMMENTED** [review]
Generally this looks really good but I'm wondering if the borg thing should be under guides... I feel like it makes more sense there because it's somewhat similar to "remote access" under guides.

**Comment by thariq-shanavas** [comment]
It's funny you should mention it, since I wrote the page on remote access.

I wondered the same thing - maybe there should just be a link to this template in the backup and restore page and the script itself should live in the guides section. I can change it if there is a second opinion.

**Comment by danieldietzler** [comment]
Haha that's funny :D
Waiting for others to chime in sounds like a good idea to me!

**Comment by alextran1502** [comment]
I agree with Daniel that we can move this over the Guide section

**Comment by thariq-shanavas** [comment]
I've moved the script to Guides. I've also taken the liberty of a slight edit to the "Getting Started" page to stress the importance of backups.

cc @alextran1502  @danieldietzler

**Review by danieldietzler — APPROVED** [review]
LGTM! Thank you :)

**Review by bo0tzz — COMMENTED** [review]
This is good, but it should probably also include some guidance on how to restore.

**Review by bo0tzz — APPROVED** [review]

**Comment by dariuszszyc** [comment]
Can you add please some lines about database restore ?
What is the command to restore a DB from backup ?
Do i have to remove old DB first or will it overwrite etc ?

I think this would make the guide a little more complete.

**Comment by thariq-shanavas** [comment]
@dariuszszyc you can find instructions on how to restore the database in the documentation here: https://immich.app/docs/administration/backup-and-restore

I don't think it's necessary to repeat it here.

**Pull request merged**
