### PR TITLE
fix(web): click outside search filter

### PR DESCRIPTION
**Pull request by martabal**
Currently, if you click outside the search filter, it does not close the modal.

### CODE REVIEW

**Comment by alextran1502** [comment]
This is intentional because very so often I manage to fill in all the info then click outside and it removes all of the content of the form

**Comment by shenlong-tanwen** [comment]
> This is intentional because very so often I manage to fill in all the info then click outside and it removes all of the content of the form

Maybe we need to add a search button and a clear button and persist the data until one of the two or enter is pressed. This way, we can close the form and re-open it with the data intact?

**Comment by martabal** [comment]
I agree with @shenlong-tanwen, It feels weird that you can close the search history box with an outside click but not the search filter box.

**Comment by alextran1502** [comment]
I am planning to handle the data binding differently, to use a global store so that it can be passed into the filter in the search result page. Let's close this PR because this feature is still under construction

**Pull request closed without merging**
