### PR TITLE
chore(mobile): Bump to Flutter 3.19.0

### PR DESCRIPTION
**Pull request by martyfuhry**
- [x] Tested on Android (@martyfuhry)
- [x] Tested on iOS

Works fine on my Android device.

Ran `fvm flutter pub upgrade --major-versions` which failed:

```bash
$ fvm flutter pub upgrade --major-versions
Encountered an alias node along [dependencies, isar]! Alias nodes are nodes that refer to a previously serialized nodes, and are 
denoted by either the "*" or the "&" indicators in the original YAML. As the resulting behavior of mutations on these nodes is no
t well-defined, the operation will not be supported by this library.

  ╷
6 │ isar_version: &isar_version 3.1.0+1
  │               ^^^^^^^^^^^^^^^^^^^^^
  ╵

```

So I removed the alias and manually wrote it in.

Running it again gave me:

```bash
Changed 5 constraints in pubspec.yaml:
  geolocator: ^10.1.0 -> ^11.0.0
  flutter_udid: ^2.1.1 -> ^3.0.0
  http: 0.13.5 -> ^0.13.6
  cancellation_token_http: ^1.1.0 -> ^2.0.0
  custom_lint: ^0.5.8 -> ^0.6.0
```

Breaking changes for each:
1. `geolocator`: BREAKING CHANGE: Updates dependency on geolocator_web to version [3.0.0](https://pub.dev/packages/geolocator_web/changelog). (seems unrelated)
2. `flutter_udid`: Add Windows and Linux support
3. `http`: Nothing relevant
4. `cancellation_token_http`: Based on version 1.1.0 of the [HTTP package](https://pub.dev/packages/http/versions/1.1.0).  Requires Dart 3.0 or later. Merge v1.1.0 changes to the HTTP package (***NB: Since we are on http 0.13.6, we may want to stick with an older version***)
5. `custom_lint`: Nothing relevant

### CODE REVIEW

**Comment by martyfuhry** [comment]
Should we update our dependencies here or in another PR?

**Comment by alextran1502** [comment]
We should update the dependencies here as well

**Comment by shenlong-tanwen** [comment]
> Should we update our dependencies here or in another PR?

If the dep update does not require much update in the codebase, then we can do them in this PR itself. Or else, leave the dep and handle it in a separate PR and update the remaining ones in this PR

**Comment by martyfuhry** [comment]
I had to clean and rebuild, but it's working fine on my Android emulator. Impeller is in preview for Android now, so it's fun to try that out on a physical device. It wasn't working right for videos, so we should let the Chewie guys know that (or someone more relevant).

**Review by alextran1502 — APPROVED** [review]

**Pull request merged**
