### PR TITLE
Add message to login screen (useful for demo instances)

### PR DESCRIPTION
**Pull request by matthinc**
I think this might be useful for the demo instance.

`.env`:
`VITE_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i>demo@demo.de</i><br>Password: <i>demo</i>"`

image

### CODE REVIEW

**Comment by zackpollard** [comment]
Can we just call this something like MOTD? I don't think this is specific to demo instances, it would be good for all server admins to announce planned maintenance etc.

**Comment by matthinc** [comment]
@zackpollard The MOTD will probably be placed at the very top of the site and is visible from all pages (that would IMO be annoying for the demo instance). This message is also deliberately located near the login form.

**Comment by zackpollard** [comment]
Alright that makes sense, then maybe we call it something specific about it's placement, I just don't like the idea of having cars specifically for demo instances, feels strange. Could call it VITE_LOGIN_PAGE_MESSAGE

**Comment by matthinc** [comment]
I agree with that point

**Comment by alextran1502** [comment]
I've added the information to the `.env.example` about the new key. 

I've also changed the style a little bit to fit with the color scheme of Immich

image

**Pull request merged**
