### PR TITLE
Update example.env to specify REDIS_PASSWORD_FILE

### PR DESCRIPTION
**Pull request by abhi-chakrab**
update to the example .env file to indicate docker secret support for REDIS_PASSWORD

### CODE REVIEW

**Comment by jrasm91** [comment]
Can you add this to the environment documentation page in the docs/ instead? We're moving away from documenting in this example file.

**Comment by abhi-chakrab** [comment]
Sure I can. But I couldn't figure out how to edit the documentation.

**Comment by jrasm91** [comment]
In the repo, you can enter the docs/ folder, then run `npm i` and `npm start`. It'll serve the docs locally so you can edit any of the markdown pages and see what they look like.

Sounds like we need a docs page for how to contribute to the docs 😛

Have you used nodejs before?

**Comment by jrasm91** [comment]
Actually it looks like this is doing the same thing.

https://github.com/immich-app/immich/pull/3402

**Comment by abhi-chakrab** [comment]
> Actually it looks like this is doing the same thing.
> 
> #3402

Yesh looks like that. Should I close this PR?

**Comment by jrasm91** [comment]
That's fine. Unless you have something additional to add.

**Comment by abhi-chakrab** [comment]
Closing pr.

**Pull request closed without merging**
