### PR TITLE
fix(server): add original path and library id index to asset

### PR DESCRIPTION
**Pull request by etnoy**
This adds an index to the original asset path. Since we often do lookups on original path this should speed things up for large libraries

### CODE REVIEW

**Review by jrasm91 — COMMENTED** [review]
Do you still have your big instance? I assumed the index should be on library id and source path, since that is what the query uses. Were you able to validate the query before/after the index?

**Comment by etnoy** [comment]
> Do you still have your big instance? I assumed the index should be on library id and source path, since that is what the query uses. Were you able to validate the query before/after the index?

250k assets, all timings made by psql

Create originalPath index: 1957ms

Select asset where originalPath='xxx'
Without index: ~133ms
With index: ~1-2ms

Create originalpath, libraryId index: 2066 ms

Select asset where originalPath='xxx' and libraryId='yyy'
Without index: ~120-140ms
With index: ~1.1-2.0 ms

So this made an incredible difference, at least when doing the raw sql call.

Profiling the library refresh is a bit harder, though.

**Review by jrasm91 — APPROVED** [review]
Can you revert the open API spec change (I need to fix that elsewhere), otherwise looks great!

**Comment by etnoy** [comment]
> Can you revert the open API spec change (I need to fix that elsewhere), otherwise looks great!

done! Hope for a fix for that soon :)

**Review by jrasm91 — APPROVED** [review]

**Pull request merged**
