### PR TITLE
fix(web): grid on people page

### PR DESCRIPTION
**Pull request by martabal**
## Changes made in this PR

With this PR, the people grid always takes up the full available width and the size of the thumbnails changes depending on the screen size.

## Screenshots

| Before | After |
| :---:  | :---: |
|<video src="https://github.com/immich-app/immich/assets/74269598/7ba9e77d-60b6-4308-b7d3-708f5b6b27b6"> | <video src="https://github.com/immich-app/immich/assets/74269598/305d76a2-a390-4994-84d6-5041f3054392">  |

### CODE REVIEW

**Review by jrasm91 — APPROVED** [review]
This seems OK, but you can actually accomplish all of this with css using flex, not with javascript that has to run in the browser and may cause performance issues on slower devices, like phones.

**Comment by martabal** [comment]
> This seems OK, but you can actually accomplish all of this with css using flex, not with javascript that has to run in the browser and may cause performance issues on slower devices, like phones.

The thumbnail width is re-calculated only when the width of the div containing all the thumbnails change. So could be an issue only on screen rotation

**Comment by martabal** [comment]
Changed to use grid instead

**Comment by jrasm91** [comment]
It's the video updated too or is that the old one?

**Review by jrasm91 — APPROVED** [review]
Lgtm

**Comment by martabal** [comment]
> It's the video updated too or is that the old one?

I just changed it

**Pull request merged**
