### PR TITLE
fix(server): server stats showing wrong quota usage

### LINKED ISSUE #8426: Space used metrics are inconsistent
### The bug

When using external libraries, the space used metric is inconsistent. The user sees this:
image

However, the Admin sees this on the Server Stats tab:

image

The "4 GB" number matches the size of the External Library as shown in the External Libraries tab.

Solution: Immich should not count the size of an External Library as part of the user Usage. 

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.100.0

### PR DESCRIPTION
**Pull request by mycroftsnm**
First time contributing here :) 
Fixes #8426

### CODE REVIEW

**Review by mertalev — APPROVED** [review]
Thanks for fixing this!

**Comment by mertalev** [comment]
You should run `npm run sql:generate` with Postgres running to fix the failing check.

**Comment by mycroftsnm** [comment]
> You should run `npm run sql:generate` with Postgres running to fix the failing check.

Sorry, where should i run that? inside the Postgres container? because im getting:

```
npm error Missing script: "sql:generate"
npm error
npm error To see a list of scripts, run:
npm error   npm run
```

**Comment by michelheusschen** [comment]
The script name is incorrect, try running `npm run sync:sql` in the server directory or `make sql` in the root directory

**Comment by mertalev** [comment]
Oh whoops, I didn't realize the script name changed.

**Comment by mycroftsnm** [comment]
I got some errors, but seems like now the user.repository.sql file its being correctly generated! 


```
make sql
npm --prefix server run sync:sql

> immich@1.105.1 sync:sql
> node ./dist/bin/sync-sql.js

(node:35729) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[Nest] 35729  - 08/06/2024, 04:34:52     LOG [EventRepository] Initialized websocket server
AlbumRepository.addAssetIds error: QueryFailedError: insert or update on table "albums_assets_assets" violates foreign key constraint "FK_e590fa396c6898fcd4a50e40927"
LibraryRepository.get error: EntityNotFoundError: Could not find any entity of type "LibraryEntity" matching: {
    "where": {
        "id": "00000000-0000-4000-a000-000000000000"
    },
    "relations": {
        "owner": true
    },
    "withDeleted": false
}
MemoryRepository.addAssetIds error: QueryFailedError: insert or update on table "memories_assets_assets" violates foreign key constraint "FK_984e5c9ab1f04d34538cd32334e"
PersonRepository.getFaceById error: EntityNotFoundError: Could not find any entity of type "AssetFaceEntity" matching: {
    "where": {
        "id": "00000000-0000-4000-a000-000000000000"
    },
    "relations": {
        "person": true
    }
}
Wrote 31 files
Generated 139 queries
Done

```

**Pull request merged**
