### PR TITLE
feat(server): nested album

### PR DESCRIPTION
**Pull request by alextran1502**
- create migration
- remove previous relationship
- migration
- response dto
- album tree

### CODE REVIEW

**Comment by waclaw66** [comment]
If I understand the code correcly this PR introduces possibility to have an album with assets inside another album with assets. With all respect to your work, do you have any reasonable usecase to have it like this? That doesn't make sense to me. I comprehend an album as the final leaf of a folder tree, with no childs.

One of proposal depictions, as I understand this PR, is that correct?

image

Please don't take this comment offensively, I just want to understand your intent.

**Comment by alextran1502** [comment]
@waclaw66 No offense taken. My reason for this approach is to reduce the complexity of introducing new concepts, e.g., folders. You can already have an album, and now you can use it as a folder if you wish, similar to how a folder/directory is used in your traditional file system, which can contain files and other folders.

For example, in a use case, if you have the habit of grouping your album into events, you can have a top-level album for Easter. Then, you can add nested Easter albums from different years and choose the highlight photos/videos of varying years to put in the top-level album.

Does it help answer the question?

**Comment by waclaw66** [comment]
@alextran1502 
> Does it help answer the question?

Yes, thank you. However still thinking that this design is way more complex that simple tree folder strufcture.
Album has more properties than folder. How will be handled start-end date, last modified asset, etc.? If there is no asset in parent album, what will be the cover? Gray as now? I assume it will behave like an empty album, right?

Looking forward to the outcome.

**Comment by Tronix117** [comment]
I'm discovering Immich and was surprised to find that a seemingly crucial feature for organizing large libraries wasn't there. However, I'm happy to learn that it's on the road.

While I grasp the intent behind avoiding a new entity similar to `folders`, I believe allowing assets to be added across all album levels might not be as beneficial as it seems. This approach could potentially complicate the user experience and lead to less organized libraries.

**Albums are a way to group assets, no more, no less. I think it's a bad design choice to deviate from that by allowing albums inside albums**

In my view, albums, folders, and tags serve distinct purposes mixed.

Let me detail a bit more my opinion on what shall be the perfect system on the long term, I think it's kind of important to avoid taking bad directions by making quick choices (even if this has been talked for a long time in issues or discussions, there is no final consensus at the end).

 #### Albums/Collection
It facilitate the presentation and quick access of a set of assets through the user interface, ideal for showcasing or sharing selected collections. To accomodate big libraries, it should be possible to organize album in a tree (why not naming that collection, album-set, album-group).

#### Folders
They serve a more structural role, organizing assets in a hierarchical manner that mirrors (or is based of) storage structure. I also think this should be presented in a way in Immich.
Ultimately, this could be used to organize physicaly a library directly from Immich (like on Lightroom Classic), I understand this is not the direction of Immich, but if it's compatible with everything else and UX friendly... why not. I saw multiple feature requests about that.

#### Tags
They provide a flexible, non-hierarchical method of categorizing assets, allowing for dynamic grouping based on themes, subjects, or any other criteria without the constraints of a fixed structure. (It does not mean tag themself could not be organized in a a hierarchical manner for easier browsing). Idealy tags are embedded inside the asset exif info, and can be used for searching, grouping, and why not creating smart-albums.

#### Smart albums
Another concept to consider in the future would be the possibility to create "smart-albums", which are read-only albums, based on a search query, or why not on the storage structure (has been asked multiple times).

_Incorporating these distinct mechanisms can enhance Immich's usability by catering to various organizational preferences and use cases, ensuring that users can manage their libraries efficiently and intuitively._

---

I detailed this much just to make a point : albums are not folders, and are not tags.

When I'm in a photo gui, I would want the following beavior:
* tags show me all assets tagged with the tag (even if the tag is within a hierarchy)
* albums show me assets in it (no more, no less)
* folders show me the physical structure of my storage

Just in case PG has the concept of ltree: https://www.postgresql.org/docs/current/ltree.html
They could be used instead of a parentId to represent a hierarchical structure for albums.

Of course this is just my opinion 😸

**Comment by alextran1502** [comment]
@Tronix117 your post answered some of my questions about the benefit of different mechanism, thank you! I will contemplate on your points

**Comment by alextran1502** [comment]
@Tronix117 

> This approach could potentially complicate the user experience and lead to less organized libraries

Can you help elaborate on this, with some example scenarios?

**Comment by Tronix117** [comment]
> Can you help elaborate on this, with some example scenarios?

Of course, there is two bad usage I can think of right now before going to bed, but I'm sure we can find more.

## 1. Navigational complexity

Let's say I create the following nested structure (maybe a bad one but if you give him the possibility, the user can do whatever he wants):

```
- Vacations
- - 2023
- - - Greece
- - - - Santorin 
- - - - Mykonos
```

Ok, I remember I also want to a restaurant on the trip to Santorini, where did I put it ? In Santorini album ? In Greece directly ? Where did I out those Paris airport photos on the way to Greece ??
It's a simple exemple, but I'll have to deep explore all sub-albums hierarchy to find the photo. 

Plus in the way I think it will be presented in the GUI (not a tree view, because it's not adapted to mixed album/assets in tree items), it means I'll have to first open Vacation, then 2023, then... 

Finally if you add a bit of sharing parent albums in a multi-users environment, it could quickly become a big mess...


## 2. Dilute hierarchical intent

The primary intent of a hierarchical structure is to categorize and organize. If parent albums, which should serve as categories, also contain assets, it blurs the lines between the levels of organization, making it harder for users to intuitively understand the structure and navigate through it.

**Comment by midzelis** [comment]
My $.02 - I agree with @Tronix117 - I use Adobe Lightroom to manage a huge (200k+) set of photos ... Lightroom has a notion of "Collections" (basically albums) and things called "Collection Sets" - Collection sets can only hold other Collection Sets, Collections or Smart Collections (query-based albums), but not images. After using Lightroom for over 10yrs, I would say this style of management is very good. 

The downsides would be that you can't just import a folder of photos and turn it into albums and album sets, but I would +1 @Tronix117 and say that it would lead to better organization. Having albums and images side-by-side in the same album feels odd. 

At the same time, I suppose you could keep with a single concept of "album" and dynamically constrain its contents. Maybe an empty album can contain either a nested album or an image. But once you add a nested album, you can no longer add images to it. And vice versa. If you do it this way, you could put this setting behind a feature flag. All you would need to do is add additional validation to the add-operations of an album, and the flag would control whether the validation is applied. So you could have it both ways.

**Comment by alextran1502** [comment]
Closing due to conflict of the way we plan to handle this feature. Will revisit later

**Pull request closed without merging**
