### PR TITLE
chore(mobile): separate build flavors

### PR DESCRIPTION
**Pull request by alextran1502**
Allow `release` build and `debug` build to be installed separately on the device

### CODE REVIEW

**Review by zackpollard — APPROVED** [review]
LGTM, is this iOS only?

**Comment by alextran1502** [comment]
@zackpollard yes, Android is already setup with this mechanism

**Comment by zackpollard** [comment]
> @zackpollard yes, Android is already setup with this mechanism

Ah! I was not aware, I have used a seperate device for testing for a long time now :laughing:

**Comment by zackpollard** [comment]
test

**Pull request merged**
