### PR TITLE
feat: smart album

### PR DESCRIPTION
**Pull request by alextran1502**
- [ ] Generate migration

### CODE REVIEW

**Comment by nopoz** [comment]
Why was this closed?

**Comment by alextran1502** [comment]
@nopoz stale and we have a better idea

**Comment by janstadt** [comment]
@alextran1502 any updates here? Curious what the better idea is. Basically im just looking for a way to create albums for specific faces.

**Comment by alextran1502** [comment]
@janstadt automation workflow, think of custom events, conditions and effect, like NodeRED

**Comment by janstadt** [comment]
Interesting. So basically youd set up a condition when a new face is detected/uploaded to create or add the photo to a specific album. That certainly would give us a lot more flexibility.

**Comment by alextran1502** [comment]
@janstadt correct, so you can perform action not only adding to an album but also send an email or send a web hook event somewhere. Basically a lot more flexibility and cover more usecases

**Comment by janstadt** [comment]
I like it. Whats the timeframe for this feature?

**Comment by alextran1502** [comment]
@janstadt Couple of months on my high priority list

**Comment by adamncsu** [comment]
> @janstadt Couple of months on my high priority list

Is this still a priority? Any roadmap to follow progress?

**Pull request closed without merging**
