### PR TITLE
feat(ci): Automatic categories in generated release notes

### PR DESCRIPTION
**Pull request by bo0tzz**
We will need to label PRs appropriately to make use of this, so I've also added a check to enforce that ;)

### CODE REVIEW

**Review by jrasm91 — APPROVED** [review]

**Review by zackpollard — APPROVED** [review]
Love it, make sure to set that job as required once this is merged (or right before) 😄

**Comment by alextran1502** [comment]
Hmm I usually group them together first, then put it in Google Docs to work on additional information for the release notes. After the release note is generated from GHA, then I copy the collaborative note over.

**Comment by bo0tzz** [comment]
You still use the generated release notes as a starting point, right? This just does some pre-grouping for you in those.

**Comment by alextran1502** [comment]
> You still use the generated release notes as a starting point, right? This just does some pre-grouping for you in those.

Not really, I generate the release note manually first from the draft to get all the PRs, then group it and modified it in text editor

**Review by alextran1502 — APPROVED** [review]

**Pull request merged**
