### PR TITLE
feat: user preferences for archive download size

### PR DESCRIPTION
**Pull request by danieldietzler**
Related to #7542

Add a user preference to store preferred download size for downloading archives (multiple assets).

image

### CODE REVIEW

**Comment by aviv926** [comment]
After merging this PR will [this part](https://immich.app/docs/features/shared-albums#:~:text=ARCHIVE%20SIZE%20LIMITED.) of the documentation become irrelevant?

**Comment by jrasm91** [comment]
> After merging this PR will [this part](https://immich.app/docs/features/shared-albums#:~:text=ARCHIVE%20SIZE%20LIMITED.) of the documentation become irrelevant?

That's the goal. It should use the user's preference for download size instead.

**Review by jrasm91 — APPROVED** [review]
tyvm

**Comment by jrasm91** [comment]
@aviv926 I can't be bothered to update the documentation, so feel free to make the change if you want :smile:

**Pull request merged**
