### PR TITLE
feat(web): improve search bar + add to search page

### PR DESCRIPTION
**Pull request by michelheusschen**
Improved search bar by adding a search icon and a button to quickly clear the search bar. To make follow up searches easier, the search bar is added to the search page. Also made some small styling changes, mostly for better responsive design and zooming in/out. Below some screenshots, but probably best to try it out yourself.

Search in navigation bar
image

Header for `/search` page
image

### CODE REVIEW

**Comment by bo0tzz** [comment]
Very nice :D

If you do two searches in a row, the back button ends up toggling between them rather than returning to the page you originally came from.

**Comment by michelheusschen** [comment]
> Very nice :D
> 
> If you do two searches in a row, the back button ends up toggling between them rather than returning to the page you originally came from.

Yup, that should be an easy fix though

**Comment by bo0tzz** [comment]
Thanks :) Now previous searches aren't shown when using the back button, instead it returns directly to the gallery. That's not a big issue to me, just thought I'd mention it.

**Comment by michelheusschen** [comment]
> Thanks :) Now previous searches aren't shown when using the back button, instead it returns directly to the gallery. That's not a big issue to me, just thought I'd mention it.

Not showing previous searches is intentional because I think that's the best approach in this situation. The main method to navigate away from the search page is the back button and having to go through all your previous searches would be pretty annoying. If we were to add the header and sidebar to the search page or add another way of navigating, then going back should cycle through the previous searches.

**Review by bo0tzz — APPROVED** [review]
<3

**Review by jrasm91 — APPROVED** [review]

**Pull request merged**
