### PR TITLE
chore: Remove old startscripts

### PR DESCRIPTION
**Pull request by bt90**
## Description

as discussed in https://github.com/immich-app/immich/pull/3350#discussion_r1269514277

### CODE REVIEW

**Comment by bt90** [comment]
@alextran1502 @jrasm91 this is a follow-up to #2689 which removes the old scripts. This should be part of the release changelog, as this will break installations that haven't yet adapted their configurations for the new start script.

**Comment by jrasm91** [comment]
Do we need to make this breaking change now for any specific reason?

**Comment by bt90** [comment]
Nope. Just a cleanup PR.

**Comment by jrasm91** [comment]
Up to @alextran1502 if we want to do this now. The original idea was to group it in with the next release that required a docker compose change.

**Comment by bt90** [comment]
#3350 *might* require changes to the compose file. Let's wait for the dust to settle.

**Comment by jrasm91** [comment]
No breaking docker compose changes at the moment. This is easy enough to re-create in the future so I'm going to close it for now.

**Pull request closed without merging**
