### PR TITLE
fix(mobile): Explore places and things now use the proper search endpoint

### PR DESCRIPTION
**Pull request by martyfuhry**
Before, tapping a location or place in the "Search" would simply do a search query with that label as the text. Now, we properly use the new search API.

image
image

Needs #2076 merged in first.

### CODE REVIEW

**Comment by alextran1502** [comment]
Marty, I think since we use the general search endpoint to get the result for Things and Places, we don't have to split each into separate routes but consolidate them into one search result
page, unless you have other reason not to

**Comment by martyfuhry** [comment]
> Marty, I think since we use the general search endpoint to get the result for Things and Places, we don't have to split each into separate routes but consolidate them into one search result page, unless you have other reason not to

So before, these were just querying the search API with their label, e.g. `search?q=Athens`. This updates the search endpoint to use the proper query filter, e.g. `search?exifInfo.city=Athens`. For objects, this query filter is different, e.g. `search?smartInfo.objects=cup`.

If you'd like to combine these into one page, I'm not sure how to orchestrate the `Provider` necessary to drive both scenarios, as they have different query signatures. Or maybe you had something better in mind. Maybe you'd like to consolidate all of the Search Results into a single page that can take parameters and then call a more generic Search Provider with those parameters. I think this would be a great refactor. Of course, it can always be done in a separate PR, if you'd prefer.

I'm happy to refactor here, especially if "Places" and "Locations" are going to scale out in the future. I'm not extremely familiar with the search explore functionality, admittedly. I just looked at what was being done in the web side.

**Comment by alextran1502** [comment]
Marty, can we close this PR?

**Comment by martyfuhry** [comment]
Yup, I think you implemented all of this and there's nothing here worth salvaging.

**Pull request closed without merging**
