### PR TITLE
fix(server): storage migration job move files without exifInfo.fileSizeInByte

### LINKED ISSUE #6375: [BUG] Storage migration job skipping files
### The bug

When I change the storage label for my users not all files are moved to the new storage label path. The interface shows multiple UNTRACKS FILES and logs shows "ERROR [StorageTemplateService] Asset NAMEOFASSET missing exif info, skipping storage template migration" during migration job.

The files that are still in the old storage label path are both videos and pictures.

What to do?

### The OS that Immich Server is running on

debian

### Version of Immich Server

v1.92.1

### Version of Immich Mobile App

v1.92.0

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${LIBRARY_LOCATION}:/usr/src/app/upload/library
      - ${UPLOAD_LOCATION}:/usr/src/app/upload/upload
      - ${THUMBS_LOCATION}:/usr/src/app/upload/thumbs
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - ${VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${LIBRARY_LOCATION}:/usr/src/app/upload/library
      - ${UPLOAD_LOCATION}:/usr/src/app/upload/upload
      - ${THUMBS_LOCATION}:/usr/src/app/upload/thumbs
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - ${VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - ${LIBRARY_LOCATION}:/usr/src/app/upload/library
      - ${UPLOAD_LOCATION}:/usr/src/app/upload/upload
      - ${THUMBS_LOCATION}:/usr/src/app/upload/thumbs
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - ${VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    #image: postgres:14
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
DB_HOSTNAME=<redacted>
DB_USERNAME=<redacted>
DB_PASSWORD=<redacted>
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=/path/immich
TYPESENSE_API_KEY=<redacted>
PUBLIC_LOGIN_PAGE_MESSAGE=
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
TZ=Europe/Stockholm
LIBRARY_LOCATION=/path/library/
THUMBS_LOCATION=/path/thumbs/
UPLOAD_LOCATION=/path/upload/
PROFILE_LOCATION=/path/profile/
VIDEO_LOCATION=/path/encoded-video/
```

### Reproduction steps

```bash
1. Set new Storage label
2. Run the Storage Migration Job
3. Immich has UNTRACKS FILES (100+)
4. Logs says "ERROR [StorageTemplateService] Asset NAMEOFASSET missing exif info, skipping storage template migration"
...
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mio-19**
This might fix https://github.com/immich-app/immich/issues/6375 https://github.com/immich-app/immich/discussions/6411
I haven't tested yet.

### CODE REVIEW

**Comment by alextran1502** [comment]
Convert this PR to draft. Can you help with the steps of reproducing the behavior before and after this fix?

**Comment by zackpollard** [comment]
We should always have a filesize on the database for every file. If we don't then there are other problems. If we change to this method and the file is corrupt at the source somehow we would never know.

**Comment by zackpollard** [comment]
Another issue with this PR I didn't initially realise, we just always need the exif info for template migration jobs. The if clause is if(!exifInfo || !exifInfo.fileSizeInBytes), it's written that way as we need exifInfo, but at that point we specifically need fileSizeInBytes. The template migration job won't be able to construct the new path for the file without the exif info, as it relies on certain information. If the exif info exists, then fileSizeInBytes should absolutely exist. I'm going to close this PR, as this error should be fixed for valid files with exif by re-running the missing metadata job.

**Comment by jrasm91** [comment]
Just want to point out that the exif entry, specifically with filesize is now created during asset upload itself. Ie filesize is saved in exif table when a file is uploaded starting in a recent release. Which further points at this being a non issue moving forward.

**Pull request closed without merging**
