### PR TITLE
feat(nginx): use non-root image for immich-proxy

### PR DESCRIPTION
**Pull request by PixelJonas**
This PR replaces the `nginx:latest` image used with `ubi9/nginx-120:latest` changing the image to not use a privileged user as well as a privileged port.

Running "privileged" containers is considered bad for containers, as most security flaws orbit around the user within the container (in this case `root`) bleeding into the host system. As such containers should be started by non-root users and don't use privileged ports at all.

This would be a breaking change for people not updating their `docker-compose.yaml` as they need to change the default port-mapping from `2283:80` to `2283:8080`.

### CODE REVIEW

**Comment by PixelJonas** [comment]
I've tested the image locally and pushed it to

`quay.io/jjanz/immich-proxy:nginx-ubi`

It should be drop-in replacement (with needing to change the port-mapping to `2283:8080`) if someone wants to test this

**Comment by alextran1502** [comment]
Tested and confirmed that it worked on `dev` environment

**Comment by alextran1502** [comment]
Tested `quay.io/jjanz/immich-proxy:nginx-ubi` on `production` environment and it worked

**Comment by alextran1502** [comment]
Can you make the change to all the docker-compose files? I will merge this PR once that is done

**Comment by PixelJonas** [comment]
I've added the correct port for staging as well - Is there any place where we could communicate that as a breaking change?

I've thought about this and maybe we can change the image name, so that the setup of people is not breaking after pulling a new image (something like `immich-nginx`)

What do you think @alextran1502 ?

**Comment by alextran1502** [comment]
Right now we expect the user to use the docker-compose file with the release tag. When we push out the release note, we will also mention breaking change and migration method

**Comment by PixelJonas** [comment]
LGTM - I've added a snippet for the Breaking Changes in this post. Is there anything else I can do to get this merged?


#651 *Breaking Change* 
`immich-proxy` switched from using port `80` which was used inside of the container to `8080` to drop dependency on a privileged user inside the container. This reduces a potential security risk of someone being able to impersonate that user on the host.

As a result you will need to change your `docker-compose.yaml` to reflect this change, by changing the port-binding from

```
  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    ports:
      - 2283:80
```
to
```
  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    ports:
      - 2283:8080
```

re-running
```bash
curl -o- https://raw.githubusercontent.com/immich-app/immich/main/install.sh | bash
```
will also ensure you get the latest version of the docker-compose.yaml

a full example of the always-up-to-date docker-compose.yaml can be found [in our repo](https://raw.githubusercontent.com/immich-app/immich/main/docker/docker-compose.yml)

**Pull request merged**
