### PR TITLE
feat(mobile): Adds gps locator to map prompt for easy geolocation

### PR DESCRIPTION
**Pull request by sirebellum**
Just a quick idea to set gps coordinates using the pop up interface. Makes setting geolocation a lot easier.

First time I'm programming in dart(?), please feel free to suggest/make edits.

Screenshot_20240108-233500_Immich

### CODE REVIEW

**Comment by shenlong-tanwen** [comment]
Thanks for your contribution. But we are in the process of refactoring the map to use a different library instead and all the map related pages are refactored in the process. Can you make your changes on top of the below PR instead? 
- #6087

**Comment by sirebellum** [comment]
> Thanks for your contribution. But we are in the process of refactoring the map to use a different library instead and all the map related pages are refactored in the process. Can you make your changes on top of the below PR instead?
> 
>     * [refactor(mobile): maplibre #6087](https://github.com/immich-app/immich/pull/6087)

@shenlong-tanwen Could you point me at the file where the map interface lives now? It looks like things have moved around a bit. Thanks!

**Comment by shenlong-tanwen** [comment]
> @shenlong-tanwen Could you point me at the file where the map interface lives now? It looks like things have moved around a bit. Thanks!

The map location page is actually a route and not a widget. So it is now located at `mobile/lib/modules/map/views/map_location_picker_page.dart`. You can use the following method to get the current geo coordinates as well `MapUtil::checkPermAndGetLocation`.

**Comment by sirebellum** [comment]
@shenlong-tanwen Refactored...

I took the liberty of rebasing on your branch and setting the merge target there. If you don't want this in there, no problem. Just thought it would work better this way.

**Comment by shenlong-tanwen** [comment]
> I took the liberty of rebasing on your branch and setting the merge target there. If you don't want this in there, no problem. Just thought it would work better this way.

Yes, We can use my branch as the merge target. Can you add a screenshot to the PR description as well. The change is good but I'm not sure if we've to have the button in the bottom bar or to keep it stacked above the map in the bottom right corner of the map or to push it to the map app bar and keep it in the top right corner of the map. What do you think about showing it above the map instead of the bottom bar?

**Comment by sirebellum** [comment]
> > I took the liberty of rebasing on your branch and setting the merge target there. If you don't want this in there, no problem. Just thought it would work better this way.
> 
> Yes, We can use my branch as the merge target. Can you add a screenshot to the PR description as well. The change is good but I'm not sure if we've to have the button in the bottom bar or to keep it stacked above the map in the bottom right corner of the map or to push it to the map app bar and keep it in the top right corner of the map. What do you think about showing it above the map instead of the bottom bar?

I'm about to push a change that puts the choose and gps buttons next to each other. I'll post a screenshot and then consider something above the map.

**Comment by sirebellum** [comment]
I personally like the buttons at the bottom because of thumb-reach. Open to suggestions though.

**Comment by shenlong-tanwen** [comment]
> I personally like the buttons at the bottom because of thumb-reach. Open to suggestions though.

This looks great. Thank you. Why is there a grey top area in the screenshot shared instead of the map completely filling the area? This is not related to this PR but want to know if there is any issue with the current refactoring 😅

**Comment by sirebellum** [comment]
> > I personally like the buttons at the bottom because of thumb-reach. Open to suggestions though.
> 
> This looks great. Thank you. We don't really need those comments though. We can remove them since the code is self explanatory. Also, Why is there a grey top area in the screenshot shared instead of the map completely filling the area? This is not related to this PR but want to know if there is any issue with the current refactoring 😅

I run an early build of crdroid so I can't say I trust the environment entirely, but it almost seems like a bug. How would I investigate this?

**Comment by shenlong-tanwen** [comment]
> I run an early build of crdroid so I can't say I trust the environment entirely, but it almost seems like a bug. How would I investigate this?

You can check if the actual map view / other map thumbnails are displaying this issue as well. Then it is most likely in the underlying library we are using. Can you move around in the map and check if it is getting updated?

Can you handle the lint issue so we can get this merged in my refactoring branch? If you'd like me to handle it, do let me know and I can take care of it and get this merged. Thanks a lot for your contribution.

**Comment by sirebellum** [comment]
> > I run an early build of crdroid so I can't say I trust the environment entirely, but it almost seems like a bug. How would I investigate this?
> 
> You can check if the actual map view / other map thumbnails are displaying this issue as well. Then it is most likely in the underlying library we are using. Can you move around in the map and check if it is getting updated?
> 
> Can you handle the lint issue so we can get this merged in my refactoring branch? If you'd like me to handle it, do let me know and I can take care of it and get this merged. Thanks a lot for your contribution.

My pleasure!

It seems my status bar is being rendered at a huge value. It is slightly translucent and I can see the map updating underneath it.

**Comment by shenlong-tanwen** [comment]
> It seems my status bar is being rendered at a huge value. It is slightly translucent and I can see the map updating underneath it.
> 
> Edit: Seems to be doing it on my stock samsung tablet as well. Looks like the height is the same as the gray bar at the bottom.
> 

The map page and map location selection page mostly have similar scaffolds. So I'm not sure what's happening here and I cannot reproduce it on my end as well. I'll try testing this across different device dimensions using emulator later today. Feel free to take a dig at it if you want to as well.

**Pull request merged**
