### PR TITLE
fix(server): convert to nv12 before using nvenc

### PR DESCRIPTION
**Pull request by mertalev**
## Description

This is a small fix for NVENC accel. It's missing `format=nv12`, so HDR content will fail and fallback to software transcoding. With this change, they'll be converted to the format expected by GPUs.

## How Has This Been Tested?

I encountered this bug while testing the tone-mapping PR. With this change applied, the HDR video I used for testing transcoded without error.

### CODE REVIEW

**Review by jrasm91 — APPROVED** [review]

**Comment by alextran1502** [comment]
Does tone-mapping PR need to be merged first?

**Comment by mertalev** [comment]
No, they're independent. But the tone-mapping PR has this fix built-in.

**Comment by alextran1502** [comment]
Can you help rebasing this PR as well?

**Comment by mertalev** [comment]
This one shouldn't be needed anymore since the tone-mapping PR included the same fix.

**Pull request closed without merging**
