### PR TITLE
feat(server): generate checksum for previous uploaded assets

### PR DESCRIPTION
**Pull request by panoti**
Just temporary for the dev releases. We can remove it for official release. On the other hand, we can use it to restore/recover fail jobs as well.

### CODE REVIEW

**Comment by alextran1502** [comment]
Which mechanism are you planning to use to trigger the job? Cronjob?

**Comment by panoti** [comment]
> Which mechanism are you planning to use to trigger the job? Cronjob?

The queue only run at bootstrap time now. Cron-job is also good idea.

**Comment by panoti** [comment]
There is a "small" problem. What will we do with duplicate uploaded assets? Delete or do approval?

**Comment by alextran1502** [comment]
I think skipping with null value is fine.

**Comment by alextran1502** [comment]
Can you take a look at the test and make sure it passes before we merge the PR?

**Comment by panoti** [comment]
> Can you take a look at the test and make sure it passes before we merge the PR?

```
ENOENT: no such file or directory, open 'upload/3ea54709-e168-42b7-90b0-a0dfe8a7ecbd/original/116766fd-2ef2-52dc-a3ef-149988997291/51c97f95-244f-462d-bdf0-e1dc19913516.jpg'
```
I think it come from your test env.

**Comment by panoti** [comment]
> Maybe, keep the duplicate with more exif tags and skip other ?

Hi @Nonobis, the uploaded duplication will be kept.

**Pull request merged**
