### PR TITLE
fix(documentation): Update to latest default config

### PR DESCRIPTION
**Pull request by jansohn**
The default configuration seems to be outdated. I compared it to the demo app as well as a newly spun-up local instance.

### CODE REVIEW

**Review by danieldietzler — APPROVED** [review]
It will be outdated with 1.92 again lol
It's fine with me to merge this though

**Comment by mertalev** [comment]
The next release will have object tagging removed, so if we merge this PR we'll have to revert it very soon. (Possibly *very* soon)

**Comment by jansohn** [comment]
> The next release will have object tagging removed, so if we merge this PR we'll have to revert it very soon. (Possibly _very_ soon)

Every release that changes the settings configuration file should update the documentation, too in my opinion. Maybe we can somehow reduce the effort by linking to the file content instead...

**Comment by mertalev** [comment]
It was updated (which is why those fields aren't there anymore), but the issue is that the docs on the website are based on main, not the latest release.

**Comment by jansohn** [comment]
Makes sense, so I'll close this again.

**Pull request closed without merging**
