### PR TITLE
fix(ml): better model unloading

### LINKED ISSUE #2074: [BUG] Gunicorn CPU & Memory utilization high even when no jobs running
### The bug

After updating to include the typesense container and running the "Encode Clip" job, CPU and memory utilization by Gunicorn is still incredibly high.

image

Restarting the containers results in more moderate usage.

image

Running on a Rock 5B SBC.

### The OS that Immich Server is running on

Armbian 23.02 Jammy

### Version of Immich Server

1.51.1

### Version of Immich Mobile App

1.51.0 Build 74

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: [ "/bin/sh", "./start-server.sh" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
      - typesense
    networks:
      - immich-internal

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: [ "/bin/sh", "./start-microservices.sh" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
      - typesense
    restart: always
    networks:
      - immich-internal

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /mnt/ssd/immich/model-cache:/cache
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - immich-internal

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:release
    entrypoint: [ "/bin/sh", "./entrypoint.sh" ]
    env_file:
      - stack.env
    restart: always
    networks:
      - immich-internal

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.0
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    logging:
      driver: none
    volumes:
      - /mnt/ssd/immich/tsdata:/data
    env_file:
      - stack.env
    networks:
      - immich-internal
      
  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always
    networks:
      - immich-internal

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - /mnt/ssd/immich/database:/var/lib/postgresql/data
    restart: always
    networks:
      - immich-internal
  
  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:release
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always
    networks:
      - proxy
      - immich-internal

volumes:
  pgdata:
  model-cache:
  tsdata:

networks:
  proxy:
    external: true
  immich-internal:
    external: true
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=/mnt/ssd/immich/upload
TYPESENSE_API_KEY=api-key
PUBLIC_LOGIN_PAGE_MESSAGE=
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
```

### Reproduction steps

```bash
1. Click "All" to queue the Encode Clip job
2. Wait 2 days (in my case).
3. When all jobs are complete, check CPU utilization in gotop
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mertalev**
## Description

This adds a more effective way to reduce the ML container's memory consumption when idle. 

The current approach is to remove the model objects and let Python garbage collect them. However, much of the memory remains allocated after this as the underlying runtimes are not affected by Python's garbage collection and manage their memory independently.

The approach here is to run the app with gunicorn as a process scheduler. The app periodically checks if there have been any requests in a certain period of time and gracefully shuts down if not. gunicorn then terminates the app process, freeing its memory, and restarts the app with a new process. This is admittedly not the most elegant solution, but it is the most effective one that I've found and the results should speak for themselves.

This is a similar approach to #2758, but is much more lightweight and results in lower memory consumption at both peak and idle.

Fixes #2074

## How Has This Been Tested?

1. Start the container with `MACHINE_LEARNING_MODEL_TTL=30` or a similarly low number for faster testing
2. Run `docker stats --no-stream` on startup to see its initial RAM usage
3. Run the `tag objects`, `encode clip` and `recognize faces` jobs to load each model and process some requests
4. Wait for the model TTL duration (it may take a bit longer as it's only polled every 10s)
5. Run `docker stats --no-stream` again to see its current usage

Compared memory usage

### CODE REVIEW

**Comment by mertalev** [comment]
It seems repeatedly unloading and loading models still increases memory usage somehow. It's specifically an issue with PyTorch models. What a pervasive bug... Maybe I should make a repro script and file an issue.

**Comment by mertalev** [comment]
As of latest testing, this change no longer has a memory leak. This may be due to less reliance on PyTorch, or possibly because of an upstream bug fix. It should be safe to use at this point.

**Review by jrasm91 — APPROVED** [review]

**Review by alextran1502 — APPROVED** [review]

**Comment by mchiappinam** [comment]
Unfortunately I still having CPU issues. After running a couple jobs, it stays in 200% useage after it's done, or after pausing, clearing... the only solution seems to be restarting Immich.

image
I'm running 1.88.2 btw

I'm sorry if this was not deployed yet, but I think it did, since it got merged into main 2 weeks ago, right?

**Comment by mertalev** [comment]
Could you post the logs for the ML container? Also, can you clarify how long you're waiting before checking CPU usage? The default is to nuke the process after idling for 5 minutes, so it should really not have any CPU usage after this as long as there are no ML jobs running.

**Comment by mchiappinam** [comment]
I'm actually unable to reproduce it again since yesterday 🤡 maybe the machine learning services saw this thread and got scared 😝 
Thanks team!

**Comment by mertalev** [comment]
Haha, if it ever comes up again please do reach out about it.

**Pull request merged**
