### PR TITLE
feat(album): album view sort order

### PR DESCRIPTION
**Pull request by alextran1502**
This PR adds a button to toggle the album sort order on the mobile app. 

https://github.com/user-attachments/assets/7ab3967c-3e98-40ee-9acb-ce25da05a62b

### CODE REVIEW

**Comment by mertalev** [comment]
Can you make the title etc. not flicker when the sort order changes?

Also, I think we should do another patch release without features for the live photo issue before merging features.

**Comment by alextran1502** [comment]
Yeah we can have this feature in the next release. Fixing the flicker will have to refactoring the whole page since the data of the page right now depends on the album provider which is watching the database changes to the album record and trigger the whole page rebuild

**Comment by mertalev** [comment]
Okay, well I think it should be refactored first then because it looks a bit janky when you toggle.

**Comment by alextran1502** [comment]
@mertalev I think refactoring the page is outside the scope of this PR. Also I will need to discuss with you how we should restructure that fix since the whole page depends on that one provider, and if any property changes, it rerenders the page

**Review by mertalev — APPROVED** [review]

**Pull request merged**
