### PR TITLE
feat(server): support simple webhook

### LINKED ISSUE #627: [Feature]: Be notified when pictures are added in album #625
### Feature detail

In webapp and mobile app : 

- As the owner of an album, I would like to be notify when someone add pictures.
- As a viewer of an album, I would like to be notify when someone add pictures

I think that a rss feed could be a simple solution. 
A webhook could be a better solution to be notified or to integrate with n8n or IFTTT.

### Platform

Server

### PR DESCRIPTION
**Pull request by panoti**
Webhook can help everybody can trigger a `zapier`, `n8n` pipline easier. We can implement some external tasks (eg: [Geolocation interpolation](https://github.com/immich-app/immich/issues/566), [Face recognization](https://github.com/immich-app/immich/issues/294)) as plugins/addons by using webhook.

- [x] Remove hard-code `http://immich-machine-learning:3003/image-classifier/tag-image` and `http://immich-machine-learning:3003/object-detection/detect-object` away from worker service. Machine learning service is standalone now. Everyone can launch it only when necessary.
- [x] Create webhook interface `POST <WEBHOOK_URL>` with payload:
```json
{
  "type": "AssetCreationEvent",
  "asset": {
    "id": "assetId",
    ...
  }
}
```
- [x] Create api `POST /webhook` on ml service to received webhook request from immich server.

### CODE REVIEW

**Comment by alextran1502** [comment]
Is this PR for moving the rest api invoked from the server to pub/sub?

**Comment by panoti** [comment]
> Is this PR for moving the rest api invoked from the server to pub/sub?

Only for machine learning service. Api service can communicate with machine learning service by using Redis broker.

**Comment by alextran1502** [comment]
> > Is this PR for moving the rest api invoked from the server to pub/sub?
> 
> 
> 
> Only for machine learning service. Api service can communicate with machine learning service by using Redis broker.

The communication between the server/microservices and the machine learning containers is intentionally designed to use REST apis so that people with their own customs model can make a simple web server as a drop in replacement for either object detection or image classification

**Comment by panoti** [comment]
> The communication between the server/microservices and the machine learning containers is intentionally designed to use REST apis so that people with their own customs model can make a simple web server as a drop in replacement for either object detection or image classification

I found that machine learning service is optional. Throwing error maybe not good technically in the case of service not available. User can customs their model easily as well without changes, just need to start the machine learning service. Machine learning service listen event from broker and don't care about API or microservice service. The current implementation, you can see microservice depend on machine learning service address when create http request.

**Comment by panoti** [comment]
> The communication between the server/microservices and the machine learning containers is intentionally designed to use REST apis so that people with their own custom model can make a simple web server as a drop in replacement for either object detection or image classification

If users wanna custom machine learning service in other programming language like python, R, ... I think they also use redis pub/sub easier. Of course, REST interface would be simpler, but I don't want the worker service to be dependent on other service addresses.

**Comment by alextran1502** [comment]
I prefer simplicity in this matter.

**Comment by panoti** [comment]
> I prefer simplicity in this matter.

I have a thought about webhook. I will move to webhook approach.

**Comment by alextran1502** [comment]
What are you trying to accomplish with this PR?

My goal for the drop-in replacement is for the user spin up their web server that runs their ML model. Then from Immich's side, we make an environment variable for the current hard-coded endpoint that is now the machine learning container's DNS, and then the job should be done.

**Comment by panoti** [comment]
> What are you trying to accomplish with this PR?
> 
> My goal for the drop-in replacement is for the user spin up their web server that runs their ML model. Then from Immich's side, we make an environment variable for the current hard-coded endpoint that is now the machine learning container's DNS, and then the job should be done.

My goals are:
1. Remove dependence between worker service and machine learning service.
2. Create a general-purpose method to hook event asset creation so that we can trigger a workflow/pipeline for other tasks (like ML job, my custom `n8n` workflow, ...)

**Comment by panoti** [comment]
`n8n` workflow can receive messages from redis pub/sub, so I think using redis pub/sub is general-purpose method. But you said that REST api id simpler with env var. I think we can create `WEBHOOK_URL` var for your goals. That's all.

**Comment by bo0tzz** [comment]
Is this PR still alive, or can/should it be closed?

**Comment by alextran1502** [comment]
I like this feature, and I would like to keep this PR open as a reminder of how to do it in the future

**Pull request closed without merging**
