### PR TITLE
fix(server): keep full datetime precision from database

### PR DESCRIPTION
**Pull request by fyfrey**
we have had these sync issues due to JavaScript reducing precision of DateTime when converting to JS Date. This still affects changes for albums, users etc. in the app and can result in not doing an update while it would be needed etc. This draft PR changes all related fields (`createdAt`, `updatedAt`, `deletedAt`) in the server entities and DTOs to type `string` instead of `Date`. DateTime information is passed through the JavaScript code as full precision ISO Strings.

### CODE REVIEW

**Comment by bo0tzz** [comment]
Breaking change, right?

**Comment by fyfrey** [comment]
> Breaking change, right?

no API changes at all.

**Comment by bo0tzz** [comment]
Ah, the API type was already string of course. Nice :D

**Review by jrasm91 — COMMENTED** [review]
LGTM

**Comment by jrasm91** [comment]
With kysely we should be able to move to using luxon DateTime objects everywhere, at that point we can migrate the dto parsing to convert incoming requests to those objects as well, and this should also solve the problems/limitations of javascript Date objects.

**Pull request closed without merging**
