### PR TITLE
feat(mobile): Add dismiss action on app_bar_dialog

### PR DESCRIPTION
**Pull request by Lauritz-Tieste**
I have intuitively tried to perform this action several times. It bothered me, so now you can close the profile dialog by swiping down.

Note: Since I do not own a mac, it has not been tested on apple devices. However, it has been tested in the Android emulator and on a Samsung A55.

https://github.com/user-attachments/assets/c312c560-5c42-4dfa-8c50-7cfe07bd687f

### CODE REVIEW

**Comment by alextran1502** [comment]
Can you try to increase the font size of the phone and test if the swipe-down action also gets triggered by scrolling the sheet?

**Comment by Lauritz-Tieste** [comment]
Of course. Everything behaves as it should.


https://github.com/user-attachments/assets/080acd25-dca9-4077-b241-67b44cbc1354

**Review by alextran1502 — APPROVED** [review]

**Comment by alextran1502** [comment]
danke!

**Comment by Lauritz-Tieste** [comment]
@alextran1502 Have you tested this on iOS?

**Comment by alextran1502** [comment]
@Lauritz-Tieste Yes, it works fine

**Pull request merged**
