### PR TITLE
feat(mobile): Adding setting in mobile app to TLS client certificate

### PR DESCRIPTION
**Pull request by yjiang-c**
This is to add an advanced setting in Immich mobile app to import TLS client certificate and private key.

Some users deploy Immich server behind a reverse web proxy server like nginx. Through setting up reverse proxy server, immich client could be asked a TLS/SSL client certificate for authentication. This can add an additional secure layer to protect Immich server behind a reverse proxy.

https://github.com/immich-app/immich/assets/66518086/c36d548f-a473-4f0c-93ab-23e51cce6f58

### CODE REVIEW

**Comment by yjiang-c** [comment]
@alextran1502 Could you please approve another workflow test? Thanks!

**Comment by yjiang-c** [comment]
Sorry to fail the test again. I just push the commit to fix the test failure.

**Comment by yjiang-c** [comment]
It seems all tests passed. What is the next step to get approval?

**Comment by alextran1502** [comment]
I will run some errands manually testing

**Review by alextran1502 — APPROVED** [review]

**Comment by vekexasia** [comment]
hey @yjiang-c any reason why i cant click the import/remove?

**Pull request merged**
