### PR TITLE
chore: Add Qudana static analyzer

### PR DESCRIPTION
**Pull request by alextran1502**

### CODE REVIEW

**Comment by jrasm91** [comment]
What does this audit?

**Comment by alextran1502** [comment]
@jrasm91 Here are some top level list

```
Assignment issues
Async code and promises
Bitwise operation issues
Code Coverage
Code quality tools
Control flow issues
Dependency analysis
General
Imports and dependencies
Naming conventions
Node.js
Potentially undesirable code constructs
Probable bugs
```

However I am not sure if I have set it up correctly because it hasn't identified anything, which I doubt our code base is that good 😅

**Comment by bo0tzz** [comment]
Is this going to be another bot spamming comments on every pr? 👀

**Comment by alextran1502** [comment]
@bo0tzz probably, I am just trying it out to see what Qudana is, I don't have a plan to integrate it into the ci/cd pipeline yet

**Pull request closed without merging**
