### PR TITLE
fix(server): Correctly set album start and end dates

### PR DESCRIPTION
**Pull request by adamantike**
Currently, the query that retrieves album assets uses `ORDER BY assets.fileCreatedAt DESC`, which makes the existing logic return the start/end dates reversed (with `startDate` being taken from the first asset in the array).

Instead of using the index-based approach, this change iterates through assets to get the min/max `fileCreatedAt`. This will avoid any future issues, if the query ordering changes, or becomes customizable (e.g. in case the user prefers to visualize older assets first).

### CODE REVIEW

**Comment by alextran1502** [comment]
Hello, this means we move from O(1) to O(n) for the calculation, correct?

**Comment by adamantike** [comment]
That's right. If we *always* expect assets to be sorted by `fileCreatedAt`, but we allow both ascending or descending order, we could stay at O(1), and just swap start and end dates, if we find that `startDate > endDate`.

**Comment by alextran1502** [comment]
> That's right. If we _always_ expect assets to be sorted by `fileCreatedAt`, but we allow both ascending or descending order, we could stay at O(1), and just swap start and end dates, if we find that `startDate > endDate`.

I like this idea

**Comment by adamantike** [comment]
Just refactored the solution to go with that approach!

**Review by alextran1502 — APPROVED** [review]

**Pull request merged**
