### PR TITLE
fix(web): notification number of people when editing faces

### PR DESCRIPTION
**Pull request by martabal**
fix for #7341

### CODE REVIEW

**Review by jrasm91 — COMMENTED** [review]
Why do we have null and undefined types in the list in the first place? Can you just add truthy values to begin with?

**Comment by martabal** [comment]
That's what I was doing before https://github.com/immich-app/immich/pull/6751 

Do you prefer something like that ? `selectedPersonToReassign = Array.from({ length: peopleWithFaces.length }, () => null);`

**Review by danieldietzler — APPROVED** [review]

**Comment by waclaw66** [comment]
May I ask why this fix was closed before merge?

**Comment by martabal** [comment]
I had too many opened PRs. I will re-open it this evening

**Review by jrasm91 — APPROVED** [review]

**Pull request merged**
