### PR TITLE
feat(server): Add size parameter to explore endpoint

### PR DESCRIPTION
**Pull request by boenni23**
Fix for #6092. Adds a Places site for Web.

### CODE REVIEW

**Comment by boenni23** [comment]
You also created a fix for this issue. But you missed the number of cities that are fetched from the database. So this is a additional commit for the new places page.

**Review by boenni23 — COMMENTED** [review]
Just a merge conflict resolved

**Comment by alextran1502** [comment]
There has been a PR recently addresses this issue #6669

**Comment by boenni23** [comment]
Yes and this PR did not include fetching more than 12 Places.

**Comment by boenni23** [comment]
Sorry for the short answer. What I wanted to say is that `api.searchApi.getExploreData()` only takes 12 Places. So in order to show all places on this site you need to adjust the API too.

**Comment by jrasm91** [comment]
This PR is a little strange in that you call "explore" with -1 to get all the places. Explore is like a summary endpoint, and it seems better to have a dedicated endpoint to get a full list of places, potentially with pagination and other options, etc.

**Comment by jrasm91** [comment]
Closing, in favor of an implementation that uses the dedicated cities endpoint

**Pull request closed without merging**
