### PR TITLE
chore(web): Update the new version announcement text

### PR DESCRIPTION
**Pull request by Snowknight26**
The new version announcement text has been updated to fix some errors in the existing language, making it clearer that a new version of Immich (instead of application) is available.

I imagine this is Alex's text so keeping this PR as draft for now to ensure that the change is ok to make.

### CODE REVIEW

**Review by danieldietzler — APPROVED** [review]

**Comment by bo0tzz** [comment]
Maybe we should also update this to note reading the release notes carefully instead of just mentioning updating the compose/.env.

**Review by jrasm91 — APPROVED** [review]
You can change this on weblate though.

**Comment by Snowknight26** [comment]
> You can change this on weblate though.

Ahh thanks for the heads-up. Last time I made commits changes to English still had to be done via code. I can update it that way if that's the preferred approach.

**Comment by danieldietzler** [comment]
> > You can change this on weblate though.
> 
> Ahh thanks for the heads-up. Last time I made commits changes to English still had to be done via code. I can update it that way if that's the preferred approach.

Both is fine with weblate (assuming there aren't any conflicts, which there shouldn't in this case) :)

**Review by alextran1502 — APPROVED** [review]

**Pull request merged**
