### PR TITLE
chore(web): timeline bucketing by day

### PR DESCRIPTION
**Pull request by alextran1502**
This PR solves the issues of bucket render of a month can make the browser crash if a certain month has more than 4000 or 5000 assets by rendering the bucket by day grouping.

### CODE REVIEW

**Review by jrasm91 — COMMENTED** [review]
How did you test this?

**Comment by alextran1502** [comment]
I tested by running on local instance and check the console network tab as
well as seeing things are rendered correctly on the timeline and the
scrollbar

**Comment by jrasm91** [comment]
Nice. I was more wondering if you tested with different bucket sizes and distributions.

**Comment by alextran1502** [comment]
I am planning to do that once I get home to use a more populated instance

**Review by michelheusschen — COMMENTED** [review]
This function still assumes buckets by month and that'll probably cause issues when uploading assets

https://github.com/immich-app/immich/blob/d1135db8cf33901aee6449a6029480198099afa3/web/src/lib/stores/assets.store.ts#L350

**Comment by mehmooda** [comment]
should it be using localDateTime rather than fileCreatedAt? In some of my external libraries the fileCreatedAt time is the time the backup was taken and not the date the image was taken.

**Pull request closed without merging**
