### PR TITLE
feat(server): Add emergency stop for library watcher

### PR DESCRIPTION
**Pull request by etnoy**
Fixes #6833 and related issues.

In some cases, the library watcher can hang, preventing immich from starting. Then the user has no way of disabling the watcher again.

This adds an env variable, IMMICH_STOP_LIBRARY_WATCHER, that causes the server container to change the configuration and then exit. After that, the env variable can be removed and Immich can start again.

### CODE REVIEW

**Comment by martabal** [comment]
Wouldn't it be better if this was an admin CLI command?

**Comment by etnoy** [comment]
> Wouldn't it be better if this was an admin CLI command?

No, since the server startup hangs and it will be hard to use the API.

**Comment by jrasm91** [comment]
I would probably opt for moving library watching to microservices and use a postgres lock to prevent it from running on multiple instances. Then you could simple disable the microservices container, and the server/web is still responsiveness. These exact reasons are why we keep jobs off of the main api thread.

**Comment by etnoy** [comment]
Closing in favor of #7533

**Pull request closed without merging**
