### PR TITLE
fix(mobile): appBar on home screen animates out and doesnt alter asset grid position

### LINKED ISSUE #9015: Selecting on Android causes screen shift
### The bug

When selecting one item on Android, the title bar disappears causing the screen to shift. Depending on where my finger was on the item, the shift could bring the item below it up to where my finger is, selecting a whole row of items when I only wanted to select one.

### The OS that Immich Server is running on

Debian 11 LXC on Proxmox 8.1.11 (host running Debian 12)

### Version of Immich Server

v1.102.3

### Version of Immich Mobile App

v1.102.2 build 135

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Irrelevant, issue is with mobile app UI
```

### Your .env content

```Shell
Irrelevant, issue is with mobile app UI
```

### Reproduction steps

```bash
1. Tap and hold on bottom half of an image
2. Title disappears when entering selection mode, causing the screen to shift up
3. Finger is now over the image one row down when I haven't moved it
4. An extra row of images is selected when I only wanted to select 1
```

### Relevant log output

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ConnerWithAnE**
## Description
Fixes #9015 

~~This alters the appBar in the home page. I removed the ternary if statement which was checking if multi-selection is enabled. I see the value in removing the bar to gain space but it does make the UI feel weird. Perhaps it could be a setting that can be added later if users want.~~

This alters the `HomePage()` widget return. The `HomePage()` is now a `Stack` which allows the `MultiselectGrid()` to scroll behind it. The page no longer shifts when an asset is selected and the `ImmichAppBar()` animates out to the top as show in the example given by @waclaw66. This only affects the home page as there is a check in the  `ImmichAssetGridView()` which checks if the current tab is index 0 and the Route is one of the main tabs within the TabController. If both of those checks come up true padding is added to accommodate the AppBar adding some extra space. The `RefreshIndicator()` also has an offset added conditionally.

## How Has This Been Tested?

I ran flutter test and had no issues, I also ran it on an android device. I am unable to test IOS but I have no reason to believe anything would be different on either OS. I checked all views which use the asset grid and only saw the changes take effect on the main page.

### CODE REVIEW

**Comment by waclaw66** [comment]
Thanks for the PR. One remark, it would be nice if you could achieve to replace `ImmichAppBar` with a transparent bar to extend the surface height in the similar way as GPhotos does.

https://github.com/immich-app/immich/assets/15554561/04c4a905-79fc-4fd1-8bd4-8e98c1de01c0

**Comment by ConnerWithAnE** [comment]
> Thanks for the PR. One remark, it would be nice if you could achieve to replace `ImmichAppBar` with a transparent bar to extend the surface height in the similar way as GPhotos does.
> Screen_Recording_20240423_124122_Photos.mp4_out.mp4

Yea I could give that a go, might need to change the way that the homepage is displayed slightly. Could you possibly post a video example of how the top of the asset view is on google photos when selected? just so I can see how it is handled. I'd appreciate it thanks.

**Comment by waclaw66** [comment]
> Edit: I think I got it looking pretty good actually, let me know what you think.

It looks awesome now, exactly like I expected. Thanks!

**Comment by benmccann** [comment]
Could you fix the failing format job?

**Comment by ConnerWithAnE** [comment]
Yup, meant to get to it was just away today. First thing tomorrow I will.

**Review by alextran1502 — APPROVED** [review]
Perfect! Thank you very much! Let's fix the format and have it merged

FYI, next time you can allow maintainer to push to the PR and we can help take care of these things

**Comment by ConnerWithAnE** [comment]
> Perfect! Thank you very much! Let's fix the format and have it merged
> 
> 
> 
> FYI, next time you can allow maintainer to push to the PR and we can help take care of these things

Oh my bad I thought I did. Also just curious what checks should be ran before pushing mobile? There isn't a list of checks on the contribution wiki page I don't think?

**Comment by waclaw66** [comment]
@ConnerWithAnE could you please adapt this PR to album viewer as well? There is the same issue with jumping `AlbumViewerAppbar`. I've tried to do on my own, but haven't succeeded. Thanks!

**Comment by ConnerWithAnE** [comment]
> @ConnerWithAnE could you please adapt this PR to album viewer as well? There is the same issue with jumping asset grid. I've tried to do on my own, but haven't succeeded. Thanks!

https://github.com/immich-app/immich/pull/9741 This should fix it.

**Pull request merged**
