### PR TITLE
feat(mobile/web): add longer expirity for share link

### PR DESCRIPTION
**Pull request by akoscomp**
Sometimes peoples, like me, want to share an album to a longer period, but don't want to create an unlimited link.
For this option I add 1 year expirity for a share link.

### CODE REVIEW

**Comment by waclaw66** [comment]
When making such changes, you should also provide web version update. Additionally a "3 months" option would be appretiated. "365 days" could be renamed to "1 year".

**Comment by jrasm91** [comment]
I can add the web changes if you aren't familiar with web development.

**Comment by akoscomp** [comment]
> I can add the web changes if you aren't familiar with web development.

Yes please. I'm not a developer, only a devops....

**Review by jrasm91 — APPROVED** [review]
LGTM

**Pull request merged**
