### PR TITLE
deps(mobile): update dependency auto_route to v8

### PR DESCRIPTION
**Pull request by shenlong-tanwen**
#### Changes made:

- Upgrades `auto_route` and `auto_route_generator` to 8.x
- Removes the route config for `VideoViewerPage` since it actually is a component and never used as a separate route
- `context.popRoute` is replaced with `context.maybePop` as popRoute is deprecated from auto_route update

### CODE REVIEW

**Comment by alextran1502** [comment]
Hello, thank you for the dependency update. I just tested the PR and found a bug when navigating back from the asset viewer page. Here is additional logs

```dart
flutter: [SEVERE] [2024-03-31 23:20:06.441895] PlatformDispatcher - Catch all
flutter: Bad state: Future already completed
flutter: #1      Route.didComplete (package:flutter/src/widgets/navigator.dart:423)
flutter: #2      Route.didPop (package:flutter/src/widgets/navigator.dart:401)
flutter: #3      OverlayRoute.didPop (package:flutter/src/widgets/routes.dart:77)
flutter: #4      TransitionRoute.didPop (package:flutter/src/widgets/routes.dart:306)
flutter: #5      LocalHistoryRoute.didPop (package:flutter/src/widgets/routes.dart:757)
flutter: #6      AutoRouteNavigatorState.build.<anonymous closure> (package:auto_route/src/router/widgets/auto_route_navigator.dart:93)
flutter: #7      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:5284)
flutter: #8      ContextHelper.pop (package:immich_mobile/extensions/build_context_extensions.dart:35)
flutter: #9      GalleryViewerPage.build.<anonymous closure> (package:immich_mobile/modules/asset_viewer/views/gallery_viewer.dart:267)
flutter: #10     ModalRoute.onPopInvoked (package:flutter/src/widgets/routes.dart:1578)
flutter: #11     _RouteEntry.pop (package:flutter/src/widgets/navigator.dart:3116)
flutter: #12     _RouteEntry.markForPop (package:flutter/src/widgets/navigator.dart:3322)
flutter: #13     DefaultTransitionDelegate.resolve.handleExitingRoute (package:flutter/src/widgets/navigator.dart:1105)
flutter: #14     DefaultTransitionDelegate.resolve (package:flutter/src/widgets/navigator.dart:1144)
flutter: #15     TransitionDelegate._transition (package:flutter/src/widgets/navigator.dart:921)
flutter: #16     NavigatorState._updatePages (package:flutter/src/widgets/navigator.dart:4181)
flutter: #17     NavigatorState.didUpdateWidget (package:flutter/src/widgets/navigator.dart:3841)
flutter: #18     StatefulElement.update (package:flutter/src/widgets/framework.dart:5652)
flutter: #19     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
flutter: #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
flutter: #21     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
flutter: #22     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
flutter: #23     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
flutter: #24     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
flutter: #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
flutter: #26     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
flutter: #27     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
flutter: #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
flutter: #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
flutter: #30     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
flutter: #31     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
flutter: #32     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
flutter: #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
flutter: #34     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
flutter: #35     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
flutter: #36     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
flutter: #37     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
flutter: #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
flutter: #39     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
flutter: #40     StatelessElement.update (package:flutter/src/widgets/framework.dart:5556)
flutter: #41     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
flutter: #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
flutter: #43     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
flutter: #44     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
flutter: #45     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
flutter: #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
flutter: #47     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
flutter: #48     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
flutter: #49     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
flutter: #50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
flutter: #51     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
flutter: #52     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
flutter: #53     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2904)
flutter: #54     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:989)
flutter: #55     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448)
flutter: #56     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386)
flutter: #57     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311)
flutter: #58     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169)
flutter: #59     _invoke (dart:ui/hooks.dart:312)
flutter: #60     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399)
flutter: #61     _drawFrame (dart:ui/hooks.dart:283)
flutter: (elided one frame from dart:async)
```

**Comment by shenlong-tanwen** [comment]
> Hello, thank you for the dependency update. I just tested the PR and found a bug when navigating back from the asset viewer page, which caused the whole screen to turn gray. Here is additional logs
> 

Thank you. Fixed now

**Comment by zackpollard** [comment]
Hey, due to the refactors that have gone on and us not getting around to testing this when it was originally made, we're going to close this. If you do get around to fixing the merge conflicts then please re-open it again and we will prioritise getting it tested and merged :)

**Comment by shenlong-tanwen** [comment]
Superseded by #9456

**Pull request closed without merging**
