### PR TITLE
feat(web): chromecast support for shared content

### PR DESCRIPTION
**Pull request by omricarmel**
* supporting chromecast casting through chrome browser 
* only on publicly shared assets without password 
* directing the casting receiver to download asset endpoint 
* using default receiver 
somewhat resolves https://github.com/immich-app/immich/discussions/7030

image

### CODE REVIEW

**Comment by bo0tzz** [comment]
How does this relate to #13966?

**Comment by etnoy** [comment]
I might be biased, but I suggest we combine our efforts in #13966. That PR has come much further along, including private assets and video controls

**Comment by omricarmel** [comment]
@bo0tzz  this pr is simpler and less comprehensive.
 
On the other hand i do not hold a state and offload playback controls to chrome's cast popup interface.

as @etnoy mentioned i only allow casting publicly accessible assets ( so that chromecast will be able to reach them on its own ).

**Comment by omricarmel** [comment]
> I might be biased, but I suggest we combine our efforts in #13966. That PR has come much further along, including private assets and video controls

@etnoy Definitely. I didn't know about the other pr when working on this one. 

Even though this one would be easier to finish at its scope of operation and complexity.

**Comment by omricarmel** [comment]
Seeing the diff between the PRs, This style implementation has merit. offloading the session playback handling to chrome and not allocating privilege to the cast device.  The PRs are complementary, this one directs the cast device to an asset upon request (hence only public assets) and the other puts the web viewer into casting mode hooking all asset views.

Eventually they should be unified but this pr can be completed before the more comprehensive one.

**Comment by zackpollard** [comment]
Hey, we are going to push ahead with the existing PR, but we will pull some inspiration from this PR wrt the loading code. We have already had discussions around authentication and ability to totally disable the option to cast that this doesn't implement. Also, I understand you don't want to initiate a cast session and just want to cast a single picture, however this isn't the direction we want to pursue. Thanks for your PR and we hope to have chromecast support implemented soon!

**Pull request closed without merging**
