### PR TITLE
feat(server) add ocr support

### PR DESCRIPTION
**Pull request by jasongwq**
use [PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/README.md) to implement ocr and support retrieval on the app

### CODE REVIEW

**Comment by bo0tzz** [comment]
Related to #565 (Which was closed as not planned, but I'll leave that up to @alextran1502)

**Comment by alextran1502** [comment]
Thank you for the PR. Although we are not planning to integrate this feature soon into the project, but once you are done with it, it can be used as groundwork when we do.

**Comment by jasongwq** [comment]
i think my job is almost done
I don't know what else needs to be done to merge this PR?
I'm a newbie at this，Please give some pointers.Thank you very much.

**Comment by alextran1502** [comment]
Closing this and putting it into archived. Will be decided later on to integrate it into the project.

**Comment by zackpollard** [comment]
Hey, thanks for the PR. Upon discussion internally we have decided we are not looking to merge this right now. We don't think this is something suited to core functionality of Immich, however we are thinking about building a plugin style system later on that may allow features like this to be added based on the users preferences.

**Comment by fivestones** [comment]
It seems a little bit strange to have machine learning in python with CLIP as a core functionality but to not make use of OCR in search as part of that same core functionality.

I think anyone who is searching their photos would appreciate search results showing photos that have the search text written somewhere in the image, as well as those that have the thing searched for pictured in the photo. If I'm searching for "medicine" I'd want to have the search results both show me bottles of medicine and photos of paperwork that has the word "medicine" on it.

Finding text in photos already works in iOS photos search. I'd love to have this feature in immich, and a plugin system would be fine.

**Comment by AngelaDMerkel** [comment]
I agree with @fivestones perspective on this. If the main goal were to purely backup to a server from the phone, this would be accomplished easily enough using rclone/sync or one of the very many sync to server style apps which are out there. I would also like to see a replacement or near enough alternative to GP, and one of the main draws of immich is the excellent UI as a browser to images. Having OCR seems like it would be an excellent tool to facilitate browsing what could easily be decades of images.

**Comment by jasongwq** [comment]
I think backing up photos is not the ultimate goal of users. The ultimate goal is to back up photos and find them when needed in the future. 
But it is not easy to find a photo in memory by recalling the time and other information, because time can become vague in memory. But I think it is often much easier to remember a text fragment in the photo.

**Comment by fivestones** [comment]
Any more thoughts about this? Could it be integrated into Immich?

If it makes a difference, in google photos the search results bring up images with the searched text in them.

**Comment by msrn** [comment]
> Hey, thanks for the PR. Upon discussion internally we have decided we are not looking to merge this right now. We don't think this is something suited to core functionality of Immich, however we are thinking about building a plugin style system later on that may allow features like this to be added based on the users preferences.

What is the core functionality of Immich nowdays? It is currently more than photo backup solution, as you can organize images and use AI/ML to classify objects and people and to ease up searching of  images. I'd said OCR is one of the missing pieces of the current core functions.

**Comment by awcator** [comment]
> > Hey, thanks for the PR. Upon discussion internally we have decided we are not looking to merge this right now. We don't think this is something suited to core functionality of Immich, however we are thinking about building a plugin style system later on that may allow features like this to be added based on the users preferences.
> 
> What is the core functionality of Immich nowdays? It is currently more than photo backup solution, as you can organize images and use AI/ML to classify objects and people and to ease up searching of images. I'd said OCR is one of the missing pieces of the current core functions.

Agree, I'd love to see this as a core feature/plugin. I really want to have this feature. I'd like to search particular meme from a bunch of memes/screenshots.

**Comment by Crocatowa** [comment]
Any change on position with regards to OCR being a core feature?
It really is the only thing keeping me from migrating off of **_"App-Which-Must-Not-Be-Named"_**

The only alternative is to build a whole separate UI Fork for the API and have it store the OCR results separately, which seems kinda silly when the core app already has: 
- Face Recog
- Basic Object Recog
- Similar/Duplicate detection
- CUDA Integration (future AI image generation?) 
- Tagging 
  - Of special note here: The API documentation doesn't show any way to search by tags
  - OCR Results/Words Detected _could_ be stored as tags as a dummy way of doing this

Add in the fact that there's already this PaddleOCR-based PR, and Tesseract has been open source for early 20 years... 
Either making it easier to have this as a plug-in, or biting the bullet and adding the feature outright would be awesome

**Comment by d0tcc** [comment]
Immich is truly amazing and I love it! The only thing that keeps me at "App-Which-Must-Not-Be-Named" is OCR. It's an essential feature for searching my photos. Please reconsider if OCR is really out of scope, because for me this is the only thing that is actually missing ...
I also wanted to suggest [EasyOCR](https://github.com/JaidedAI/EasyOCR)!

Thanks for all the work you have put into this software. Once I have fully switched I will purchase a server license :smiley:

**Comment by mertalev** [comment]
To be clear, OCR isn't out of scope for Immich and we do plan to implement it. It just isn't part of our pre-stable roadmap, so other things take priority for now. We'll work on OCR after the stable release.

**Comment by banjuer** [comment]
It is obvious that it will be a major feature point of immich and also a highly distinctive feature

**Pull request closed without merging**
