### PR TITLE
feat(web,server): user memory settings

### LINKED ISSUE #3627: [Feature] Ability to disable memories feature
### Discussed in https://github.com/immich-app/immich/discussions/3187

<div type='discussions-op-text'>

<sup>Originally posted by **samip5** July  9, 2023</sup>
### The feature

I would like to be able to disable the memories feature, or at least disable showing things in mobile/web.

### Platform

- [X] Server
- [X] Web
- [X] Mobile</div>

### PR DESCRIPTION
**Pull request by jrasm91**
Fixes #3627

In this PR:
- Add a new user property `memoriesEnabled` to the user entity
- Disable `MemoryLane` in the web when this is set to false
- Add new `Memories` settings under User Settings

Tested Scenarios:
- Set to false, verify no memory lane
- Set to true, verify memory lane
- e2e test to update user and set memories to false
- e2e test to create user with memories set to false
- unit tests all pass

TODO:
- [x] Disable memory lane in the mobile app when turned off

image
image

### CODE REVIEW

**Comment by alextran1502** [comment]
Should we make this client-side?

**Comment by alextran1502** [comment]
> I thought about that, but I think they want to turn it off everywhere not over and over again on each client and new device.

fair point

**Comment by samip5** [comment]
> Should we make this client-side?

That would make it very poor user experience IMO.

**Comment by martabal** [comment]
What about both ? If you want memory on every devices except one

**Comment by jrasm91** [comment]
> What about both ? If you want memory on every devices except one

We have seen requests for specifically disabling this across the board. I have not seen any requests for disabling it on all devices except one. In general, I think it is OK not to support every use case out the gate, especially if supporting them means more complexity in the code/implementation. I'm voting for simplicity + maintainability at the expense of edge cases that may or may not be valid/wanted to the users today.

**Comment by alextran1502** [comment]
I tried updating the property, but it doesn't get updated in the database.  

https://github.com/immich-app/immich/assets/27055614/bbde79b8-38d1-4a7b-ad58-5734e7969edf

**Comment by jrasm91** [comment]
Oh thanks lol. Don't know how I missed that.

**Review by alextran1502 — APPROVED** [review]

**Pull request merged**
