### PR TITLE
docs: add example reverse proxy config for HA Proxy

### PR DESCRIPTION
**Pull request by linuxtim**
Thanks for helping to maintain Immich and also for looking at this PR...

[haproxy](https://en.wikipedia.org/wiki/HAProxy) is a commonly used and long-standing high performance and full featured proxy and load balancer etc. etc.  This PR adds instructions for configuring HA Proxy to provide access to Immich.

Since the availability and use of basic auth (see https://github.com/immich-app/immich/pull/6840 etc.) is not well documented, I also show the use of this in the sample config (along with instructions for how to omit that feature).

Thanks!

Tim.

### CODE REVIEW

**Comment by bo0tzz** [comment]
Thanks for the PR! I think we want to keep the configurations on this page to the bare minimum without extra bits like basic auth or HTTPS, otherwise the page is going to overflow with those in no time. If you want to document a more elaborate configuration, feel free to write that up elsewhere and add a link to the community guides (https://immich.app/docs/community-guides).

**Comment by mmomjian** [comment]
> Thanks for the PR! I think we want to keep the configurations on this page to the bare minimum without extra bits like basic auth or HTTPS, otherwise the page is going to overflow with those in no time. If you want to document a more elaborate configuration, feel free to write that up elsewhere and add a link to the community guides (https://immich.app/docs/community-guides).

Agreed, especially since Basic auth doesn't work with our video player library

**Comment by alextran1502** [comment]
Hello, any update on this PR?

**Comment by zackpollard** [comment]
Hey, going to close this as there has been no update. However if you want to update it and re-open a new PR or comment on this one to have it re-opened, please do so!

**Comment by DavidFederX** [comment]
Hello, 
I used to have immich behind haproxy without any problem. 
Yesterday I installed Authentik for oAuth, got it working fine except with (ios) mobile app. 
if I put the sever ip:port (lan then of course), it works, but when I put the fqdn, it just says "server unreachable". (no matter if it's lan or wan).
I followed this great guide for the haproxy + authentik setup: https://github.com/LojDev/pfsense-haproxy-authentik

**Pull request closed without merging**
