### PR TITLE
feat(web): allow closing asset viewer by clicking on background

### PR DESCRIPTION
**Pull request by zax-xyz**
## Description
Currently, the only ways to close the asset viewer in the web application is by clicking the arrow in the top left or by using the keyboard. This adds another way, that may be convenient when using the web application using primarily a mouse, by clicking outside the region of the asset, but not over any of the overlays (navigation, etc).

This is done is by creating another element covering the screen solely to capture clicks, and then raising the assets above this. Styles for centering the assets are moved upwards, so that the assets can take only their needed space so as to not block the cursor capturing.

We also make sure that only the actual assets are raised high enough in the stacking context and not loading spinners so that we can still click through loading spinners to close the viewer (to me this makes sense, loading spinners seem like they should be "transparent" and not block this, not sure if others agree)

## How Has This Been Tested?

This has just been manually tested, making sure that the functionality works, and that all of the different types of viewers (Photo, Video, Panorama) still work correctly.

## Screenshots (if appropriate):

https://github.com/immich-app/immich/assets/25019123/3f35221d-9faf-4a38-868d-945902412995

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation if applicable

### CODE REVIEW

**Comment by alextran1502** [comment]
Hello, I don't think this is a common behavior to close the viewer. I will reject this PR

**Comment by zaxutic** [comment]
> Hello, I don't think this is a common behavior to close the viewer. I will reject this PR

It's definitely not found everywhere which I understand, but it is in some other similar applications, including [Photoprism](https://www.photoprism.app) and [Nextcloud Photos](https://github.com/nextcloud/photos)

**Comment by ddshd** [comment]
> > Hello, I don't think this is a common behavior to close the viewer. I will reject this PR
> 
> It's definitely not found everywhere which I understand, but it is in some other similar applications, including [Photoprism](https://www.photoprism.app) and [Nextcloud Photos](https://github.com/nextcloud/photos). Personally I find this useful and I don't think it's intrusive

I’ve definitely seen this behavior with popups type behavior (mailing list sign ups, etc..) and I do know that some sites do use this behavior for loading media viewers so it’s not uncommon - maybe it’s a regional difference?

Though I’m not smart enough to comment on the method of implementation of this.

**Comment by jrasm91** [comment]
I think this comes down to the fact that we don't want to treat the asset viewer like a modal, but a full screen page/component.

The "click in the background to close something" functionality is specifically for _modals_. We actually use this same pattern for our modals, most of which can be closed by clicking in the background. Our modals look quite a bit different from the asset viewer though. They aren't full width/height, and this allows room for a (semi) transparent background overlay with the described functionality.

It would be more acceptable if the viewer didn't always take up the full screen width/height and if the background was semi-transparent, but I don't think that is the look we're going for.

**Pull request closed without merging**
