### PR TITLE
fix(web): delete user

### LINKED ISSUE #6513: Deleting a user
### The bug

when deleting a user after pressing delete again to confirm, the popup stays open and you can only cancel
if you cancel after confirming the delete, the user is still in a delete stage

### The OS that Immich Server is running on

Ubuntu 20.04

### Version of Immich Server

v1.93.1

### Version of Immich Mobile App

1.93.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
-
```

### Your .env content

```Shell
-
```

### Reproduction steps

```bash
1. create a user (with oauth in my case)
2. delete the user
3. click delete again to confirm
...
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by martabal**
fixes #6513

### CODE REVIEW

**Review by danieldietzler — APPROVED** [review]
Lol what a stupid typo :D
Thanks!

**Comment by martabal** [comment]
It didn't take too long to figure out what the problem was :laughing: 

I think this isn't the first time we've run into this kind of issue with the dispatcher, I don't know if svelte has any built in features to limit this.

**Review by jrasm91 — COMMENTED** [review]
Why is this not throwing an error? We're using typed dispatchers so this should be validated, no?

**Comment by martabal** [comment]
> Why is this not throwing an error? We're using typed dispatchers so this should be validated, no?

No, it does prevent that error

**Comment by jrasm91** [comment]
Ah, maybe it would only prevent it if you used a custom event with a type that mismatched.

**Pull request merged**
