### PR TITLE
feat(web): add delete button to asset viewer

### PR DESCRIPTION
**Pull request by anbraten**
# todo
- [x] fix typo in file name
- [x] add button to delete asset
- [x] support for keyboard delete

image

### CODE REVIEW

**Comment by anbraten** [comment]
Going to the next image after deleting seems a bit buggy 🤔

**Comment by alextran1502** [comment]
> Going to the next image after deleting seems a bit buggy 🤔 

You probably need to remove the image from the global store of the asset grid bucket as well since it is in charge of building out the list to navigate forward and backward

**Comment by anbraten** [comment]
Problem was that the currentIndex was `-1` as I called go to next after removing the current asset. Just changed it so it first goes to the next asset and then removes the asset from the grid. Should be fine now.

**Comment by alextran1502** [comment]
Thank you for the PR. I appreciate the contribution.

**Pull request merged**
