### PR TITLE
fix(web): reorder jobs in concurrency view to match job overview

### PR DESCRIPTION
**Pull request by traktuner**
On the admin page, the order of the job overview is different from the "manage concurrency" view.
This reorders the concurrency view to have a better overview, when users jump between the two sections to optimize their job concurrency settings.

### CODE REVIEW

**Comment by jrasm91** [comment]
This file is auto generated by the immich server when running in dev mode. You will need to fix it at the source.

**Comment by traktuner** [comment]
> This file is auto generated by the immich server when running in dev mode. You will need to fix it at the source.

sorry about that. it's not reordered in the api entities. hope that's correct now!

**Comment by jrasm91** [comment]
Just change it here:

https://github.com/immich-app/immich/blob/main/web/src/lib/components/admin-page/settings/job-settings/job-settings.svelte#L20

**Comment by jrasm91** [comment]
Closing in favor of https://github.com/immich-app/immich/pull/5386

**Pull request closed without merging**
