### PR TITLE
build(docker): Use ghcr.io as build cache instead of gha

### PR DESCRIPTION
**Pull request by bo0tzz**
This pr replaces the gha-internal layer caching with an image pushed to ghcr.io. This works more reliably than the gha cache (which I'm pretty sure is bugged), with the added benefit that there is no 10GB cache limit. One caveat is that pull requests cannot -write- cache entries, because the push fails with a permission error. This is somewhat odd, because normal images can be pushed no problem, but I can't figure it out and it doesn't seem a big issue anyways :P 

I'm not 100% confident about this caching approach (it feels a little gross), so I'd like to hear others' opinions on it before this is merged.

### CODE REVIEW

**Comment by alextran1502** [comment]
So cache can only be written when the build is run on the main?

**Comment by bo0tzz** [comment]
Yes, indeed.

**Comment by alextran1502** [comment]
I am OK with merging and trying it out. I guess it is quite hard to quantify without actual usage data

**Review by jrasm91 — APPROVED** [review]
:rocket:

**Pull request merged**
