### PR TITLE
chore: add CLI tool to the server image

### PR DESCRIPTION
**Pull request by ddshd**
Allows easy access to the CLI tool from within the server container to import existing galleries

### CODE REVIEW

**Comment by alextran1502** [comment]
The goal of the CLI is to be headless so that it can be functioned from any client, any computer. What do you think about that goal?

**Comment by ddshd** [comment]
> The goal of the CLI is to be headless so that it can be functioned from any client, any computer. What do you think about that goal?

The goal is awesome, the upload/import CLI should be accessible from everywhere, and imo I don't think this should affect that goal (maybe I'm missing something so feel free to let me know)

I think this would just be a good quality-of-life improvement for importing libraries so one doesn't have to mount a volume to the exact same path as their host system for the import command to work, they can just exec the command through the container.

The CLI tool also interferes with with the default `immich` command on the server image (as they both use the same command) so if a user installs the npm package manually from within the container without foresight they may face some issues using both commands at the same time. This just create a quick way to call the upload/import cli while also keeping the default command as-is.

**Comment by davidrudlstorfer** [comment]
@ddshd that would be a perfect addition - thanks for the PR 🙏🏻 I am currently setting up Immich and I am planning on utilizing the novel read-only feature. Unfortunately I ran into the exact issue you described above and wasn't able to use the CLI tool in combination with docker. If the CLI tool is included it would ease the installation.

Hope this gets merged

**Comment by uhthomas** [comment]
_really_ this tool should be moved into this repo and added directly instead.

**Comment by martabal** [comment]
I think it's a great idea to install the CLI directly in the server, so users can import their assets with a command like `docker exec immich_server immich-cli --key apikey --server http://my-server-ip:2283/api ${UPLOAD_LOCATION}/import_folder --recursive --import`

**Review by jrasm91 — COMMENTED** [review]
The all in one image does something similar. We have two CLIs the admin one and this one. What do you think about leaving this one as `immich` and renaming the admin one to `immich-admin`?

**Comment by martabal** [comment]
@jrasm91 @hydazz made a bash script to determine if the immich command is a command for the admin CLI or the upload CLI https://github.com/imagegenius/docker-immich/blob/main/root/usr/local/bin/immich

**Comment by ddshd** [comment]
> The all in one image does something similar. We have two CLIs the admin one and this one. What do you think about leaving this one as `immich` and renaming the admin one to `immich-admin`?

I could do that but that will probably need a review from the project owner.. It would also break anything that's expecting to use the default `immich` in some fashion..

**Comment by ddshd** [comment]
> > The all in one image does something similar. We have two CLIs the admin one and this one. What do you think about leaving this one as `immich` and renaming the admin one to `immich-admin`?
> 
> @jrasm91 I like this to keep the commands consistent for CLI tool.


> The all in one image does something similar. We have two CLIs the admin one and this one. What do you think about leaving this one as `immich` and renaming the admin one to `immich-admin`?

I've updated the changes to change the upload CLI to `immich` and the normal command to `immich-admin`

**Review by jrasm91 — COMMENTED** [review]
Nice! Would you mind updating the immich-admin docs to use the new name?

**Review by alextran1502 — APPROVED** [review]

**Pull request merged**
