### PR TITLE
refactor(mobile): tidy-up dependencies, remove unused, replace rarely used ones

### PR DESCRIPTION
**Pull request by fyfrey**
- removed dependencies: dio, exif, flutter_swipe_detector, percent_indicator, equatable, flutter_spinkit
- removed some dead code
- marginally reduces app size

Backup screen storage and backup progress indicator no longer have rounded borders:

old:
old

new:
new

Progress text color now matches all the other text color on that page

I've further identified that image_picker could be replaced: only used to select user profile image from system gallery -> we can simply select an image from within immich

### CODE REVIEW

**Comment by alextran1502** [comment]
```image_picker: only used to select user profile image from system gallery -> we can simply select an image from within immich?```

Yep, it makes sense to it that way. However, it will take more work to show the page with all the images I assume

```equatable: only used in error_upload_asset.model.dart -> write hashCode and equals manually as for every other class?```

Agree

```flutter_spinkit: only used in three places, we could instead use a builtin CircularProgressIndicator (that we use more often anyway) but less fancy than SpinKit```

Agree


Besides the three points mentioned, I like the rounded corner of the progress bar as everything in Material Design 3 is rounded 😛

**Comment by zoodyy** [comment]
> ```
> image_picker: only used to select user profile image from system gallery -> we can simply select an image from within immich?
> ```
> 
> Yep, it makes sense to it that way. However, it will take more work to show the page with all the images I assume

True, I won't tackle that in this PR.

> Besides the three points mentioned, I like the rounded corner of the progress bar as everything in Material Design 3 is rounded stuck_out_tongue

Bad news: Materiel Design 3 has actually [specified](https://m3.material.io/components/progress-indicators/specs) non-rounded corners for the progress bar. If you want I can still figure out how to make rounded corners (the builtin flutter component has no way to set it)

**Comment by alextran1502** [comment]
> > ```
> 
> > image_picker: only used to select user profile image from system gallery -> we can simply select an image from within immich?
> 
> > ```
> 
> > 
> 
> > Yep, it makes sense to it that way. However, it will take more work to show the page with all the images I assume
> 
> 
> 
> True, I won't tackle that in this PR.
> 
> 
> 
> > Besides the three points mentioned, I like the rounded corner of the progress bar as everything in Material Design 3 is rounded stuck_out_tongue
> 
> 
> 
> Bad news: Materiel Design 3 has actually [specified](https://m3.material.io/components/progress-indicators/specs) non-rounded corners for the progress bar. If you want I can still figure out how to make rounded corners (the builtin flutter component has no way to set it)

Opps, I didn't read the specs about the progress bar. Good to know! We can keep it straight corner though

**Comment by zoodyy** [comment]
> Opps, I didn't read the specs about the progress bar. Good to know! We can keep it straight corner though

neither did I before. From my side this PR is no ready to be merged. But it would better if you could test it an iOS (emulator): swiping to show on videos and close the video, and check if the loading animation (e.g. when opening an album) is ok.

**Comment by alextran1502** [comment]
Everything looks good. Merging

**Pull request merged**
