### PR TITLE
feat(web): timeline bucket for albums (4)

### LINKED ISSUE #3606: [Feature] Add justified layout to album view
### Discussed in https://github.com/immich-app/immich/discussions/3602

<div type='discussions-op-text'>

<sup>Originally posted by **waclaw66** August  8, 2023</sup>
### The feature

Currently album view uses strict grid - matrix. It's not recognizable which asset is landscape or portrait.
It would be nicer to use the already implemented [justified layout](https://github.com/immich-app/immich/pull/2666) for albums as well.  Android version uses that non-matrix view already, but in the simplified way (not nice).

### Platform

- [ ] Server
- [X] Web
- [ ] Mobile</div>

### PR DESCRIPTION
**Pull request by jrasm91**
Fixes #3606, #3607

Related to:
- #3550 
- #2370
- #2337

In this PR:
- Use time buckets on the album (not shared links though)
- Add link icon under album title
- Add owner icon to list of shared user icons
- Add owner item to list of users (share info modal)
- Add option to get album by id without return assets
- Include new property (`hasSharedLink`) to know if there is at least one shared link on the album
- Add typing to several dispatcher events
- Simplify `CreateSharedLinkModal` interface
- Add another `UserAvatar` size in between the previous `md` and `lg`.

Tested Scenarios:
- Create a new album from select in the timeline (no share button)
- Create a new album from asset view in the timeline
- Create a new shared album from sharing page (shows share button)
- Update album cover (thumbnail)
- Add user to album
- Remove user from album
- Remove self from album (leave album)
- Remove asset
- Remove assets via shift+select
- Remove assets via group select
- Add assets via shift-select
- Add assets via group select
- Add/remove assets and album details (date, count) are correctly updated
- Create album shared link
- View link icon in share row (if owner)
- No view link in share row (for non-owner)
- Asset view next/previous work as expected
- Delete from album shows up if all selected assets are owned by me (non owner)
- Delete from album is not visible if selection includes a non-owned asset
- Add asset from computer (owned)
- Add asset from computer (non owned) immediately adds a broken thumbnail, which requires a refresh

Notes:
- Creating a _new_ album from a selection of assets in the album view doesn't reload the `AssetGrid` / page correctly.

### CODE REVIEW

**Comment by alextran1502** [comment]
One bug I found while testing is that from the empty album, clicking on the Select Photo button would not show the asset selection page.

**Comment by alextran1502** [comment]
Can you also put back the select photos button in the empty album instead of the empty placeholder image? When I implement the smart album, another button will be on top of it

**Comment by jrasm91** [comment]
Yeah, I can put that back.

**Review by brighteyed — COMMENTED** [review]
I encountered a minor bug. The `Select Album Cover` page doesn't preselect the current cover

**Comment by jrasm91** [comment]
> I encountered a minor bug. The `Select Album Cover` page doesn't preselect the current cover

Yeah, that sounds like a regression.

**Review by alextran1502 — APPROVED** [review]

**Comment by magicedy** [comment]
Snipaste_2023-08-16_08-36-33
@jrasm91 Is this feature only effective on the web? I tried it on mobile and it didn't work. Can it also be made effective on mobile?

**Comment by jrasm91** [comment]
The PR only addresses the web. I'm not a mobile dev so I can't comment on implementing it there, although it should be possible.

**Comment by magicedy** [comment]
@alextran1502 Is there any plan to implement this feature on mobile?  #3607

**Comment by alextran1502** [comment]
Album on the mobile app is already lazy loaded and with the draggable scrollbar

**Comment by magicedy** [comment]
- Use time buckets on the album
Sorry for any confusion earlier. Like the above modification, I was wondering if the display on mobile can be consistent with the web version? Thanks in advance! @alextran1502

**Comment by alextran1502** [comment]
@magicedy the mobile app use different mechanism to render the asset i.e builder pattern so it doesn't need time-bucket mechanism like the web

**Comment by magicedy** [comment]
@alextran1502 Apologies if I wasn't clear earlier. What I meant to ask is, on mobile, can the assets in 'albums' and 'shared albums' be grouped by month+day, just like they are in the main timeline on mobile and also like the current web version? Thanks for considering!

**Comment by alextran1502** [comment]
@magicedy Ah I see, no worry, right now the album on the mobile app doesn't support grouping like that

**Comment by rcdailey** [comment]
I'm currently running v1.79.1 and photos in the timeline view take 10s of seconds to load. Definitely a client side performance issue. Once they do load, scrolling is extremely laggy. I'm using Microsoft Edge. My external photo library has 65,000 photos in it.

Was this PR intended to address my scenario?

**Comment by rcdailey** [comment]
Correct, I believe we're talking about the web client here.

Local IP (I haven't put it through my reverse proxy yet because I'm still experimenting with it).

I tested on Edge on both a Macbook Pro and Windows 10 machines. I also tested on Firefox on Windows 10. Behavior was consistent.

**Comment by jrasm91** [comment]
@rcdailey - I don't think your issue is related to this PR, perhaps you can open a separate bug or join the discord server and create a support post with some more details.

**Comment by rcdailey** [comment]
I appreciate it. I wanted to check here first before I open another issue.

**Pull request merged**
