### PR TITLE
feat(server): add env for reverse geocoding path

### PR DESCRIPTION
**Pull request by martabal**
## Changes made in this PR

This PR adds an environment variable (`IMMICH_REVERSE_GEOCODING_ROOT`) to set the path of the reverse geocoding dump directory.

### CODE REVIEW

**Review by danieldietzler — COMMENTED** [review]
What's the purpose of this? I mean it shouldn't matter at all how we store that stuff internally. You can always just map it to whatever volume you like with docker

**Review by zackpollard — APPROVED** [review]

**Comment by zackpollard** [comment]
LGTM, only thing might be to add documentation of this path, but as it's for very specific cases, also happy for it to be an undocumented variable

**Review by danieldietzler — APPROVED** [review]

**Comment by danieldietzler** [comment]
Didn't even know there is an AUR package lol

**Comment by martabal** [comment]
> LGTM, only thing might be to add documentation of this path, but as it's for very specific cases, also happy for it to be an undocumented variable

I added it https://feat-reverse-geocoding-env.immich.pages.dev/docs/install/environment-variables. But, yes, it's probably good too if it's undocumented

**Comment by martabal** [comment]
> Didn't even know there is an AUR package lol

It's for sure not a great experience to maintain this lol https://aur.archlinux.org/cgit/aur.git/plain/metadata.repository.ts.patch?h=immich

**Comment by zackpollard** [comment]
> > LGTM, only thing might be to add documentation of this path, but as it's for very specific cases, also happy for it to be an undocumented variable
> 
> I added it https://feat-reverse-geocoding-env.immich.pages.dev/docs/install/environment-variables. But, yes, it's probably good too if it's undocumented

Lol somehow I missed that file entirely...

**Review by zackpollard — APPROVED** [review]

**Comment by jrasm91** [comment]
Maybe we can migrate to a single env for a single folder and assume everything is a relative path from there. It is kind of annoying adding a new env anytime we read any file from disk.

**Pull request merged**
