### PR TITLE
Added Powershell script for scheduled Windows DB backups

### PR DESCRIPTION
**Pull request by JustSuperHuman**

### CODE REVIEW

**Comment by mmomjian** [comment]
This should probably be located under Guides, mayb at [this link](https://immich.app/docs/guides/template-backup-script/)

**Comment by JustSuperHuman** [comment]
@mmomjian I didn't see that actually. I wonder if the two pages should actually be consolidated? 
They seem directly related, just in two different places.

- https://immich.app/docs/guides/template-backup-script
- https://immich.app/docs/administration/backup-and-restore

If there's a consensus, I'd be happy to do it, would just need to know which place to put it.

**Comment by alextran1502** [comment]
I agree with @mmomjian that we should have this in the Guide section instead.

**Comment by mmomjian** [comment]
> @mmomjian I didn't see that actually. I wonder if the two pages should actually be consolidated? They seem directly related, just in two different places.
> 
> * https://immich.app/docs/guides/template-backup-script
> * https://immich.app/docs/administration/backup-and-restore
> 
> If there's a consensus, I'd be happy to do it, would just need to know which place to put it.

I don't believe these two pages need to be moved. I believe the "spirit" of the documentation is for Immich-specific commands to be under Admin, and examples of how to use these commands under Guides. As this script is an example of how to use the Immich commands in a rotating backup, it would go under Guides.

**Comment by JustSuperHuman** [comment]
Ah! Thank you for the explanation :) I’ll close this and move it to guides.

**Pull request closed without merging**
