### PR TITLE
feat(server, web): add checkbox to create user screen for shouldChang…

### PR DESCRIPTION
**Pull request by samholton**
…ePassword

Addresses https://github.com/immich-app/immich/discussions/7592

Also saw an old discussion in discord around this.

Defaults to `true` to keep behavior consistent with current flow.

**before**
before

**after**
after

### CODE REVIEW

**Comment by samholton** [comment]
Could someone rerun the failed check? It appears it was a connection issue with npmjs

**Comment by alextran1502** [comment]
It should always be required for the sake of the privacy of other users that use your instance.

**Comment by alextran1502** [comment]
Have you tested create new user with this flag disable and the user doesn't have to reenter the password on first login?

**Comment by samholton** [comment]
Yeah, I agree it should be enabled as well. But an admin could always create a user then login to the instance once and then share the account. I left in enabled by default.

Yes  I tested with it both enabled and disabled. I checked the `users` table as well as logging in. The login bypassed the password change with it disabled.

**Review by alextran1502 — APPROVED** [review]

**Pull request merged**
