### PR TITLE
feat[i18n]: add fink messages editor

### PR DESCRIPTION
**Pull request by NilsJacobsen**
> let me know what needs to be changed in order to merge this

# Description: DX upgrade with little i18n tool.
- I added [fink editor](https://inlang.com/m/tdozzpar/app-inlang-editor) to update product copy/translation with a no code UI. Here u see an example from my fork: https://inlang.com/editor/github.com/NilsJacobsen/immich
- Badge for docs: https://inlang.com/m/zu942ln6/app-inlang-badge

# What I added (opt-in)
- A config file -> `settings.json`

## Screenshots:
image

### CODE REVIEW

**Comment by bo0tzz** [comment]
We were just working on moving to https://weblate.org/ for i18n. How does this compare?

**Comment by NilsJacobsen** [comment]
> I'm working on inlang, so based on my experience with this solution and others:

The great thing about Fink is that it is compatible with [inlang's ecosystem apps](https://inlang.com/c/apps). You only need one configuration, that I added in this PR. After that, you can use any app that is compatible with this [ecosystem](https://inlang.com/g/7777asdy). Fink is just one app. If you need a [cli](https://inlang.com/m/2qj2w8pu) to automate the translation process or even machine translate you can also use that ootb. Or for better DX in your code editor use the [ide-extension](https://inlang.com/m/r7kp499g).

I feel like weblate is and will be a TMS, storing your translations on a additional DB and syncing it into the repo. Inlang just stores it in your repo with lots of benefits:
- version control
- approval system
- PR workflow
...

I just feel you get more for less code and maintenance. 

How was your experience with weblate so far?

**Comment by jrasm91** [comment]
One of the specific features we're looking for is plural support, which fink seems to be missing.

**Comment by NilsJacobsen** [comment]
You are right. Pluralization is gonna be added in the next months. I'd be happy to let you know.

**Pull request closed without merging**
