### PR TITLE
fix(server): normalize external path

### PR DESCRIPTION
**Pull request by etnoy**
This normalizes the user's external path. This should fix many bugs we've found with external paths and no assets being found.

### CODE REVIEW

**Comment by jrasm91** [comment]
Can you give an example of a situation that this would fix?

**Comment by etnoy** [comment]
> Can you give an example of a situation that this would fix?

After some consideration, this might fix fewer bugs than anticipated. However, whenever you have /../ in the external path, this makes things easier. Note that this will always be the case when we do e2e.

**Comment by jrasm91** [comment]
In that situation can we normalize the path before it is saved instead?

**Comment by etnoy** [comment]
> In that situation can we normalize the path before it is saved instead?

done!

**Review by alextran1502 — APPROVED** [review]

**Pull request merged**
