### PR TITLE
feat(web): show number of assets in memory progress bar

### LINKED ISSUE #2810: [BUG] memory progress should show number of assets as multiple bars
### The bug

It should behave like Google Photos:

image

Currently it looks like this:

image

### The OS that Immich Server is running on

N/A

### Version of Immich Server

v0.61.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by uhthomas**
Fixes: #2810

### CODE REVIEW

**Comment by uhthomas** [comment]
Looks like this:

image

**Comment by uhthomas** [comment]
There is one issue I need to fix though, the progress bar freaks out when the asset changes.

[Screencast from 2023-06-16 18-17-11.webm](https://github.com/immich-app/immich/assets/9749173/59f28303-124a-461a-90e7-62634b438599)

This seems like a race condition between the progress bar being reset to 0 and Svelte switching which progress bar is monitoring the tween.

**Comment by uhthomas** [comment]
Resolved!

[Screencast from 2023-06-16 18-42-05.webm](https://github.com/immich-app/immich/assets/9749173/55a4aaaf-3479-42c5-b0ab-573e0db6d717)

**Comment by alextran1502** [comment]
Nice job! Can you resolve build error?

image

Also, should we limit the number of memory return?

**Pull request merged**
