### PR TITLE
immich kubernetes example

### PR DESCRIPTION
**Pull request by gregwalters**
Not the best of examples but it works for me and is better than no example! Maybe someone that writes cleaner kubernetes stuff or uses kustomize can contribute later.

### CODE REVIEW

**Comment by bo0tzz** [comment]
There's a helm chart at https://github.com/immich-app/immich-charts

**Comment by gregwalters** [comment]
LOL. I guess my time/PR would be better spent updating the docs to include a mention of the helm chart!

**Comment by alextran1502** [comment]
> LOL. I guess my time/PR would be better spent updating the docs to include a mention of the helm chart!

Yes please, it would be greatly appreciated.

**Comment by bo0tzz** [comment]
I've created some docs in #1418.

**Pull request closed without merging**
