### PR TITLE
doc: documentation of the Immich Flutter Architectural Pattern

### PR DESCRIPTION
**Pull request by Skyquek**
## Description

Added the Immich Flutter architectural documentation on Readme.md. The current readme.md is empty, figured out that we can use the Readme.md to document the architectural pattern on Flutter.

### CODE REVIEW

**Comment by alextran1502** [comment]
is this from ChatGPT or Bard?

**Comment by Skyquek** [comment]
Ya, I use it clean up my grammar.

**Comment by alextran1502** [comment]
> Ya, this is from ChatGPT. I use it clean up my grammar. But the explaination is correct right? The flutter do use provider pattern organization with the separation of the Ui, view, provider, services, model

Some part has more sugar and not necessarily correct but overall very good

**Review by alextran1502 — APPROVED** [review]

**Comment by benjamonnguyen** [comment]
Thanks for the documentation @Skyquek!

I'm curious about the prompt you provided to generate this. Did you pass in parts of the codebase?

**Pull request merged**
