### PR TITLE
feat(web,mobile) Allow videos to be looped in the detail viewer

### PR DESCRIPTION
**Pull request by kleinMaggus**
This PR adds a setting to the web and mobile version to make videos automatically loop in the detail viewer. The user can decide if he wants this behaviour or not (default currently enabled).

Web setting:

Mobile setting:

It is my first contribution and I am complete new to flutter and have only little svelte experience, so I am open for constructive feedback :)

### CODE REVIEW

**Review by jrasm91 — APPROVED** [review]

**Review by jrasm91 — APPROVED** [review]
LGTM

**Comment by jrasm91** [comment]
@alextran1502 can you test this when you have a second?

**Comment by zackpollard** [comment]
I'll take a look at this and test it tomorrow

**Review by alextran1502 — APPROVED** [review]

**Comment by aminomaboul** [comment]
i update the both the mobile app and the server (1.105.0 build 139 and 1.105.1) but still cannot see the option in the Asset Viewer settings section on the mobile App (Android)

**Pull request merged**
