### PR TITLE
fix(web): remove processing key events in photo viewer window

### LINKED ISSUE #3165: image metadata cannot be copied to clipboard
### The bug

I want to copy the filename, but can't because Immich is quite aggressively pushing the image to the clipboard instead.

image

### The OS that Immich Server is running on

N/A

### Version of Immich Server

v1.65.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
N/A
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by tranquanghuy0801**
Resolves #3165 

Currently processing key events are always executed. Update this to allow only when range selection is not active

### CODE REVIEW

**Comment by bo0tzz** [comment]
Does the image copying feature still work with this change?

**Comment by tranquanghuy0801** [comment]
> Does the image copying feature still work with this change?

If you click on the `Copy` button it still works. Or is there another way to copy the image?

**Review by jrasm91 — COMMENTED** [review]
We want to change it from "ctrl + c always copies the image" to "ctrl + c only copies the image when there is no text selected". ie selection type is not "Range".

https://developer.mozilla.org/en-US/docs/Web/API/Selection/type

**Comment by tranquanghuy0801** [comment]
> We want to change it from "ctrl + c always copies the image" to "ctrl + c only copies the image when there is no text selected". ie selection type is not "Range".
> 
> https://developer.mozilla.org/en-US/docs/Web/API/Selection/type

Sorry for that. Also thanks for the guidance. Updated my work

**Review by bo0tzz — APPROVED** [review]

**Review by jrasm91 — APPROVED** [review]

**Pull request merged**
