### PR TITLE
fix(docs) Fix relative paths leading to broken links

### PR DESCRIPTION
**Pull request by thariq-shanavas**
If there is a trailing slash on a documentation page, any links referenced as ../xxx/file.md do not work

e.g.,
The links on this page work: https://immich.app/docs/overview/quick-start
The links on this page don't: https://immich.app/docs/overview/quick-start/

The trailing slash is automatically added if the user refreshes the page or gets there from an external link,
Specifying absolute path fixes this.

cc @danieldietzler

### CODE REVIEW

**Review by alextran1502 — APPROVED** [review]

**Comment by jrasm91** [comment]
Can we add a rule or check to catch these in the future?

**Review by jrasm91 — APPROVED** [review]

**Comment by thariq-shanavas** [comment]
@jrasm91The trailing slash is never added on a local deployment, which makes me think it is a bug with Docusaurus. (Also presumably why it went uncaught so long)

If you concur, I'll open an issue there instead of writing a test to catch relative paths.

**Comment by bo0tzz** [comment]
From https://github.com/facebook/docusaurus/issues/2298#issuecomment-590911963:
> For the links to work, a file name (along with the extension) has to be used (e.g. `[docs 2](doc_test_2.md)`). If you do something like `[docs 2](doc_test_2)`, Docusaurus doesn't treat that link as a Docusaurus file and doesn't process the href value. The end result is it becomes a relative link and defaults to the browser behavior

I think this might be what is happening for us? Unfortunately I can't find a lint or setting to enforce that `.md` suffix.

**Review by danieldietzler — APPROVED** [review]

**Comment by jrasm91** [comment]
Sounds like it would be better to add extensions to the links instead.

**Comment by thariq-shanavas** [comment]
The really confusing bit is Docusaurus does not add a trailing slash when deployed locally.
image


From Docusaurus documentation, it appears like it might be something to do with cloudflare.
https://docusaurus.io/docs/api/docusaurus-config
image

From the Cloudflare forum:
https://community.cloudflare.com/t/removing-trailing-slash-on-static-websites/583429

The easiest fix appears to be simply specifying the absolute path. I'm open to more elegant solutions though.

**Comment by bo0tzz** [comment]
The `trailingSlash` option applies to the `.md` -> `.html` link transform. The issue I flagged above is that (some of?) our links don't even end in `.md` to begin with, meaning that docusaurus does not pick up on them for transforms (but just passes them through verbatim). That also means this `trailingSlash` option would have no effect on them.

**Pull request merged**
