### PR TITLE
feat(web): Improved assets upload

### PR DESCRIPTION
**Pull request by Willena**
Changes summary;
- [Web] Upload Queue: New process algorithm
- [Web] Upload Queue: Concurrency correctly respected when dragging / adding multiple group of files to the queue
- [Web] Upload Task: Add more information about progress (upload speed and remaining time)
- [Web] Upload Panel: Add more information to about the queue status (Remaining, Errors, Duplicated, Uploaded)
- [Web] Upload Panel: The floating button reflects the number of errors and remaining uploads
- [Web] Error recovery: Asset information are kept in the queue to give the user a chance to read the error message
- [Web] Error recovery: On error, allow the user to retry the upload or hide the error / all errors
- [Web] Upload Queue: Use API SDK instead of "raw" axios request
- [Web] Upload Queue: Upload parallelism (concurrency) can be updated while uploading. Configuration is not persistent across page refreshes. 

Screenshots for changed UI elements:
image

Updated Screenshots:
| Light Mode | Dark Mode|
| - | - |
| image | image |

Remaining issues not solved by this PR (I'll try to work on them)
- In albums, too many notifications are displayed (notification takes all screen space; It might be useful to group "addToAlbum" calls by batch or at the end of the queue. This will also make less request for the API to process) 
- UI not automatically refreshing after assets are uploaded

### CODE REVIEW

**Comment by samip5** [comment]
Ooooh, this looks awesome. Cannot wait to test it out. :fire:

**Review by jrasm91 — APPROVED** [review]
Thanks for the PR!

**Comment by jrasm91** [comment]
BTW - the `fileUploadHandler` needs to return asset ids of the uploaded items, otherwise the files cannot be added to the shared link (individual).

**Comment by Willena** [comment]
Thanks for the corrections. 
I'm new to the project and not very familiar with the svelte framework. 

Thanks for the explanation. At first sight I thought the result of fileUploadHandler was not used, that why I left an empty array. 

Sorry for the linting issues. Exceptionally I was on window and prettier/eslint does not seem to do the job correctly even though I ran the command....

**Comment by jrasm91** [comment]
Haha no worries, thanks for the PR! It is a welcomed improvement.

**Pull request merged**
