### PR TITLE
Revert "perf: precompress and cache assets (#7757)"

### PR DESCRIPTION
**Pull request by alextran1502**
This is causing development issues, and there seems to be more work we need to do to handle this change.

This reverts commit ba55e867e04c6e4e509bb6f6c00a7603442ffec2.

### CODE REVIEW

**Comment by benmccann** [comment]
What was the issue?

**Comment by mertalev** [comment]
It worked fine when I tested it. Was there something wrong with it?

**Comment by alextran1502** [comment]
@mertalev @benmccann 

The mobile app cannot connect to the server, and you have to manually create a `www` directory I believe

**Comment by benmccann** [comment]
Wouldn't the www folder be created during build before the server tries to startup?

**Comment by shenlong-tanwen** [comment]
> The mobile app cannot connect to the server, and you have to manually create a `www` directory I believe

I faced only the `www` dir not available issue. After creating it and starting the server back fixed everything. Even the mobile app works.

**Comment by jrasm91** [comment]
> Wouldn't the www folder be created during build before the server tries to startup?

Yes, but not in development. I ran into the same issue with the previous implementation and had to check for it's existence to determine if the middleware should be added or not. Also, I think there is an env variable for `www` that should be used instead.

**Pull request closed without merging**
