### PR TITLE
feat(web): Duplicate-Page shortcut changes

### PR DESCRIPTION
**Pull request by JW-CH**
- Reassigned 'Select all' from `shift`+`k` => `a`
- Reassigned 'Select none' from `shift`+`t` => `d`
- Added new shortcut to 'View asset' on `s`

Feel free to change things up, but for me those shortcuts felt good to efficiently resolve duplicates. I left the 'handle Resolved' shortcut on `shift`+`c`

### CODE REVIEW

**Comment by JW-CH** [comment]
I am trying to add a 'show shortcuts' page similar to the user settings, converted into draft again

**Review by danieldietzler — APPROVED** [review]
Code looks good to me!

**Comment by JW-CH** [comment]
Does this PR require changes to be accepted? Or do you guys just merge before a release? :)

**Comment by danieldietzler** [comment]
We're kinda under the water right now with a lot of stuff going on, which you can also see by the 72 open PRs :)
Hopefully we'll get that merged in for the next release though

**Review by alextran1502 — APPROVED** [review]

**Pull request merged**
