### PR TITLE
fix(server): cannot delete an asset if presented in album

### PR DESCRIPTION
**Pull request by alextran1502**
## Description

Fixes issues with assets in albums that cannot be deleted due to missing references in the ManyToMany declaration in AlbumEntity

## How Has This Been Tested?

- [x] Add assets to album(s) and delete from the main timeline
- [x] Delete assets from the mobile app

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by jrasm91 — COMMENTED** [review]
Hmm, I don't think we want to do that migration. It is removing the cascade from the foreign key. Can you add those cascade options to the many to many decorator?

If I'm not mistaken the database is correct, but the metadata on this side of the relationship is missing, which prevents TypeORM from working as expected. We probably will fix this without actually running a migration.

**Comment by alextran1502** [comment]
> Hmm, I don't think we want to do that migration. It is removing the cascade from the foreign key. Can you add those cascade options to the many to many decorator?
> 
> If I'm not mistaken the database is correct, but the metadata on this side of the relationship is missing, which prevents TypeORM from working as expected. We probably will fix this without actually running a migration.

This is correct, it works without the migration. I run the migration just in case there is anything mismatched because it would present in the next migration anyway. Let me try adding those relationships to the entity

**Review by jrasm91 — APPROVED** [review]
Looks good. Did this successfully fix the delete asset problem?

**Comment by alextran1502** [comment]
> Looks good. Did this successfully fix the delete asset problem?

Yes it did

**Pull request merged**
