### PR TITLE
feat(mobile): Uses profile photo for user avatar drawer

### PR DESCRIPTION
**Pull request by martyfuhry**
Without a profile photo:
image

With a profile photo:
image

### CODE REVIEW

**Comment by alextran1502** [comment]
Hi Marty, I personally don't want this change. I don't have any reasonable reason other than how I perceived the look and feel of the app bar.

**Comment by alextran1502** [comment]
I am gonna leave this open and sleep on it for a few nights and see if I change my opinion.

FWIW, the image on the app bar doesn't change if you change the old avatar to a new one. Probably caching issue.

**Comment by martyfuhry** [comment]
> I am gonna leave this open and sleep on it for a few nights and see if I change my opinion.

Entirely up to you! It wasn't anything discussed or requested elsewhere. This is just a proposal. 

> FWIW, the image on the app bar doesn't change if you change the old avatar to a new one. Probably caching issue.

Thanks, I'll take a look if you decide you'd like to keep it.

**Comment by alextran1502** [comment]
Hi @martyfuhry, I added some more styling to the profile image, and I think I like it better. Let's fix the error of not uploading then we can merge this PR in

**Pull request merged**
