### PR TITLE
feat(server): apply storage migration after exif completes

### PR DESCRIPTION
**Pull request by jrasm91**
Apply storage migration after exif process saves `fileCreatedAt`.

### CODE REVIEW

**Review by bo0tzz — APPROVED** [review]
`handleTemplateMigration` has a TODO about removing some livePhoto stuff, is that applicable yet? And if so, can that function be refactored just delegate to the `single` one?

**Comment by alextran1502** [comment]
I tried to upload LivePhotos, and the motion part doesn't get moved correctly to the `library` folder

## Actual

image

## Expected

image

**Review by alextran1502 — CHANGES_REQUESTED** [review]
Error in moving LivePhotos

**Comment by jrasm91** [comment]
@alextran1502 - did a bit more testing with live photos and it seems to be working now. Feel free to retest.

**Review by alextran1502 — APPROVED** [review]

**Pull request merged**
