### PR TITLE
feat(web,server): Allow search page albums to be visible or not

### PR DESCRIPTION
**Pull request by samip5**

### CODE REVIEW

**Comment by samip5** [comment]
I'm really not sure what's the issue with the e2e tests...

**Review by jrasm91 — COMMENTED** [review]
I feel like this setting/preference is not really a great solution, but more of an indication of a bad (current) design. The solution should be to improve the relevancy/UX of search in general and specifically for albums not make a setting to turn it off.

**Comment by alextran1502** [comment]
@samip5 my apologize if I sent a mix message. My thought was to fix the issue, to hide the album if there is no relevant results

**Comment by alextran1502** [comment]
> That was a very mixed message yes. If I'm searching for videos and there is only one album that contains some, that album should be shown but not archived nor albums with no videos, right?

Yes, this sounds correct

**Pull request closed without merging**
