### PR TITLE
feat(web,server): link/unlink oauth account

### PR DESCRIPTION
**Pull request by jrasm91**
This PR adds the ability for a user to link/unlink their OAuth account in the user settings page.

I also fixed two bugs and added tests for them.
- Unable to login with OAuth (unnecessary `AuthUserDto` everywhere on the unauthenticated route)
- Able to make yourself an admin due to `dto.isAdmin` not being checked in `userCore.updateUser`.

image

TODO:
- [x] Refactor sections into separate components
- [x] Refactor oauth login/callback logic
- [x] Update the docs to include the new callback url:  `/user-settings` ~(waiting for doc refactor)~
- [x] Fix update user bug ~(waiting for user core services refactor)~
- [x] Update oauth tests (^^)

### CODE REVIEW

**Comment by alextran1502** [comment]
I got the redirect error when try linking an account. I tested with both accounts in the OAuth provider and an account not present in the OAuth provider.

Unlink works fine but linking seems to have a problem with my setup

image

image

image

image

**Comment by jrasm91** [comment]
Yup, there is a new redirect url you need to add. See the docs in the PR 😁

**Comment by jrasm91** [comment]
That brings up a good point though. I need to make sure an oauth account can only be linked to one immich user.

**Comment by alextran1502** [comment]
> Yup, there is a new redirect url you need to add. See the docs in the PR 😁

Can you double-check? I don't see the any files in the `docs` get modified

**Comment by jrasm91** [comment]
Oh dang. I made there changes, but must not have pushed them. You need another redirect URI with /user-settings in addition to /auth/login.

**Review by alextran1502 — APPROVED** [review]
Looks good, let's merge it in

**Pull request merged**
