### PR TITLE
Fix - When deleting assets, albums thumbnails can break

### PR DESCRIPTION
**Pull request by badbreze**
This can be simulated creating an album with 1 or more assets, then from the mail library, when deleting the relative album thumbnail asset, when you get back to albums, the thumbnail is broken

### CODE REVIEW

**Comment by alextran1502** [comment]
It would be better to approach from the album repository standpoint, checking if the thumbnail is valid when fetching the album and then changing the thumbnail to empty or to the next available asset in the album.

**Comment by badbreze** [comment]
you're probably right, I'm not very familiar with the language so I did the best I could. i will try to understand if i can find a better solution but i don't promise anything :D

**Comment by badbreze** [comment]
@alextran1502 I was thinking, if I move this logic to fetch, it creates unnecessary overload, assuming you have N albums, every time you fetch, it will unnecessarily perform checks on all albums, does that make sense?

**Comment by alextran1502** [comment]
> @alextran1502 I was thinking, if I move this logic to fetch, it creates unnecessary overload, assuming you have N albums, every time you fetch, it will unnecessarily perform checks on all albums, does that make sense?

It makes sense, but I think the overhead is low. Because you would only check if the file is there; if it is not there, then set it to `null` (simple case), and the user can handle the part of setting a different asset in the album for the thumbnail. Checking the file is valid is a mechanism that is done whenever you fetch the thumbnail already, so if you compare to the N album that will be fetched, it is pretty low comparing to thousands and thousands of assets are fetched when you scroll the timeline

The pros of having such a mechanism in the `AlbumService` so that you group the logic in its respective actions.

**Comment by alextran1502** [comment]
Implemented in #681

**Pull request closed without merging**
