### PR TITLE
feat(web): search names when merging faces

### PR DESCRIPTION
**Pull request by martabal**
## Changes made in this PR

This PR adds the ability to filter people by names on the merge selector
Solves #5207

## Screenshots

| Light mode | Dark mode |
| :---: | :---: |
| Screenshot from 2023-11-21 03-33-05 | Screenshot from 2023-11-21 03-33-24 |

### CODE REVIEW

**Review by jrasm91 — APPROVED** [review]

**Comment by alextran1502** [comment]
I moved the search text box outside of the list of faces to prevent the text box from getting scrolled with the list of faces. Also, I removed the argument for force search and made it the default to simplify the logic.

**Comment by martabal** [comment]
It means you make an API request for every input even if the previous API request returned every faces with a name starting with your searched word - which is a bit useless

**Comment by alextran1502** [comment]
It serves the case of you type "Alo" then remove the "o" then it will search and show the correct result for "Al". With the force option, it does not do that unless  you click on the magnifying glass icon, which is unclear to the user

**Comment by martabal** [comment]
Oh, this isn't supposed to happen, let me fix it

**Pull request merged**
