### PR TITLE
refactor(mobile): maplibre

### PR DESCRIPTION
**Pull request by shenlong-tanwen**
#### Changes made:

- Replaces [flutter_map](https://pub.dev/packages/flutter_map) with [maplibre_gl](https://pub.dev/packages/maplibre_gl) which should hopefully solve the performance issues with rendering vectors

#### TODO:

- [x] Test it on a physical iOS device
- [x] Two-pane view in landscape
- [x] Fix location picker
- [x] Add zoom to current location
- [x] Add no assets in bounds placeholder
- [x] Tests
- [ ] Check if this passes the F-droid build

### CODE REVIEW

**Comment by alextran1502** [comment]
@shenlong-tanwen Thank you for the PR. It works very well on an actual iOS device, the map tile is now loading instantly. The pinch to zoom is a bit sensitive. Let's finish this up and get it merge

**Comment by shenlong-tanwen** [comment]
>     * The pinch to zoom is a bit sensitive.

Let me check if there is something we can do to improve it. We can take this as a non-blocker and can handle it in a separate PR though. Can you check if double tap to zoom suffers from the same issue as well? On android, both seem fine to me.

>     * I got some error while scrolling around the home page

I tried scrolling through the home page few times but cannot reproduce this. Is there anything I can do to reproduce it consistently?

>     * In the location picker, when switching to the view of selecting the location on the map, the map isn't rendered

This was not implemented then. I've added it back now

**Comment by waclaw66** [comment]
Do you plan to consolidate location pin image with the web version?

**Comment by shenlong-tanwen** [comment]
> Do you plan to consolidate location pin image with the web version?

The refactoring includes a new pic but this is still different than the web version though.

**Review by alextran1502 — APPROVED** [review]

**Comment by waclaw66** [comment]
This is how position settings looks like on Samsung Galaxy S20 FE...
- a tall gray bar at the top
- bottom buttons are hidden under system navigation bar

Nepojmenované

**Comment by shenlong-tanwen** [comment]
> This is how position settings looks like on Samsung Galaxy S20 FE...
>     * a tall gray bar at the top
>     * bottom buttons are hidden under system navigation bar
> 

I cannot reproduce this on my end. Can you please check if #6553 fixes it for you?

**Comment by waclaw66** [comment]
> I cannot reproduce this on my end. Can you please check if #6553 fixes it for you?

Will try tomorrow, thanks.

**Comment by waclaw66** [comment]
Seems to be fixed with #6553.

Nepojmenované

**Pull request merged**
