### PR TITLE
refactor(mobile): reworked Asset, store all required fields from local & remote

### LINKED ISSUE #1537: [Tech-Debt]: Refactor asset service and asset_cache service from home to shared module

### PR DESCRIPTION
**Pull request by fyfrey**
replace usage of AssetResponseDto with Asset

Add new class `ExifInfo` to store data from `ExifResponseDto`

This is a first step towards offline support.

fixes #1537

### CODE REVIEW

**Comment by alextran1502** [comment]
Fynn, are we going to potentially mirror most of the DTO to the client database? What is the high-level strategy that you are planning to carry out for the offline mode?

**Comment by zoodyy** [comment]
> Fynn, are we going to potentially mirror most of the DTO to the client database?

Yes, that is the plan. Rather than mirroring the DTOs, we somewhat mirror the `*.entity.ts` files used for the server database. Not a perfect mirror though because Isar DB works different than classic relational databases and we might not need all data that is on the server but need other data relevant only to the mobile app. 

> What is the high-level strategy that you are planning to carry out for the offline mode?

I'll open a thread in discord

**Comment by alextran1502** [comment]
The build and test found an error here 
image

**Comment by zoodyy** [comment]
> The build and test found an error here image

@alextran1502 yes.. merge conflicts resolving gone bad. fixed that. github job is running again

**Comment by alextran1502** [comment]
Bug report

image

`663FBB64-9FE2-439A-B53D-6EB65F66EFB3/L0/001` is the device asset id on iOS

**Comment by zoodyy** [comment]
@alextran1502 thanks a lot for testing on iOS! I fixed the first issue.

No clue currently about the second one with  `deviceAssetId` being `null` in the JSON..

**Comment by alextran1502** [comment]
@zoodyy From the stack trace, it seems like it was fired from `AssetCacheService._computeEncode` function. I guess this is from my local storage cache information that doesn't have the `deviceAssetId` before - Confirmed that this is the case, we might want to handle this. You can recreate it by using a release version, then after that using the version in the PR.

The problem with iOS isn't fixed for some reasons
image

With this error, the local assets aren't displayed. How does the local asset get constructed, did we passed in the correct `id` property from the `AssetEntity` of the `photo_manager` package?

**Comment by zoodyy** [comment]
@alextran1502 thanks a lot for testing!

I've reworked the PR, no need anymore for the asset ID parsing.
Further, I tried to migrate any existing asset cache, but it does not contain all required information. So instead, the cache is now invalidated if an error occurred when reading data.
I've tested the latest version of this PR this with first running app from main branch, loading images, closing app, re-building app from this PR, loading app, message is correctly logged that asset cache had to be cleared

If you can verify it works now (finally!) also on iOS, go ahead with the merge.

**Comment by martyfuhry** [comment]
> If you can verify it works now (finally!) also on iOS, go ahead with the merge.

I checked this out and ran it on a physical iOS device and all seemed well. I had a few errors, but I doubt they had anything to do with this PR:

### 1
```
Unhandled Exception: Bad state: Tried to use BackupNotifier after `dispose` was called.

Consider checking `mounted`.

#0      StateNotifier._debugIsMounted.<anonymous closure> (package:state_notifier/state_notifier.dart:175:9)
#1      StateNotifier._debugIsMounted (package:state_notifier/state_notifier.dart:182:6)
#2      StateNotifier.state (package:state_notifier/state_notifier.dart:196:12)
#3      BackupNotifier._getBackupAlbumsInfo (package:immich_mobile/modules/backup/providers/backup.provider.dart:223:13)
<asynchronous suspension>
#4      BackupNotifier.getBackupInfo (package:immich_mobile/modules/backup/providers/backup.provider.dart:396:7)
```

### 2
```
2023-02-04 13:46:37.396762-0500 Runner[23987:961638] [error] error: XPC: synchronousRemoteObjectProxyWithErrorHandler encountered error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service created from an endpoint was invalidated: failed to check-in, peer may have been unloaded: mach_error=10000003." UserInfo={NSDebugDescription=The connection to service created from an endpoint was invalidated: failed to check-in, peer may have been unloaded: mach_error=10000003.}
```

### 3
```
2023-02-04 13:46:20.066601-0500 Runner[23987:961855] [PAAccessLogger] Failed to log access with error: access=<PATCCAccess 0x283489260> accessor:<<PAApplication 0x28196c4b0 identifierType:auditToken identifier:{pid:23987, version:71762}>> identifier:14EF4421-790D-4F9A-AAE8-D5943CC04D65 kind:intervalEnd timestampAdjustment:0 tccService:kTCCServicePhotos, error=Error Domain=PAErrorDomain Code=10 "Possibly incomplete access interval automatically ended by daemon"
```

I'm pretty sure that two of these are related to #1470 which has been plaguing me. Anyway, the code looks nice and clean, too!

**Pull request merged**
