### PR TITLE
refactor(web): albums list (2)

### PR DESCRIPTION
**Pull request by martabal**
Following #7966, This PR moves the shared / owned / all views to the same albums list

### Screenshots

Full screen

Screenshot from 2024-03-23 10-08-29

Iphone screen

image

### CODE REVIEW

**Review by jrasm91 — APPROVED** [review]
This looks good to me. With the removal of albums from "sharing", the page doesn't do much anymore. There are a few things we still need though, but that page right now looks pretty empty. We still need a way to view all shared-links. We also need a way to get to partner photos. I like having all the albums under the album page, but I think we might want to change _something_ about the sharing page although I don't know exactly what to do.

**Comment by alextran1502** [comment]
Please keep the sharing page as is for now. We add these options to the Albums page for convenience

**Review by alextran1502 — APPROVED** [review]

**Comment by waclaw66** [comment]
One remark, there is preseleced no choice from All, Owned and Shared by default, therefore no albums will be shown after new release update.

**Comment by martabal** [comment]
> One remark, there is preseleced no choice from All, Owned and Shared by default, therefore no albums will be shown after new release update.

Yeah, you just need to click once on one of the new buttons

**Pull request merged**
