### PR TITLE
feat(server): return asset checksum

### PR DESCRIPTION
**Pull request by jrasm91**
- Add checksum (base64)
- Add `resize: boolean`
- Remove webp, encoded video path, resize path

### CODE REVIEW

**Comment by michelheusschen** [comment]
Encoding the checksum as base64 is inconsistent with `bulkUploadCheck` where they're handled as hexadecimal, it would be good to keep that consistent

**Comment by fyfrey** [comment]
> Encoding the checksum as base64 is inconsistent with `bulkUploadCheck` where they're handled as hexadecimal, it would be good to keep that consistent

base64 is shorter and we already have HUGE requests/responses. Maybe we can change `bulkUploadCheck` in follow-up PR to also use base64 (or anything even shorter if we have that)

**Review by fyfrey — APPROVED** [review]
thank you! checksum works flawless in the app

**Comment by jrasm91** [comment]
I updated the bulk endpoint to accept both `hex` and `base64` values in the checksum field. I think that provides both flexibility and consistency. We can return checksum as `base64` in the asset response dto though, since it is more compact.

**Pull request merged**
