### PR TITLE
docs: add product key to roadmap

### PR DESCRIPTION
**Pull request by aviv926**
image

### CODE REVIEW

**Comment by zackpollard** [comment]
You used the forbidden word

**Comment by aviv926** [comment]
> You used the forbidden word 🙈

Yes, I wasn't really sure how we would like to write it..
You have an idea? 😅

**Comment by alextran1502** [comment]
Maybe "Option to Buy Immich" we know have "The word must not be named" lmao

**Comment by aviv926** [comment]
> Maybe "Option to Buy Immich" we know have "The word must not be named" lmao

Haha yeah.
I think that's a really good option.
image

**Review by jrasm91 — APPROVED** [review]

**Pull request merged**
