### PR TITLE
chore(mobile): translation update

### PR DESCRIPTION
**Pull request by alextran1502**
Exported the most recent translations from Localizely

### CODE REVIEW

**Review by bo0tzz — APPROVED** [review]

**Comment by ja49619** [comment]
@alextran1502 hi Alex, where can I contribute to the translation of the mobile version? Your documentation only contains a link to webplate, but now you are writing about Localizely. I couldn’t find where I can change the translation of the mobile version, if it’s not difficult, please tell me

**Comment by alextran1502** [comment]
@ja49619 can you send me your email address so I can invite you to the platform?

**Comment by ja49619** [comment]
> @ja49619 can you send me your email address so I can invite you to the platform?

ja49619@gmail.com

**Comment by alextran1502** [comment]
@ja49619 What language are you planning to contribute?

**Comment by ja49619** [comment]
> @ja49619 What language are you planning to contribute?

ru_RU

**Pull request merged**
