### PR TITLE
feat(web) Make "no albums" card clickable (#888)

### PR DESCRIPTION
**Pull request by bo0tzz**
On the albums page, if no albums exist, there is a card saying so and inviting you to create a new album. That card looks very clickable, but isn't. This change fixes that.

### CODE REVIEW

**Comment by jrasm91** [comment]
Could we add cursor: pointer as well if it is clickable?

**Comment by bo0tzz** [comment]
For consistency I went with what the standard create album button also does: background change on hover, but no cursor. If we do add a cursor change, it might be worth making that change more broadly for most/all of the hover buttons we have and maybe extracting the details to a css class?

**Comment by jrasm91** [comment]
> For consistency I went with what the standard create album button also does: background change on hover, but no cursor. If we do add a cursor change, it might be worth making that change more broadly for most/all of the hover buttons we have and maybe extracting the details to a css class? 

Sounds good. I think things like links and buttons are cursor pointer automatically, so I've always add it to elements with click events that aren't links. Semantically the card is a link even though we're using an image with a svelte click event.

I'm good with just revisiting this later though. I like the change of making it clickable. I assumed it was clickable and tried to click it the first time lol.

**Comment by bo0tzz** [comment]
> I assumed it was clickable and tried to click it the first time lol.  

Me too, that's what prompted me into making this change lol.  
I just checked on another device and now I am seeing the cursor: pointer on the standard create album button, so I'll add it to this as well.

**Pull request merged**
