### PR TITLE
feat(web): Implemented device last seen date and time with user locale support

### PR DESCRIPTION
**Pull request by declan8010**
This pull request introduces enhancements to the last seen functionality in our application. Previously, the last seen information displayed only the time elapsed since the device was last seen. However, with this update, I have implemented support for displaying the date and time of the last seen event, enhancing the user experience.

Before:
image

After:
image

Totally open to suggestions for this in terms of how its displayed

### CODE REVIEW

**Comment by declan8010** [comment]
No idea why prettier is failing, Its all showing good in my VSCode could someone take a look please?

**Comment by alextran1502** [comment]
> No idea why prettier is failing, Its all showing good in my VSCode could someone take a look please?

Try run `npm i` again in the `web` directory

**Comment by alextran1502** [comment]
I think if it is last seen over 7 days then we display the time, otherwise, keep the day count

**Comment by jrasm91** [comment]
I like the relative date format myself. 90 seems more useful than some random date. I don't really care if it was October 11th or November 1st. I would be fine adding a way to get the actual date though. Something like text-underline on 90 days ago and when it is clicked or hovered shows the actual date.

**Comment by declan8010** [comment]
Hey both what do you think of this change?

firefox_Tx91Zmj1Sh

**Comment by alextran1502** [comment]
From UX point of view, I think it adds unnecessary interaction where you can just present the information on screen

**Comment by declan8010** [comment]
Sounds good, Do you think just displaying it under the current values in a sub text style?

**Comment by alextran1502** [comment]
Yeah, you can try that or also display it on the same line after a dash

**Comment by declan8010** [comment]
What do we think of this layout? 

image

**Comment by alextran1502** [comment]
> What do we think of this layout?
> 
> image

I like it!, thank you

**Comment by declan8010** [comment]
All pushed and good to go 👍

**Review by alextran1502 — APPROVED** [review]

**Comment by jrasm91** [comment]
Nice work, looks great.

**Pull request merged**
