### PR TITLE
117 service names

### PR DESCRIPTION
**Pull request by chasx003**
Allows for service names to be set by environment variables

### CODE REVIEW

**Comment by alextran1502** [comment]
I would delete the environmental variables in each Dockerfile of the `server` and `microservices` folder, then move them into the `docker-compose` file instead. Since the production build is pulled from Dockerhub, putting the environment variable in there will give the user the option to change them if wanted.

For an example of the `docker-compose.dev.yml` file

```yaml
version: "3.8"

services:
  immich_server:
    image: immich-server-dev:1.7.0
    build:
      context: ../server
      dockerfile: Dockerfile
    command: npm run start:dev
    expose:
      - "3000"
    volumes:
      - ../server:/usr/src/app
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /usr/src/app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - DB_HOST=immich_postgres 
      - REDIS_HOST=immich_redis
      - MICROSERVICE_HOST=immich_microservices
    depends_on:
      - redis
      - database
    networks:
      - immich_network

  immich_microservices:
    image: immich-microservices-dev:1.7.0
    build:
      context: ../microservices
      dockerfile: Dockerfile
    command: npm run start:dev
    expose:
      - "3001"
    volumes:
      - ../microservices:/usr/src/app
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /usr/src/app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - DB_HOST=immich_postgres 
    depends_on:
      - database
    networks:
      - immich_network

[...]

```

**Comment by chasx003** [comment]
sorry for the MIA -- I tried to make the changes you suggested, but I'm not very good with git best practices , so I'm not really sure what I need to do because of the conflicts etc.

**Comment by badlandspray** [comment]
Could this be merged? I really would like to specify redis, db host.

**Comment by alextran1502** [comment]
I will incorporate this into #163 since it has additional information for testing and other environment variables.

**Comment by alextran1502** [comment]
Solved in #174

**Pull request closed without merging**
