### PR TITLE
fix(mobile): Remove occurrences of manual string pluralization

### PR DESCRIPTION
**Pull request by adamantike**
Instead, use `.plural` to find the correct string translation.

### CODE REVIEW

**Comment by alextran1502** [comment]
FYI, update any translation file beside EN-US won't be merged in Localizely. And they will be replaced when we pull down information from Localizely

**Comment by adamantike** [comment]
Is Localizely smart enough to not lose the singular/plural versions of `album_thumbnail_card_items` for each language? Otherwise, each translator should update these strings again when the changes reach upstream.

I expected Localizely to work bidirectionally, to also allow for bulk edits directly in the json files, without overriding everything next time we import new translated strings.

**Comment by jrasm91** [comment]
It might, but I think generally we always just export and overwrite the json files. If you want to spend time investigating and coming up with a process to support bidirectional, by all means, but for the foreseeable future I think we will continue to pull/overwrite all the non English transitions.

**Comment by adamantike** [comment]
Thanks for the context! I have reverted any translation file changes, except for `en-US`. Let's check if Localizely's translation memory helps in not losing the existing one/many translations for some of the existing strings.

**Comment by shenlong-tanwen** [comment]
We can pick this up after migrating to a better localization tool that handles plurals properly. Localizely messes up the translation keys when merging the changes

**Pull request closed without merging**
