### PR TITLE
feat(web): add archive shortcut to grid

### LINKED ISSUE #9466: timeline view - shortcut Shift-a not working to move assets to archive
### The bug

I can archive selected assets in the main timeline view only by using the 3-dot-menu > archive
But when I use shift-a, then nothing happens.
When I press "?" I get the hint, which shortcuts can be used. Shift-A is listed.
But it looks like, the information, which is displayed when pressing "?" doesn't match the implementation.
I suggest, that the information window content and the implementation should match.

### The OS that Immich Server is running on

docker in synology containers

### Version of Immich Server

v1.104.0

### Version of Immich Mobile App

not relevant

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
1. open the timeline view
2. select one or more assets
3. press shift-A => nothing happens
4. Use the 3-dot-menu > archive => assets will be archived
```

### Relevant log output

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Snowknight26**
Closes #9466.

Per the keyboard shortcut modal, `Shift`+`A` now works on the grid.

### CODE REVIEW

**Comment by Snowknight26** [comment]
Not sure if the keyboard shortcut modal is actually supposed to appear globally since some of the actions don't apply in all contexts (`i` for show/hide info is only applicable when viewing assets), but c'est la vie.

**Review by danieldietzler — APPROVED** [review]
Code looks good to me!

**Review by jrasm91 — APPROVED** [review]
Seems to work well.

**Comment by Snowknight26** [comment]
Need to merge main in again but I'm wondering.. is this superseded by #9712?

**Comment by jrasm91** [comment]
Probably, but this one works and doesn't have any conflicts. That one has a bunch and other unresolved comments, so I'm just going to merge it.

**Pull request merged**
