### PR TITLE
feat(web): added toggle for Sharing button in the sidebar

### PR DESCRIPTION
**Pull request by upsetdog**
A simple toggle (defaults to True) to hide the Sharing button in the sidebar, in the Sidebar settings.

### CODE REVIEW

**Comment by alextran1502** [comment]
Hello, what is the purpose of this change?

**Comment by upsetdog** [comment]
> Hello, what is the purpose of this change?

I'm the only user of my instance so don't need the sharing feature, so thought a toggle would be useful to reduce clutter for those in a similar position :)

**Review by jrasm91 — APPROVED** [review]
Lgtm

**Comment by alextran1502** [comment]
Can you help fix the build error with `npm run format:fix` in the web directory?

**Comment by shenlong-tanwen** [comment]
> I'm the only user of my instance so don't need the sharing feature, so thought a toggle would be useful to reduce clutter for those in a similar position :)

We still show add to shared album and other actions throughout the app. It might make sense to handle it everywhere instead of hiding it only from the sidebar if sharing is not needed entirely.

**Comment by alextran1502** [comment]
@shenlong-tanwen I think what he has make sense since this is probably user preference

**Comment by waclaw66** [comment]
Sharing should be enabled by default.

**Pull request merged**
