### PR TITLE
fix(milestone): Fix zero-index dates

### PR DESCRIPTION
**Pull request by etnoy**
Fix a stupid typo in my last pr

### CODE REVIEW

**Comment by martabal** [comment]
Maybe merge it once v1.94 is released ? Just to be sure to have the correct date

**Comment by etnoy** [comment]
> Maybe merge it once v1.94 is released ? Just to be sure to have the correct date

Good idea!

**Comment by martabal** [comment]
Oh, and can you add a new milestone for GPU support for machine learning?

**Comment by etnoy** [comment]
Feel free to add it to the pr!

**Review by jrasm91 — APPROVED** [review]

**Comment by jrasm91** [comment]
Might as well publish it since the docs are already wrong

**Pull request merged**
