### PR TITLE
chore: use markdown highlight for README warning 

### PR DESCRIPTION
**Pull request by arcb01**
Updated README with new Warning style 

Before:
## Disclaimer

- ⚠️ The project is under **very active** development.
- ⚠️ Expect bugs and breaking changes.
- ⚠️ **Do not use the app as the only way to store your photos and videos.**
- ⚠️ Always follow [3-2-1](https://www.backblaze.com/blog/the-3-2-1-backup-strategy/) backup plan for your precious photos and videos!

After:

### CODE REVIEW

**Review by jrasm91 — APPROVED** [review]

**Comment by alextran1502** [comment]
Can we change the title of the block to Disclaimer instead of Warning?

**Comment by jrasm91** [comment]
I think the "highlight" stuff has to include `**warning**` otherwise it doesn't render.

**Comment by martabal** [comment]
Maybe using Import ? 

> [!IMPORTANT]  
> The project is under **very active** development.

**Comment by alextran1502** [comment]
Hello, I want to keep the older format to make each point as distinct as possible. Thank you for the idea :)

**Pull request closed without merging**
