### PR TITLE
feat(mobile): Enter server first for login

### LINKED ISSUE #1500: [Feature]: Ask for URL first on a separate Screen and for Authentication afterwards
### Feature detail

I think the UX would be dramatically improved if the user is first asked for the Server fist and gets possible ways of authentication shown afterwards.

Currently it's very confusing for people signing in to an Instance, that only supports OIDC Login since the user gets prompted to enter his credentials in the unused fields first and only after confirming the Server URL field he sees a potential OIDC Login.

The Nextcloud Android App solved this quite nice to offer a reference.

### Platform

Mobile App

### PR DESCRIPTION
**Pull request by martyfuhry**
- Closes #1500 
- Asks for server endpoint url first
- Then asks for login information
- Changes to use `SliverFillRemaining` and `Flexible` to size the page so that the text form fields can change without changing the logo / title layout
- Uses keyboard input actions (Go / Next) to confirm the action or move to the next field (Email -> Password -> Go to login)
- Shows error messages
- Gets server information after entering in server
- Shows loading
- [x] Needs testing with OAuth, since I never set that up on my test machine (thanks for testing @alextran1502)

Screenshot from 2023-03-05 20-43-47

image

### CODE REVIEW

**Comment by martyfuhry** [comment]
I found a bug in the layout, so I'll have to refactor from this `SliverFillRemaining`. It doesn't quite do what I need it to.

**Comment by martyfuhry** [comment]
Should be fixed now. Give it a shot!

**Comment by alextran1502** [comment]
@martyfuhry Thank you for the PR! Good stuff!

I noticed the `photo.domain.com` text never changes to the entered server URL 

image

**Comment by alextran1502** [comment]
Also confirmed that OAuth login works as expected

**Comment by martyfuhry** [comment]
Forgot to remove that placeholder for the screenshot.

**Review by alextran1502 — APPROVED** [review]

**Pull request merged**
