### PR TITLE
Update command-line-interface.md

### PR DESCRIPTION
**Pull request by BoBBer446**
Add immich upload background runs for large inputs

### CODE REVIEW

**Comment by bo0tzz** [comment]
I'm not quite sure how I feel about this; if we want to document how to run the cli in the background at all, maybe describing something like tmux might be better?

**Comment by BoBBer446** [comment]
That's right. It could also be a possibility.
I don't know if it's really better or worse. But I think it's good if the user knows how and that he can do this in the background.

I import over 200,000 images, which takes a while and I don't want to leave the computer on for that long (around 14 hours). Besides, the network could break.

By the way, this is my first request, I have no idea how something like this works :D

**Comment by bo0tzz** [comment]
Sending the CLI process to the background doesn't do anything for those cases

**Comment by BoBBer446** [comment]
Does that mean this way would be better?

1. **Start a new `tmux` session:**
   ```sh
   tmux new -s immich_upload
   ```

2. **Run the `immich upload` command within the `tmux` session:**
   ```sh
   immich upload /path/to/your/files/ -r
   ```

3. **Detach the `tmux` session:**
   Press `Ctrl+b` followed by `d`.
   _This detaches the session, allowing the process to continue running in the background._

4. **Reattach to the `tmux` session:**
   ```sh
   tmux attach -t immich_upload
   ```

The aim should be to be able to switch off and shut down the computer while the import is running

**Comment by bo0tzz** [comment]
> The aim should be to be able to switch off and shut down the computer while the import is running

None of these approaches will be able to do that, and I'm not aware of any way that will.

**Comment by BoBBer446** [comment]
Are we talking at cross purposes?
If I move the process with nohub or tmux to the background or a new temux, then I can shut down the PC, the server continues to run.

Later, I can go back to my the PC and connect to the server and either move the nohub process to the foreground or look at the tmux. So while I have switched off the PC, the import has continued to run.

If I only do “immich upload” in the terminal and close the PC, the process is also terminated.

So tmux and nohub are able to continue a long upload process in the background. Or am I making a mistake?

**Comment by bo0tzz** [comment]
It wasn't clear to me that you were talking about running the cli over ssh. I had understood it as wanting to shut down the system that the CLI was running on. If it's over ssh then tmux is the way to go - in fact, tmux is really nice whenever you're doing anything over ssh cause stuff like connection failures will not mess up your session.

**Comment by jrasm91** [comment]
Yeah, I don't think we need any detailed guides here. Running commands in the background is a common, well-known problem. It is worth mentioning via a note, but we can just refer users to other tools/docs for the details, IMO.

**Pull request closed without merging**
