### PR TITLE
chore(mobile): upgrade gradle

### PR DESCRIPTION
**Pull request by alextran1502**
This PR upgrade the Android project to the latest gradle configuration to work with the latest version of Android Studio

Some of the requirements

- Java 17
- Android Studio Ladybug and above

> [!TIP]
> If you run into error "Unknown Kotlin JVM target: 21", run the following command
> `flutter config --jdk-dir <path-to-java-sdk-17-home-directory>`

### CODE REVIEW

**Comment by alextran1502** [comment]
@shenlong-tanwen finally

**Comment by alextran1502** [comment]
@fyfrey FYI

**Comment by shenlong-tanwen** [comment]
@alextran1502 Much needed 😄 While we're at it, can we also migrate KAPT to KSP. It should be a simple change

**Comment by alextran1502** [comment]
@shenlong-tanwen Can you help me with a commit for that change? Thank you

**Comment by shenlong-tanwen** [comment]
> @shenlong-tanwen Can you help me with a commit for that change? Thank you

Done. Pumped the versions of kotlin and its dependencies to resolve build issues. video_player plugin is also pumped for the same reason.

**Review by shenlong-tanwen — APPROVED** [review]
🚀

**Review by fyfrey — APPROVED** [review]

**Review by jrasm91 — APPROVED** [review]

**Pull request merged**
