### PR TITLE
feat(server): Allow .mkv, .wmv, .flv, .mpg videos to be uploaded

### PR DESCRIPTION
**Pull request by samip5**

### CODE REVIEW

**Review by jrasm91 — APPROVED** [review]
Looks good, assuming you have verified the the thumbnail extraction process works correctly.

**Comment by alextran1502** [comment]
Have you had a chance to test all of the new file format?

**Comment by samip5** [comment]
> Have you had a chance to test all of the new file format?

Yes, I have and all of them work fine. :)

**Comment by michelheusschen** [comment]
All file types get uploaded via web and a thumbnail is correctly generated. However, `video/x-matroska` and `video/x-matroska` files are not transcoded while having limited or no support by browsers for direct playback

**Comment by jrasm91** [comment]
I think it only transcodes them if the video codec isn't  `h264`.

**Comment by michelheusschen** [comment]
Yep tested it with the h264 codec only, a h265 video in .mkv did get transcoded. Tested on Android and all files can be played, so we can either accept those file types are unplayable in some browsers or implement remuxing to mp4.

**Comment by jrasm91** [comment]
I think you might be right that some browsers can't play them, even if the video codec itself is playable. Basically codec + container need to be a valid combination. I think we might be able to leave this as-is for now. I know @zackpollard had mentioned wanting to potentially update the container in addition to the codec for situations like this.  That would be a separate PR though.

**Comment by zackpollard** [comment]
Happy for this change to go in, will add this to the required transcoding changes, need to be smarter with the way transcoding is done anyway.

**Comment by Johan1976** [comment]
> > Have you had a chance to test all of the new file format?
> 
> Yes, I have and all of them work fine. :)

For me the thumbnail images of 16:9 mpg/Mpeg2 videos are in wrong aspect ratio (4:3). The video also plays in 4:3 in Android app. On web or on Ipad they play in 16:9. I have played both the mpg files as well as the transcoded versions in external videoplayer directly from my nas and they both play fine in 16:9. Something seems wrong on server side (and not just Android app) since thumbnails are wrong. What do you need from me to check/verify? Video info say video resolution are 576x720.

**Pull request merged**
