### PR TITLE
refactor(web): centralize buttons

### PR DESCRIPTION
**Pull request by michelheusschen**
Refactors buttons with a couple of reusable components. Previously, a lot of slightly different buttons were used leading to maintainability and consistency issues. I've tried to keep the amount of visual changes to a minimum, but there are some small changes especially between light/dark mode, hover and disabled state.

### CODE REVIEW

**Review by jrasm91 — APPROVED** [review]
Looks good. I wonder if we could have some sort of design page, which has rendered examples of the button variants.

**Comment by alextran1502** [comment]
> Looks good. I wonder if we could have some sort of design page, which has rendered examples of the button variants.

React has something called StoryBook right?

**Comment by michelheusschen** [comment]
Yes, I was just looking into this. Storybook 7 recently released with support for SvelteKit, but it doesn't look too polished. I found [Histoire](https://histoire.dev/) which seems to work better with Svelte but that might not have all features and is also a smaller project.

**Comment by jrasm91** [comment]
Yeah, it doesn't have to be particularly fancy or anything. I was even just thinking about a custom page in the app with some examples lol

Code blocks + rendered components.

**Pull request merged**
