### PR TITLE
chore(compose): Remove unnecessary env values from proxy container

### PR DESCRIPTION
**Pull request by bo0tzz**

### CODE REVIEW

**Review by jrasm91 — COMMENTED** [review]
I think these are still used.

https://github.com/immich-app/immich/blob/main/nginx/15-set-env-variables.envsh

**Comment by bo0tzz** [comment]
They are still supported, but not used or needed in the default setup, and having them there confuses users who think they need to add them to their .env file.

**Comment by jrasm91** [comment]
We can remove them, but then also that may break some installs since they will no longer be passed from the `.env` file. Is that the intended behavior?

**Comment by bo0tzz** [comment]
I would expect that anybody using these env vars has an unusual setup and is aware that these vars need to be passed.

**Comment by jrasm91** [comment]
Sounds good

**Review by jrasm91 — APPROVED** [review]

**Comment by martabal** [comment]
It should probably be mentioned in the next release

**Pull request merged**
