### PR TITLE
doc: update truenas.md with permission info.

### PR DESCRIPTION
**Pull request by NicholasFlamy**
This is very important information about permissions on datasets used by immich.

I was screwing around with permissions and discovered that immich needs these so I edited the docs with info about this.

### CODE REVIEW

**Comment by alextran1502** [comment]
This guide is for the official TrueNAS image which I don't think it is being maintained. TrueNAS team was waiting for the application to go into stable before doing so

**Comment by NicholasFlamy** [comment]
> This guide is for the official TrueNAS image which I don't think it is being maintained. TrueNAS team was waiting for the application to go into stable before doing so

The title of the page says "TrueNAS SCALE [Community]"
I have the community-maintained official TrueNAS repository version of immich installed and it gets updates pretty fast, it even got the recent option for machine learning hardware acceleration (yay). I'm pretty sure this guide is 100% relevant, as I can follow it and have the latest version of immich installed (1.97.0)

**Review by danieldietzler — APPROVED** [review]
This indeed appears to be the version that's still maintained - like @NicholasFlamy and @bo0tzz on Discord mentioned. So this PR looks good to me!

**Comment by NicholasFlamy** [comment]
I think I fixed the formatting. Sorry about that.

**Pull request merged**
