### PR TITLE
chore(server): remove unneeded debug logging

### PR DESCRIPTION
**Pull request by samip5**

### CODE REVIEW

**Comment by bo0tzz** [comment]
No need to comment out code, just remove it ;)

**Review by jrasm91 — COMMENTED** [review]
Can you actually change this to verbose instead?

**Comment by jrasm91** [comment]
Inevitably there will be someone who can't blah blah blah some video file. It'll be nice for them to turn on verbose logging and see the details.

**Comment by samip5** [comment]
For it to be more useful, I think the log should include assetID, but it's not passed though to the isTranscodeRequired function. :(

**Review by jrasm91 — APPROVED** [review]

**Pull request merged**
