### PR TITLE
feat(web): improved album view UI & album card UI

### PR DESCRIPTION
**Pull request by azroberts8**
This PR horizontally expands the asset grid when viewing an album to reduce the large margins on the left and right side of the page. This makes better utilization of screen real estate allowing users to preview more photos at once without reducing thumbnail size like in Google Photos. This PR also modifies the album cards to have a cleaner hover effect.

| Before | After |
| - | - |
| image | image |
| image | image |

### CODE REVIEW

**Comment by jrasm91** [comment]
Can you add before and after screenshots to the pull request description please?

**Comment by azroberts8** [comment]
Sure! Just added screenshots

**Review by jrasm91 — APPROVED** [review]
LGTM

**Review by danieldietzler — APPROVED** [review]
That looks nice, thanks!

**Pull request merged**
