### PR TITLE
feat(mobile): Added data saving mode

### PR DESCRIPTION
**Pull request by JamesCullum**
As a fellow Google Photos refugee, I would love to use Immich heavily. I mostly use it for memories that I watch from my phone, so I'd prefer to enable a voluntary resizing of my images, similiar to how Google Photos does it. This allows my hard drive to not be filled as quickly.

Instead of having a binary choice like in Google Photos, I thought it would be more future proof to give the user more fine-grained control and allow even smaller images.

screenshot screenshot screenshot

For the resizing I had to use an external library. Due to a conflict with flutter_launcher_icons, we cannot use the newest version.

I first spent a day trying to make it work as part of an existing state struct, however this either required API changes, many code changes, didn't save the variable or it wasn't accessible to the background service. Hence I chose the most straightforward solution by just putting the data into a Box. If you would like to do this differently, support would be highly appreciated.

### CODE REVIEW

**Comment by alextran1502** [comment]
Hello, this feature would fit better for an option of the admin's config interface for the following reasons.

1. The admin would have more concerns about data usage on the system.
2. Any heavy processing tasks should happen on the server so that the battery and CPU usage is reserved on the mobile app

**Comment by JamesCullum** [comment]
I thought about this first, but did this on purpose. Doing this on the device has the following advantages:

1. The user can save mobile data volume
2. Workload distributes more nicely
3. Different users can have different settings and can spontanously change it, based on the occasion (e.g. if he wants to upload 200 images in small but normally in high quality, he can change the setting, start the backup and change it again once finished)
4. The app is quite peformant on execution and it doesn't cost any added resources, compared to a potential system spec requirement for the server

**Comment by bo0tzz** [comment]
I think if we added this feature, IMO it should be on the server side and not in the app, just like all the other processing we do. That said, I don't know how I feel about it - storage is really cheap these days, so I don't see the need to be too sparing with it, and with Immich being primarily a backup type tool I expect most people would want to keep their original files.

**Comment by alextran1502** [comment]
I would echo @bo0tzz respond and and not going to merge in this feature as it is not the image we have for the direction.

Thank you for your work and I suggest next time you can join Discord and raise a question about implementing a feature that impacts the application on both the client or the server heavily on the operations and architecture wise.

Happy new year!

**Comment by aviv926** [comment]
> Here's a guide I wrote for people who want to resize images: https://gist.github.com/JamesCullum/6604e504318dd326a507108f59ca7dcd

Unfortunately [according to the developer](https://github.com/immich-app/immich/pull/1242#issuecomment-1368285255) of the project this is not a feature that will be added in the near future or at all

In my reply above, I showed how it is possible to still apply compression to details, but it seems that this is something that affects the entire library and cannot be selected per user

**Comment by shukebeta** [comment]
Based on @JamesCullum 's gist, I successfully got a working Immich instance with transparent image Resize + Compression feature. I have put my effort on https://github.com/shukebeta/immich-settings-with-transparent-compression 
Many thanks to @JamesCullum !

**Pull request closed without merging**
