### PR TITLE
feat(server): get asset by library and path

### LINKED ISSUE #4904: [Feature] Expose getByLibraryIdAndOriginalPath to controller
### Discussed in https://github.com/immich-app/immich/discussions/4352

Adding this to my own todo list, should be easy to do

<div type='discussions-op-text'>

<sup>Originally posted by **alvistar** October  5, 2023</sup>
### The feature

Hi,
following discussion on https://github.com/immich-app/immich/discussions/4279 to enable the creation of albums from a file structure without resorting to query the db, the following function:

- getByLibraryIdAndOriginalPath from asset.service.ts 

should be exposed in asset.controller.ts.

The patch should be trivial.

### Platform

- [X] Server
- [ ] Web
- [ ] Mobile</div>

### PR DESCRIPTION
**Pull request by etnoy**
Fixes #4904.

The naming of the endpoint is not set in stone

### CODE REVIEW

**Comment by jrasm91** [comment]
It is not very restful to add endpoints for every variation of asset querying. Ideally this could be merged into the "get all" endpoint.

Related, I have some unfinished code that adds a new, search by anything endpoint. It supports created, updated, trashed, asset type, id, motion, checksum, etc.

**Comment by jrasm91** [comment]
If you want I can push those changes tomorrow and we can maybe merge these two things together.

**Comment by etnoy** [comment]
> If you want I can push those changes tomorrow and we can maybe merge these two things together.

Alright, that sounds good to me!

**Comment by jrasm91** [comment]
#4931

**Comment by etnoy** [comment]
Closing in favor of #4931

**Pull request closed without merging**
