### PR TITLE
feat(web): new fonts

### PR DESCRIPTION
**Pull request by alextran1502**

### CODE REVIEW

**Review by jrasm91 — APPROVED** [review]
Did you remove the old ones?

**Comment by waclaw66** [comment]
Distrupts the scrollbar.

**Comment by waclaw66** [comment]
New font looks awesome, however there are only 4 albums in a row on 15" laptop, they have huge thumbnails, it's too much. Latest version of Immich displays 5 of them same as Google Photos .

**Comment by jrasm91** [comment]
Our official beta tester :heart:

**Pull request merged**
