### PR TITLE
feat(mobile): add new theme option to customise app primary color

### PR DESCRIPTION
**Pull request by ghost**
This pull request adds new theme options to the mobile app, allowing users to customize the appearance.

Added these color options: Indigo(default), Blue, Teal, Green, Lime, Yellow, Orange, Red, Purple, Deep purple, Blue grey, Brown.

### CODE REVIEW

**Comment by alextran1502** [comment]
Thank you so much for the contribution!

Can you help revert the change to the localization file, you only need to change for `en-US`

**Comment by pruthvi-21** [comment]
@alextran1502 I've reverted the translations.

**Comment by Me-Mr** [comment]
Very cool!

**Comment by sannidhyaroy** [comment]
Thank you for this PR. Would it be possible to have the app fetch the primary color from Material You?

**Comment by fabianbees** [comment]
> Thank you for this PR. Would it be possible to have the app fetch the primary color from Material You?

This could potentially be implemented with the flutter package dynamic_color: https://github.com/material-foundation/flutter-packages/tree/main/packages/dynamic_color

**Comment by sannidhyaroy** [comment]
> This could potentially be implemented with the flutter package dynamic_color: https://github.com/material-foundation/flutter-packages/tree/main/packages/dynamic_color

This would be pretty cool as the `dynamic_color` package, not only works for android but on other platforms as well. Although, in this case, it's only for android as this package doesn't support iOS though. Maybe, this could be useful if we ever have a Windows/macOS/Linux flutter app in the future.

**Comment by shankar-213** [comment]
> Thank you for this PR. Would it be possible to have the app fetch the primary color from Material You?

Yes it's possible. am working on that.

**Comment by shankar-213** [comment]
Made a new PR (#11560). Hence closing this.

**Comment by shankar-213** [comment]
Made a new PR (#11560). Hence closing this one.

**Pull request closed without merging**
