### PR TITLE
feat(mobile): Admin Controls Web View

### PR DESCRIPTION
**Pull request by ddshd**
- Adds WebView to manage admin functions for admin uses

TODO:
- Android Testing
- More iOS Testing
- UI Cleanup
- oAuth Admin Account Testing

Current UI:

image
image

### CODE REVIEW

**Comment by jrasm91** [comment]
Would it be better to just add a dedicated set of views instead of a web view for this functionality?

**Comment by ddshd** [comment]
> Would it be better to just add a dedicated set of views instead of a web view for this functionality?

Dedicated views would be better for UX though because of the very small number of users who would be able to access these views (likely single digit admin users for each install) it may not be worth the effort. I also foresee the the mobile views diverging from the web views as more features/options are added to the web without the mobile views being updated.

I think a webview is a good stop gap solution to give easy access to the admin controls without too much effort to develop or more importantly maintain the separate views.

If that's not the path we want to take, I'm fully open to admin controls being revisited at a later time when there are resources to keep the dedicated views maintained.

**Comment by daniele-athome** [comment]
Personally I'd advise against using a webview and instead redirect the user to a browser directly. Webviews are more of a band-aid and don't integrate well with apps IMHO.

**Comment by ddshd** [comment]
> Personally I'd advise against using a webview and instead redirect the user to a browser directly. Webviews are more of a band-aid and don't integrate well with apps IMHO.

Agreed - I'm looking into if it's possible to call the native SafariViewController or Chrome Tabs with cookies pre-set. So far it doesn't look like it's possible (at least on iOS) which is why I decided to use WebView instead.

It's still worth considering ditching this all together for dedicated views at a later time

**Comment by daniele-athome** [comment]
Sure. This is just my personal view anyway. You should probably wait for a comment by the dev team :-)

Using a web view has its use cases of course, but in this case it doesn't give a feeling of integration, but more of a container opening a webapp (so, equivalent to opening a full browser but without the features of a browser).
If the admin area would be deployed as a separate webapp (or, better the same webapp but without the navigation elements) specialized to serve only admin routes, that would probably be a candidate for a webview (waiting for the native implementation of course).

**Comment by ddshd** [comment]
> Sure. This is just my personal view anyway. You should probably wait for a comment by the dev team :-)
> 
> Using a web view has its use cases of course, but in this case it doesn't give a feeling of integration, but more of a container opening a webapp (so, equivalent to opening a full browser but without the features of a browser). If the admin area would be deployed as a separate webapp (or, better the same webapp but without the navigation elements) specialized to serve only admin routes, that would probably be a candidate for a webview (waiting for the native implementation of course).

Thank you for the input though, it's very valid.. I was able to get it to work with mobile browser with a small change on the server side.. Lmk if you think this would look better or the same..

image

**Comment by ddshd** [comment]
> Sure. This is just my personal view anyway. You should probably wait for a comment by the dev team :-)
> 
> Using a web view has its use cases of course, but in this case it doesn't give a feeling of integration, but more of a container opening a webapp (so, equivalent to opening a full browser but without the features of a browser). If the admin area would be deployed as a separate webapp (or, better the same webapp but without the navigation elements) specialized to serve only admin routes, that would probably be a candidate for a webview (waiting for the native implementation of course).

Thank you for the input though, it's very valid.. I was able to get it to work with mobile browser with a small change on the server side.. Lmk if you think this would look better or the same..

image

**Comment by daniele-athome** [comment]
I would have just opened the browser, but as I said I'm just a contributor :-) you should ping the devs on Discord on #contributing channel.

P.S. out of curiosity, what did you modify on the server for this?

**Comment by jrasm91** [comment]
I'd be fine with adding a link to the admin page in the sidebar (only visible for the admin of course).

**Comment by ddshd** [comment]
> I'd be fine with adding a link to the admin page in the sidebar (only visible for the admin of course).

Should the link open in app (Screenshot above) or take the user out of the app?

**Comment by jrasm91** [comment]
I think it can just take the user out of the app.

**Pull request closed without merging**
