### PR TITLE
chore: add more languages

### PR DESCRIPTION
**Pull request by danieldietzler**

### CODE REVIEW

**Comment by pyorot** [comment]
Serbian was already in there… where did you get your languages from? 🧐

**Comment by danieldietzler** [comment]
> Serbian was already in there… where did you get your languages from? 🧐

There were only Serbian (Cyrillic) and Serbian (Latin). Are those not different?

**Comment by pyorot** [comment]
> > Serbian was already in there… where did you get your languages from? 🧐
> 
> There were only Serbian (Cyrillic) and Serbian (Latin). Are those not different? To answer your question, we get requests to add new languages and then we do :)

I was wondering who would’ve requested Serbian then :P

> Serbian is practically the only European standard language whose speakers are fully functionally digraphic, using both Cyrillic and Latin alphabets.

Those are the language’s two writing systems, basically

**Comment by danieldietzler** [comment]
Ah I see. Are you on our discord (https://discord.immich.app) ? That'd be easier to discuss this with others who speak the language as well

**Comment by pyorot** [comment]
> Ah I see. Are you on our discord (https://discord.immich.app) ? That'd be easier to discuss this with others who speak the language as well

Yep, I’ll give you a bell

**Review by zackpollard — APPROVED** [review]

**Pull request merged**
