### PR TITLE
Add search field to people route

### PR DESCRIPTION
**Pull request by pstuermlinger**
Similar to the search field in the people-merge view, this PR introduces a search field in the people main view. By clicking on any person the search string is preserved when the user clicks the back arrow.

### CODE REVIEW

**Comment by martabal** [comment]
Hello !

What's the difference with #5703 ?

**Comment by pstuermlinger** [comment]
Hi @martabal ! Seems like you created your PR just when I started with this one :)

Mine tries to make minimal changes. Only the web is affected. Yours goes some steps further, especially on mobile and server. Maybe you can take over the feature to preserve the search string when navigating to a single person?

**Comment by martabal** [comment]
No, it does not affect the mobile. There's changes in the mobile folder because the API has been updated (I'm not a mobile dev ahah). 

Yep, keeping the search could be a nice addition

**Comment by pstuermlinger** [comment]
Closing in favor of #5703

**Pull request closed without merging**
