### PR TITLE
feat(server) add docker debug config for server

### PR DESCRIPTION
**Pull request by jrasm91**

### CODE REVIEW

**Comment by jrasm91** [comment]
image

**Comment by alextran1502** [comment]
Can you add the steps necessary to attached the debugger to this PR as documentation? 

I run the containers with `make dev` then attach the node debugger by using the config file you have and get errors message. 

image

**Comment by jrasm91** [comment]
It has to map the host filesystem to the container filesystem in launch config. I open vscode at immich/ and so the paths in the launch config just worked.

Is your workspace root something else?

**Comment by alextran1502** [comment]
> It has to map the host filesystem to the container filesystem in launch config. I open vscode at immich/ and so the paths in the launch config just worked.
> 
> Is your workspace root something else?

I believe so, the only different is that I use a VM to as the dev machine. So I SSH to the instance on the VM first then start up docker and attached the debugger. On theory it should be the same as development on the local machine

**Comment by alextran1502** [comment]
After I restart VSCode, it works :)

**Pull request merged**
