### PR TITLE
feat(web): Adds toggle to disable sorting of faces

### LINKED ISSUE #14843: Merge sort by similarity is often empty
### The bug

Trying out the new merge "sort by similarity" mentioned in v1.123.0, but it only works sometimes.

On most people, when I enter the merge page, the list of faces is just empty. I very much doubt that Immich can't find any faces close enough to display here, as it's empty even on faces where I know there are unmerged faces that should show up here. Meanwhile, on faces where it does work, the list seems to include everything, so scrolling all the way down, the faces down there have nothing in common with the merging face. So I'm pretty sure it's a bug.

### The OS that Immich Server is running on

Docker

### Version of Immich Server

v1.123.0

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### PR DESCRIPTION
**Pull request by lukasdotcom**
Adds a way to disable sorting of faces by similarity on merge screen and the detailed face view (#14635) below search bar. Keeps similarity sorting enabled as the default.

Fixes #14762
FIxes #14843

### CODE REVIEW

**Comment by alextran1502** [comment]
I think a better place for this is a toggle in the merge face interface itself

**Comment by Lukasdotcom** [comment]
@alextran1502 I was just about to ask if that would be a better choice.

**Comment by alextran1502** [comment]
Haha, like minds

**Comment by welpher** [comment]
> I think a better place for this is a toggle in the merge face interface itself

Not only in the merge face page, the detail page named face should display first

**Comment by Lukasdotcom** [comment]
You mean this screen right?
image
I added it to that one, but I probably should have updated the description of the pull request.

**Review by alextran1502 — APPROVED** [review]
Thank you, I cleaned up the logic and the UI to make the components fit in the context. I also set the sort to false by default because it causes an error that if there are no similar faces found, then no faces would be rendered

image

**Comment by welpher** [comment]
> You mean this screen right? image I added it to that one, but I probably should have updated the description of the pull request.

Yes, this screen.

**Comment by welpher** [comment]
> You mean this screen right? image I added it to that one, but I probably should have updated the description of the pull request.

Yes, in this screen named face should display first

**Pull request merged**
