### PR TITLE
chore: migrate to SvelteKit app state

### PR DESCRIPTION
**Pull request by benmccann**
bye bye stores!

### CODE REVIEW

**Review by alextran1502 — APPROVED** [review]
Thank you!

**Review by danieldietzler — APPROVED** [review]
Noice! Could you fix the package-lock file?

**Comment by benmccann** [comment]
Oh yeah. Good catch! Sorry I missed that. It's been updated now

**Comment by michelheusschen** [comment]
Any reason not to migrate the remaining `$app/stores` instances?

**Comment by benmccann** [comment]
> Any reason not to migrate the remaining $app/stores instances?

I hadn't noticed there were more. I ran the migration tool and assumed it'd found them all. I'm not by a computer at the moment, so will have to check this later

**Comment by jrasm91** [comment]
I'll merge it for now and we can always do the rest in a follow-up

**Pull request merged**
