### PR TITLE
feat(web): support 360 video (equirectangular)

### PR DESCRIPTION
**Pull request by truongsinh**
This PR addresses https://github.com/immich-app/immich/discussions/5130 and https://github.com/immich-app/immich/issues/5414 .

Microservice already does a good job of extracting `projectionType` tag. This PR only make sure to use the correct (panorama) viewer when the video has EquirectangularAdapter projectionType. Unlike 360 image, 360 video requires navbar and progress bar.

### CODE REVIEW

**Comment by alextran1502** [comment]
Hello, is there a sample video that you can attach to this PR?

**Comment by truongsinh** [comment]
> Hello, is there a sample video that you can attach to this PR?

Yes I can provide sample file. Where in the codebase should I place the file?

**Comment by truongsinh** [comment]
Anyway, meanwhile I can attach it here:


https://github.com/immich-app/immich/assets/358585/fac6f67f-996b-47a5-b2cb-29b50deaf380

**Comment by alextran1502** [comment]
Hello, can you help fix the failed web test? Thanks

**Review by alextran1502 — APPROVED** [review]

**Pull request merged**
