### PR TITLE
Draft: user deletion from web interface

### PR DESCRIPTION
**Pull request by PrivateGER**
Relates to #695 

This is a first draft, the user deletion endpoint does work and removes the user, but the other data (such as shared albums) owned by the user will need to be adjusted as well. 

The frontend will also need changes, maybe the data owned by the deleted user could be rewritten to become owned by "Deleted User" similar in a way that Discord does it.

### CODE REVIEW

**Comment by PrivateGER** [comment]
- In it's current form, this only deletes the user record. The files themselves stay, including shared albums and the files within. Should this be this way?
- The edit-user-form always seems to submit upon being closed and I don't know enough Svelte to figure out why. It doesn't mess with the actual user deletion, but does pop up the little error message thingy. Is there a way to just not submit it?

**Comment by alextran1502** [comment]
Hello @PrivateGER, thank you for taken an initiative on this issue.

My image of this feature will be a soft delete functionality. So the user will be fully deleted after 7 days along with the associated assets. During the 7 days period, the user can be restored from the Admin interface. 

I am thinking of having another column in the `users` table such as `deletedAt`. And we would write into the column when the user is deleted the timestamp. Then there will be a daily cron job to check for any user with existing info in the column and check if 7 days has passed or not before performing the actual deletion.

For the behavior of the form keep sending event, I cannot replicate it. Here is the video. Can you show how it behave differently on your environment?

https://user-images.githubusercontent.com/27055614/194157445-cbc7f57a-23c0-4e86-b60b-06735aaa35b3.mov

**Comment by bo0tzz** [comment]
@alextran1502 is this superseded by the other pr?

**Comment by PrivateGER** [comment]
It is.

**Pull request closed without merging**
