### PR TITLE
fix(machine-learning): Add the command to execute at startup

### PR DESCRIPTION
**Pull request by samip5**
Previously it wasn't set in the Docker container but it should be.

### CODE REVIEW

**Review by bo0tzz — APPROVED** [review]

**Review by bo0tzz — APPROVED** [review]

**Comment by alextran1502** [comment]
Have you tested this on a dev and production build? Can it still hot reload in dev mode?

**Comment by zackpollard** [comment]
> Have you tested this on a dev and production build? Can it still hot reload in dev mode?

This shouldn't affect the dev builds as we can still override the entrypoint manually regardless of what is in the dockerfile.

**Review by zackpollard — APPROVED** [review]

**Comment by samip5** [comment]
Okay so in theory that works, but for whatever reason it doesn't seem to find the main.py despite it being at the correct location, maybe it should be started with a script entrypoint instead that most images does it..

```
immich_machine_learning    | python: can't open file '/usr/src/app/src/main.py': [Errno 2] No such file or directory
immich_machine_learning    | python: can't open file '/usr/src/app/src/main.py': [Errno 2] No such file or directory
immich_machine_learning    | python: can't open file '/usr/src/app/src/main.py': [Errno 2] No such file or directory
```

What's your thoughts?

**Comment by alextran1502** [comment]
> Okay so in theory that works, but for whatever reason it doesn't seem to find the main.py despite it being at the correct location, maybe it should be started with a script entrypoint instead that most images does it..
> 
> ```
> immich_machine_learning    | python: can't open file '/usr/src/app/src/main.py': [Errno 2] No such file or directory
> immich_machine_learning    | python: can't open file '/usr/src/app/src/main.py': [Errno 2] No such file or directory
> immich_machine_learning    | python: can't open file '/usr/src/app/src/main.py': [Errno 2] No such file or directory
> ```
> 
> What's your thoughts?

Can you exec to the container and list out the directory? Or having the command as "ls" to double check?

**Comment by jrasm91** [comment]
I think we may really just want both arguments set in the dockerfile under CMD. No need to make python an entrypoint.

**Comment by alextran1502** [comment]
> I think we may really just want both arguments set in the dockerfile under CMD. No need to make python an entrypoint.

I can confirm that it works this way so `CMD ["python", "src/main.py"]`

**Review by jrasm91 — APPROVED** [review]

**Pull request merged**
