### PR TITLE
Update ru-RU.json

### PR DESCRIPTION
**Pull request by ygibson86**

### CODE REVIEW

**Comment by alextran1502** [comment]
Hello, this update is usually done through our translation platform. If you can send me your email, I can send you the invitation.

**Comment by ygibson86** [comment]
Hello, my email is ***@***.*** 08.02.2023, 19:01, "Alex" ***@***.***>: Hello, this update is usually done through our translation platform. If you can send me your email, I can send you the invitation.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>   -- Золотарев Константин+79376531200

**Comment by alextran1502** [comment]
Can you send me an email at 
image


GitHub doesn't show email address

**Comment by alextran1502** [comment]
Email sent

**Pull request closed without merging**
