### PR TITLE
feat(server): advanced settings for transcoding

### LINKED ISSUE #3706: [BUG] Hardware encoding not working when using HEVC (NVIDIA card)
### The bug

When selecting HEVC as the codec for transcoded videos, hardware encoding does not seem to work, and encoding seems to be done only by the CPU. However, when selecting h264 as the codec, hardware encoding works correctly with the "Video Encode" portion of the graphics card showing GPU usage.

The GPU I am using is the NVIDIA GTX 1070, and under the [NVENC GPU Support Matrix](https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new), it says that this card should be able to encode with HEVC.

NVIDIA driver version is 528.02 and I am running Windows 10 22H2 with Docker Desktop 4.22.0 (117440).

### The OS that Immich Server is running on

Windows 10 (Docker Desktop)

### Version of Immich Server

v1.73.0

### Version of Immich Mobile App

v1.73.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.yml
      service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
###################################################################################
# Database
###################################################################################

# NOTE: The following four database variables support Docker secrets by adding a *_FILE suffix to the variable name
# See the docker-compose documentation on secrets for additional details: https://docs.docker.com/compose/compose-file/compose-file-v3/#secrets
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=*
DB_DATABASE_NAME=immich

# Optional Database settings:
# DB_PORT=5432

###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=immich_redis

# REDIS_URL will be used to pass custom options to ioredis.
# Example for Sentinel
# {"sentinels":[{"host":"redis-sentinel-node-0","port":26379},{"host":"redis-sentinel-node-1","port":26379},{"host":"redis-sentinel-node-2","port":26379}],"name":"redis-sentinel"}
# REDIS_URL=ioredis://eyJzZW50aW5lbHMiOlt7Imhvc3QiOiJyZWRpcy1zZW50aW5lbDEiLCJwb3J0IjoyNjM3OX0seyJob3N0IjoicmVkaXMtc2VudGluZWwyIiwicG9ydCI6MjYzNzl9XSwibmFtZSI6Im15bWFzdGVyIn0=

# Optional Redis settings:

# Note: these parameters are not automatically passed to the Redis Container
# to do so, please edit the docker-compose.yml file as well. Redis is not configured
# via environment variables, only redis.conf or the command line

# REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_USERNAME=
# REDIS_PASSWORD=
# REDIS_SOCKET=

###################################################################################
# Upload File Location
#
# This is the location where uploaded files are stored.
###################################################################################

UPLOAD_LOCATION=O:\docker_data\immich_data


###################################################################################
# Typesense
###################################################################################
TYPESENSE_API_KEY=*
# TYPESENSE_ENABLED=false
# TYPESENSE_URL uses base64 encoding for the nodes json.
# Example JSON that was used:
# [
#      { "host": "typesense-1.example.net", "port": "443", "protocol": "https" },
#      { "host": "typesense-2.example.net", "port": "443", "protocol": "https" },
#      { "host": "typesense-3.example.net", "port": "443", "protocol": "https" },
# ]
# TYPESENSE_URL=ha://WwogIHsgImhvc3QiOiAidHlwZXNlbnNlLTEuZXhhbXBsZS5uZXQiLCAicG9ydCI6ICI0NDMiLCAicHJvdG9jb2wiOiAiaHR0cHMiIH0sCiAgeyAiaG9zdCI6ICJ0eXBlc2Vuc2UtMi5leGFtcGxlLm5ldCIsICJwb3J0IjogIjQ0MyIsICJwcm90b2NvbCI6ICJodHRwcyIgfSwKICB7ICJob3N0IjogInR5cGVzZW5zZS0zLmV4YW1wbGUubmV0IiwgInBvcnQiOiAiNDQzIiwgInByb3RvY29sIjogImh0dHBzIiB9Cl0=

###################################################################################
# Reverse Geocoding
#
# Reverse geocoding is done locally which has a small impact on memory usage
# This memory usage can be altered by changing the REVERSE_GEOCODING_PRECISION variable
# This ranges from 0-3 with 3 being the most precise
# 3 - Cities > 500 population: ~200MB RAM
# 2 - Cities > 1000 population: ~150MB RAM
# 1 - Cities > 5000 population: ~80MB RAM
# 0 - Cities > 15000 population: ~40MB RAM
####################################################################################

# DISABLE_REVERSE_GEOCODING=false
# REVERSE_GEOCODING_PRECISION=3

####################################################################################
# WEB - Optional
#
# Custom message on the login page, should be written in HTML form.
# For example:
# PUBLIC_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i>demo@demo.de</i><br>Password: <i>demo</i>"
####################################################################################

PUBLIC_LOGIN_PAGE_MESSAGE="Samuel's Secret Stash"

####################################################################################
# Alternative Service Addresses - Optional
#
# This is an advanced feature for users who may be running their immich services on different hosts.
# It will not change which address or port that services bind to within their containers, but it will change where other services look for their peers.
# Note: immich-microservices is bound to 3002, but no references are made
####################################################################################

IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003

####################################################################################
# Alternative API's External Address - Optional
#
# This is an advanced feature used to control the public server endpoint returned to clients during Well-known discovery.
# You should only use this if you want mobile apps to access the immich API over a custom URL. Do not include trailing slash.
# NOTE: At this time, the web app will not be affected by this setting and will continue to use the relative path: /api
# Examples: http://localhost:3001, http://immich-api.example.com, etc
####################################################################################

#IMMICH_API_URL_EXTERNAL=http://localhost:3001

###################################################################################
# Immich Version - Optional
#
# This allows all immich docker images to be pinned to a specific version. By default,
# the version is "release" but could be a specific version, like "v1.59.0".
###################################################################################

#IMMICH_VERSION=
```

### Reproduction steps

```bash
1. In system settings -> FFmpeg Settings, turn on hardware acceleration (using NVENC)
2. Change Video Codec to HEVC
3. Under Jobs -> Transcode Video -> Start Transcoding for ALL
4. Check Task Manager for "Video Encode" GPU Usage
```

### Additional information

Under Job Concurrency, **Transcode Videos Concurrency** is set to **2**

These are my FFmpeg settings in immich
image

Task manager when HEVC is being used
image

Task manager when AVC is being used
image

### PR DESCRIPTION
**Pull request by mertalev**
## Description

B-frames are currently handled internally in FFmpeg commands, but there are instances (particularly with hardware acceleration) where they're not supported. This PR exposes B-frames as an admin setting so users can set it according to their preference, or disable them if they find that their hardware doesn't support B-frames.

Fixes #3706

Edit: This PR now adds this setting to a new "advanced" subsection in the FFmpeg settings, along with several more niche settings that were previously hardcoded. The default for all of them is to omit these flags from the command by default, with some exceptions for hardware acceleration.

## Testing

The `-bf` flag is tested to work, but the other changes are pending testing.

### CODE REVIEW

**Review by jrasm91 — APPROVED** [review]

**Comment by alextran1502** [comment]
Looks good, let's start adding these configurations options to the advanced subsection of FFMPEG settings, since the majority of users might be confused by it

**Comment by mertalev** [comment]
I made an advanced section for some hardcoded settings, but still need to test some of the changes.

**Comment by kkoshelev** [comment]
I wonder if there is a traction for this FR. I would really like to make use of my newly purchased Tesla P4 card for hw transcoding.

**Comment by mertalev** [comment]
> I wonder if there is a traction for this FR. I would really like to make use of my newly purchased Tesla P4 card for hw transcoding.

It mainly just needs to be tested. I've been focusing more on ML improvements lately so haven't been able to look at this as much. You could help test this branch by setting your image to `ghcr.io/immich-app/immich-server:pr-3775` for `immich-server` and `ghcr.io/immich-app/immich-web:pr-3775` for `immich-web`. Setting "max bframes" to 0 should be enough for it to work on your GPU.

**Comment by kkoshelev** [comment]
> You could help test this branch by setting your image to `ghcr.io/immich-app/immich-server:pr-3775` for `immich-server` and `ghcr.io/immich-app/immich-web:pr-3775` for `immich-web`. Setting "max bframes" to 0 should be enough for it to work on your GPU.

Doesn't work, unfortunately. I wish there was an option to tweak paramaters.

```

[Nest] 8  - 08/31/2023, 5:26:49 AM     LOG [MediaService] Start encoding video 2662c529-8062-4295-b0bf-9fa17eddfcb7 {"inputOptions":["-init_hw_device cuda=cuda:0","-filter_hw_device cuda"],"outputOptions":["-tune hq","-qmin 0","-temporal-aq 1","-rc-lookahead 20","-i_qfactor 0.75","-b_qfactor 1.1","-c:v:0 hevc_nvenc","-c:a:1 aac","-movflags faststart","-fps_mode passthrough","-bf 0","-g 256","-v verbose","-vf format=nv12,hwupload_cuda","-preset p6","-cq:v 18"],"twoPass":false}
[Nest] 8  - 08/31/2023, 5:26:50 AM   ERROR [MediaRepository] ffmpeg version 6.0-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Guessed Channel Layout for Input Stream #0.1 : mono
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'upload/library/d59d3ce9-c503-4514-86f7-4c4273a9a8de/2023/2023-08-31/IMG_7985.mov':
  Metadata:
    creation_time   : 2023-08-31T05:25:37.000000Z
    com.apple.quicktime.location.accuracy.horizontal: 67.000000
    com.apple.quicktime.live-photo.auto: 1
    com.apple.quicktime.content.identifier: 40C2E79E-BA8B-4A62-A1A2-DB10F75280B9
    com.apple.quicktime.live-photo.vitality-score: 1.000000
    com.apple.quicktime.live-photo.vitality-scoring-version: 0
    com.apple.quicktime.location.ISO6709: +37.3962-121.9998+007.440/
    com.apple.quicktime.make: Apple
    com.apple.quicktime.model: iPhone 13 Pro
    com.apple.quicktime.software: 16.6
    com.apple.quicktime.creationdate: 2023-08-30T22:25:22-0700
  Duration: 00:00:02.48, start: 0.000000, bitrate: 10451 kb/s
  Stream #0:0[0x1](und): Video: hevc (Main), 1 reference frame (hvc1 / 0x31637668), yuvj420p(pc, smpte170m/smpte432/bt709, left), 1920x1440, 9684 kb/s, 29.48 fps, 29.83 tbr, 600 tbn (default)
    Metadata:
      creation_time   : 2023-08-31T05:25:37.000000Z
      handler_name    : Core Media Video
      vendor_id       : [0][0][0][0]
      encoder         : HEVC
  Stream #0:1[0x2](und): Audio: pcm_s16le (lpcm / 0x6D63706C), 44100 Hz, 1 channels, s16, 705 kb/s (default)
    Metadata:
      creation_time   : 2023-08-31T05:25:37.000000Z
      handler_name    : Core Media Audio
      vendor_id       : [0][0][0][0]
  Stream #0:2[0x3](und): Data: none (mebx / 0x7862656D), 0 kb/s (default)
    Metadata:
      creation_time   : 2023-08-31T05:25:37.000000Z
      handler_name    : Core Media Metadata
  Stream #0:3[0x4](und): Data: none (mebx / 0x7862656D), 41 kb/s (default)
    Metadata:
      creation_time   : 2023-08-31T05:25:37.000000Z
      handler_name    : Core Media Metadata
  Stream #0:4[0x5](und): Data: none (mebx / 0x7862656D), 504 kb/s (default)
    Metadata:
      creation_time   : 2023-08-31T05:25:37.000000Z
      handler_name    : Core Media Metadata
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> hevc (hevc_nvenc))
  Stream #0:1 -> #0:1 (pcm_s16le (native) -> aac (native))
Press [q] to stop, [?] for help
[graph 0 input from stream 0:0 @ 0x49c7e1c7a40] w:1920 h:1440 pixfmt:yuvj420p tb:1/600 fr:179/6 sar:0/1
[auto_scale_0 @ 0x49c7e1c2880] w:iw h:ih flags:'' interl:0
[Parsed_format_0 @ 0x49c7e1c7140] auto-inserting filter 'auto_scale_0' between the filter 'graph 0 input from stream 0:0' and the filter 'Parsed_format_0'
[swscaler @ 0x49ca0dce000] deprecated pixel format used, make sure you did set range correctly
[auto_scale_0 @ 0x49c7e1c2880] w:1920 h:1440 fmt:yuvj420p sar:0/1 -> w:1920 h:1440 fmt:nv12 sar:0/1 flags:0x00000004
[swscaler @ 0x49ca0dce000] deprecated pixel format used, make sure you did set range correctly
[auto_scale_0 @ 0x49c7e1c2880] w:1920 h:1440 fmt:yuvj420p sar:0/1 -> w:1920 h:1440 fmt:nv12 sar:0/1 flags:0x00000004
[swscaler @ 0x49ca0dce000] deprecated pixel format used, make sure you did set range correctly
[auto_scale_0 @ 0x49c7e1c2880] w:1920 h:1440 fmt:yuvj420p sar:0/1 -> w:1920 h:1440 fmt:nv12 sar:0/1 flags:0x00000004
[swscaler @ 0x49ca0dce000] deprecated pixel format used, make sure you did set range correctly
[auto_scale_0 @ 0x49c7e1c2880] w:1920 h:1440 fmt:yuvj420p sar:0/1 -> w:1920 h:1440 fmt:nv12 sar:0/1 flags:0x00000004
[hevc_nvenc @ 0x49c7e277180] Using input frames context (format cuda) with hevc_nvenc encoder.
[hevc_nvenc @ 0x49c7e277180] Loaded Nvenc version 12.1
[hevc_nvenc @ 0x49c7e277180] Nvenc initialized successfully
[hevc_nvenc @ 0x49c7e277180] Temporal AQ not supported
[hevc_nvenc @ 0x49c7e277180] Provided device doesn't support required NVENC features
[hevc_nvenc @ 0x49c7e277180] Nvenc unloaded
[vost#0:0/hevc_nvenc @ 0x49c7ecd1680] Error initializing output stream: Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
[AVIOContext @ 0x49c7e1ba040] Statistics: 0 bytes written, 0 seeks, 0 writeouts
Terminating demuxer thread 0
[AVIOContext @ 0x49c7e1b75c0] Statistics: 1522013 bytes read, 4 seeks
Conversion failed!
[Nest] 8  - 08/31/2023, 5:26:50 AM   ERROR [MediaService] Error: ffmpeg exited with code 1: Conversion failed!
[Nest] 8  - 08/31/2023, 5:26:50 AM   ERROR [MediaService] Error occurred during transcoding. Retrying with NVENC acceleration disabled.
```

**Comment by kkoshelev** [comment]
Wonder if it is possible to make use of hw HDR->SDR mapping (tonemap_cude filter) while you are making some changes.

```
$ docker exec -ti immich_microservices /bin/bash
root@2bdc7cd22cc1:/usr/src/app# for i in encoders decoders filters; do
    echo $i:; ffmpeg -hide_banner -${i} | egrep -i "npp|cuvid|nvenc|cuda"
done
encoders:
 V....D av1_nvenc            NVIDIA NVENC av1 encoder (codec av1)
 V....D h264_nvenc           NVIDIA NVENC H.264 encoder (codec h264)
 V....D hevc_nvenc           NVIDIA NVENC hevc encoder (codec hevc)
decoders:
 V..... av1_cuvid            Nvidia CUVID AV1 decoder (codec av1)
 V..... h264_cuvid           Nvidia CUVID H264 decoder (codec h264)
 V..... hevc_cuvid           Nvidia CUVID HEVC decoder (codec hevc)
 V..... mjpeg_cuvid          Nvidia CUVID MJPEG decoder (codec mjpeg)
 V..... mpeg1_cuvid          Nvidia CUVID MPEG1VIDEO decoder (codec mpeg1video)
 V..... mpeg2_cuvid          Nvidia CUVID MPEG2VIDEO decoder (codec mpeg2video)
 V..... mpeg4_cuvid          Nvidia CUVID MPEG4 decoder (codec mpeg4)
 V..... vc1_cuvid            Nvidia CUVID VC1 decoder (codec vc1)
 V..... vp8_cuvid            Nvidia CUVID VP8 decoder (codec vp8)
 V..... vp9_cuvid            Nvidia CUVID VP9 decoder (codec vp9)
filters:
 ... bilateral_cuda    V->V       GPU accelerated bilateral filter
 ... chromakey_cuda    V->V       GPU accelerated chromakey filter
 ... colorspace_cuda   V->V       CUDA accelerated video color converter
 ... hwupload_cuda     V->V       Upload a system memory frame to a CUDA device.
 ... overlay_cuda      VV->V      Overlay one video on top of another using CUDA
 ... scale_cuda        V->V       GPU accelerated video resizer
 ... thumbnail_cuda    V->V       Select the most representative frame in a given sequence of consecutive frames.
 ... tonemap_cuda      V->V       GPU accelerated HDR to SDR tonemapping
 T.. yadif_cuda        V->V       Deinterlace CUDA frames
```

**Comment by mertalev** [comment]
Hmm, I guess I'll add that to the advanced section. I'd like to make Pascal work OOTB since it's still very common, so I'll set the defaults accordingly.

> **Wonder if it is possible to make use of hw HDR->SDR mapping (tonemap_cude filter) while you are making some changes.

The plan is to eventually add support for hardware decoding and tone-mapping, but I'd like to iron out the encoding side first. Given these settings are all very hardware-dependent (as you've seen), taking it one step at a time makes it easier to know what works and what doesn't.

**Comment by kkoshelev** [comment]
Thanks! I'm happy to try out changes. Please ping me once the updated docker image is pushed.

**Comment by mertalev** [comment]
@kkoshelev The updated version is up and should "just work". Could you try it out?

**Comment by kkoshelev** [comment]
This time I see an extra "-map" flag, which I didn't see before.

```
[Nest] 7  - 09/02/2023, 6:55:00 AM     LOG [MediaService] Start encoding video 36f4eeae-275f-4e6a-a8b0-6f875fc07200 {"inputOptions":["-init_hw_device cuda=cuda:0","-filter_hw_device cuda"],"outputOptions":["-tune hq","-qmin 0","-rc-lookahead 20","-i_qfactor 0.75","-c:v hevc_nvenc","-c:a aac","-movflags faststart","-fps_mode passthrough","-map 0:v:0","-map 0:a:1","-bf 0","-g 256","-v verbose","-vf format=nv12,hwupload_cuda","-preset p6","-cq:v 18"],"twoPass":false}
[Nest] 7  - 09/02/2023, 6:55:00 AM   ERROR [MediaRepository] ffmpeg version 6.0-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Guessed Channel Layout for Input Stream #0.1 : mono
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'upload/library/d59d3ce9-c503-4514-86f7-4c4273a9a8de/2023/2023-09-02/IMG_7990.mov':
  Metadata:
    creation_time   : 2023-09-02T06:53:13.000000Z
    com.apple.quicktime.location.accuracy.horizontal: 35.000000
    com.apple.quicktime.live-photo.auto: 1
    com.apple.quicktime.content.identifier: F00B0D60-605E-4FE2-AEC4-58A0FFF4287F
    com.apple.quicktime.make: Apple
    com.apple.quicktime.model: iPhone 13 Pro
    com.apple.quicktime.software: 16.6
    com.apple.quicktime.creationdate: 2023-09-01T23:53:03-0700
  Duration: 00:00:02.78, start: 0.000000, bitrate: 11405 kb/s
  Stream #0:0[0x1](und): Video: hevc (Main), 1 reference frame (hvc1 / 0x31637668), yuvj420p(pc, smpte170m/smpte432/bt709, left), 1920x1440, 10648 kb/s, 29.53 fps, 29.83 tbr, 600 tbn (default)
    Metadata:
      creation_time   : 2023-09-02T06:53:13.000000Z
      handler_name    : Core Media Video
      vendor_id       : [0][0][0][0]
      encoder         : HEVC
    Side data:
      displaymatrix: rotation of -90.00 degrees
  Stream #0:1[0x2](und): Audio: pcm_s16le (lpcm / 0x6D63706C), 44100 Hz, 1 channels, s16, 705 kb/s (default)
    Metadata:
      creation_time   : 2023-09-02T06:53:13.000000Z
      handler_name    : Core Media Audio
      vendor_id       : [0][0][0][0]
  Stream #0:2[0x3](und): Data: none (mebx / 0x7862656D), 0 kb/s (default)
    Metadata:
      creation_time   : 2023-09-02T06:53:13.000000Z
      handler_name    : Core Media Metadata
  Stream #0:3[0x4](und): Data: none (mebx / 0x7862656D), 34 kb/s (default)
    Metadata:
      creation_time   : 2023-09-02T06:53:13.000000Z
      handler_name    : Core Media Metadata
  Stream #0:4[0x5](und): Data: none (mebx / 0x7862656D), 504 kb/s (default)
    Metadata:
      creation_time   : 2023-09-02T06:53:13.000000Z
      handler_name    : Core Media Metadata
Stream map '0:a:1' matches no streams.
To ignore this, add a trailing '?' to the map.
[AVIOContext @ 0x36a4e1b75c0] Statistics: 1575178 bytes read, 4 seeks
[Nest] 7  - 09/02/2023, 6:55:00 AM   ERROR [MediaService] Error: ffmpeg exited with code 1: 
[Nest] 7  - 09/02/2023, 6:55:00 AM   ERROR [MediaService] Error occurred during transcoding. Retrying with NVENC acceleration disabled.
[Nest] 7  - 09/02/2023, 6:55:00 AM   ERROR [MediaRepository] ffmpeg version 6.0-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Guessed Channel Layout for Input Stream #0.1 : mono
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'upload/library/d59d3ce9-c503-4514-86f7-4c4273a9a8de/2023/2023-09-02/IMG_7990.mov':
  Metadata:
    creation_time   : 2023-09-02T06:53:13.000000Z
    com.apple.quicktime.location.accuracy.horizontal: 35.000000
    com.apple.quicktime.live-photo.auto: 1
    com.apple.quicktime.content.identifier: F00B0D60-605E-4FE2-AEC4-58A0FFF4287F
    com.apple.quicktime.make: Apple
    com.apple.quicktime.model: iPhone 13 Pro
    com.apple.quicktime.software: 16.6
    com.apple.quicktime.creationdate: 2023-09-01T23:53:03-0700
  Duration: 00:00:02.78, start: 0.000000, bitrate: 11405 kb/s
  Stream #0:0[0x1](und): Video: hevc (Main), 1 reference frame (hvc1 / 0x31637668), yuvj420p(pc, smpte170m/smpte432/bt709, left), 1920x1440, 10648 kb/s, 29.53 fps, 29.83 tbr, 600 tbn (default)
    Metadata:
      creation_time   : 2023-09-02T06:53:13.000000Z
      handler_name    : Core Media Video
      vendor_id       : [0][0][0][0]
      encoder         : HEVC
    Side data:
      displaymatrix: rotation of -90.00 degrees
  Stream #0:1[0x2](und): Audio: pcm_s16le (lpcm / 0x6D63706C), 44100 Hz, 1 channels, s16, 705 kb/s (default)
    Metadata:
      creation_time   : 2023-09-02T06:53:13.000000Z
      handler_name    : Core Media Audio
      vendor_id       : [0][0][0][0]
  Stream #0:2[0x3](und): Data: none (mebx / 0x7862656D), 0 kb/s (default)
    Metadata:
      creation_time   : 2023-09-02T06:53:13.000000Z
      handler_name    : Core Media Metadata
  Stream #0:3[0x4](und): Data: none (mebx / 0x7862656D), 34 kb/s (default)
    Metadata:
      creation_time   : 2023-09-02T06:53:13.000000Z
      handler_name    : Core Media Metadata
  Stream #0:4[0x5](und): Data: none (mebx / 0x7862656D), 504 kb/s (default)
    Metadata:
      creation_time   : 2023-09-02T06:53:13.000000Z
      handler_name    : Core Media Metadata
Stream map '0:a:1' matches no streams.
To ignore this, add a trailing '?' to the map.
[AVIOContext @ 0x419bc250180] Statistics: 1575178 bytes read, 4 seeks
[Nest] 7  - 09/02/2023, 6:55:00 AM   ERROR [JobService] Unable to run job handler: Error: ffmpeg exited with code 1: 
[Nest] 7  - 09/02/2023, 6:55:00 AM   ERROR [JobService] Error: ffmpeg exited with code 1: 
    at ChildProcess.<anonymous> (/usr/src/app/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
[Nest] 7  - 09/02/2023, 6:55:00 AM   ERROR [JobService] Object:
{
  "id": "36f4eeae-275f-4e6a-a8b0-6f875fc07200"
}
```

**Comment by mertalev** [comment]
Yeah, that's from another fix I included here too. There was a bug in it that I fixed, so the updated version shouldn't have that error.

**Comment by kkoshelev** [comment]
Works for hvec now.

```
[Nest] 7  - 09/02/2023, 9:02:39 PM     LOG [MediaService] Start encoding video 65a5f439-e5f1-458e-938e-40714987dc1f {"inputOptions":["-init_hw_device cuda=cuda:0","-filter_hw_device cuda"],"outputOptions":["-tune hq","-qmin 0","-rc-lookahead 20","-i_qfactor 0.75","-c:v hevc_nvenc","-c:a aac","-movflags faststart","-fps_mode passthrough","-map 0:0","-map 0:1","-bf 0","-g 256","-v verbose","-vf format=nv12,hwupload_cuda","-preset p6","-cq:v 18"],"twoPass":false}
[Nest] 7  - 09/02/2023, 9:02:41 PM     LOG [MediaService] Encoding success 65a5f439-e5f1-458e-938e-40714987dc1f
```

**Review by alextran1502 — APPROVED** [review]

**Pull request merged**
