### PR TITLE
feat(web) add asset count stats on admin page (#843)

### PR DESCRIPTION
**Pull request by zkhan93**
addresses part of #393
implements asset count stats on admin page in a new section called "Server Stats",
if we agree that the direction I'm taking is correct then I would like to implement per user storage here as well.

image

### CODE REVIEW

**Comment by zkhan93** [comment]
apparently I would need some suggestion on the design.

**Comment by alextran1502** [comment]
Looks good to me. Once you have all the data available on the frontend, let me know and I will whip up a design for the page.

**Comment by bo0tzz** [comment]
Looking good! I do have one nit about the API: Rather than a specific `assetCount` endpoint, I think a general stats one would be a better fit here for when more stats are added. Maybe something under the existing server-info, like `/api/server-info/stats`.

**Comment by zkhan93** [comment]
size: sum of size of all the files in the user directory
object: this is just the count of files in the user directory
videos: aggregated count from database based on asset type column
photos: aggregated count from database based on asset type column

size and objects are calculated using `fs` module to loop over the user directory to collect size and count of all files, this way we included thumbnails and other additional files if any in user directory.

I want someone to confirm the way I accessed AssetRepo in ServerInfoService.

**Comment by alextran1502** [comment]
> I want someone to confirm the way I accessed AssetRepo in ServerInfoService.

The way you access the AssetRepo is correct. Thank you for the PR. I will review in detail later today. Do you want to include the UI work in this PR or you want to do it in a separate PR?

**Comment by zkhan93** [comment]
if everything else is ok, I would like to get a simple UI table in this PR itself

**Comment by alextran1502** [comment]
> if everything else is ok, I would like to get a simple UI table in this PR itself

Let's do that then. I can modified the design later if needed.

**Comment by zkhan93** [comment]
added UI
Screenshot 2022-10-23 at 2 12 04 PM

**Comment by alextran1502** [comment]
Can you allow this branch to be pushed update from the maintainer? I fixed a few things

**Comment by zkhan93** [comment]
not sure how to do that, however I did check this 

Screenshot 2022-10-23 at 4 47 36 PM

which allows adding commit to this PR. is that what you are looking for ?

**Comment by alextran1502** [comment]
> not sure how to do that, however I did check this
> 
> Screenshot 2022-10-23 at 4 47 36 PM
> 
> which allows adding commit to this PR. is that what you are looking for ?

Correct but for some reason I cannot push it to your branch, no big deal, I can create a new branch after merge your branch in

**Pull request merged**
