### PR TITLE
Improve backup UX

### PR DESCRIPTION
**Pull request by xethlyx**
This attempts to fix these issues/improve these features:

- [x] Backup file information is permanently visible, even when not backing up
- [x] HTTP errors in backups cause invisible errors to the user
- [x] Malformed error responses cause invisible errors to the user (e.g. file too large errors from a reverse proxy)
- [x] If an error occurs in the last asset in a manual backup, then the backup UI would never finish
- [x] Improve UX of manual backup

No longer planned (I was not aware that background backups gave error notifications):
- ~~Display background backup errors in the UI~~
- ~~Add a notifier on the main screen on the backup icon if any backups failed~~

Some considerations:
* Should users be prompted about the newly detected HTTP errors? Someone could be running Immich only in their local network, so should they need to be notified if an upload failed while they were roaming?

UI Screenshots:

image
image
image
image
image

This is currently a work-in-progress and I will be updating this description as I work.

### CODE REVIEW

**Comment by xethlyx** [comment]
Almost done, just stuck on this layout problem now: https://github.com/immich-app/immich/pull/8533/files#diff-c00a7c028bb7ba1ec21f707165486dea93043cf04d556a7a753f5a589507a3d8R342

**Comment by Chaphasilor** [comment]
I'd suggest giving the user a way to enable automatic backup along with the "Automatic backup is disabled" message. The button could say something like "Change backup settings" or even "Enable automatic backup" and would then do the same as clicking the gear icon at the top.

**Comment by zackpollard** [comment]
Hey, the fixes in this PR look promising. For the UI I think we like the approach but will probably want to make some further changes to get it more in-line with the design of the rest of the app. For the non-UI changes, are those ready to go? What else is needed to get this PR into a state ready for review? Cheers!

**Comment by xethlyx** [comment]
Hi, the only other change that's needed right now I believe is just to fix some of my UI hacks: https://github.com/immich-app/immich/pull/8533/files#diff-c00a7c028bb7ba1ec21f707165486dea93043cf04d556a7a753f5a589507a3d8R343

**Comment by alextran1502** [comment]
I am closing this as it is now stale and need a lot of UI work to adapt with Immich's design language. Thanks for the idea, I will definitely return to this UI work

**Pull request closed without merging**
