### PR TITLE
Provide instructions of how to specify a default timezone

### PR DESCRIPTION
**Pull request by mmomjian**
We should specify to the user how to enter their timezone as an env var.

### CODE REVIEW

**Comment by mmomjian** [comment]
Sort of a followup to this - how is `/etc/localtime` vs `TZ` handled? I had /etc/localtime mounted but I had some images that would not get the correct timezone until I added the `TZ` env var as well.

**Comment by etnoy** [comment]
Having localtime mounted should be equivalent to the TZ env var. We had th TZ method documented before switching over to the localtime volume method which is more reliable. Are you sure there was a difference? If you remove the TZ method and rerun metadata extraction, does the problem come back, and on which assets?

**Comment by mmomjian** [comment]
> Having localtime mounted should be equivalent to the TZ env var. We had th TZ method documented before switching over to the localtime volume method which is more reliable. Are you sure there was a difference? If you remove the TZ method and rerun metadata extraction, does the problem come back, and on which assets?

I don't want to play on my primary instance but I will be starting up a second instance in the next week or two for testing purposes, and I will run some tests there.

**Comment by etnoy** [comment]
I'm closing this for now, feel free to reopen when you did your tests

**Pull request closed without merging**
