### PR TITLE
Minor improvements to the detail-panel component

### PR DESCRIPTION
**Pull request by matthinc**
This PR contains three improvements of the details-panel component:

- Floor the exposure time as the current implementation can result in very long numbers (see attached image)
- Add a popup to the map-marker that shows the location in the lat,lon format (useful e.g. to copy the location to google maps)
- Refactor some duplicated map-related code to a separate function

immich01

### CODE REVIEW

**Comment by alextran1502** [comment]
Thank you for the PR. With this current change, the map doesn't redraw/change the marker when you change /navigate through the assets when the panel is opened.

```svelte

	export let asset: ImmichAsset;
	$: {
		// Redraw map
		if (map && leaflet) {
			map.removeLayer(marker);
			map.setView([asset.exifInfo?.latitude || 0, asset.exifInfo?.longitude || 0], 17);
			marker = leaflet.marker([asset.exifInfo?.latitude || 0, asset.exifInfo?.longitude || 0]);
			map.addLayer(marker);
		}
	}
```

The `$` right below the property `export let asset: ImmichAsset;` indicates that whenever the `asset` change, then run the reactive logic in the `{}` block

**Comment by matthinc** [comment]
Thanks for the explanation - I'm not very familiar with svelte. I force-pushed to my latest commit and moved it to the correct line.

**Comment by alextran1502** [comment]
No problem, here is a better explaination. The `{}` block only run if you include the `reactive property` which is `asset` in this case. Here is how I would do the refactor

```svelte

	export let asset: ImmichAsset;
	$: if (asset.exifInfo) {
		drawMap(asset.exifInfo.latitude, asset.exifInfo.longitude);
	}

	onMount(async () => {
		if (browser) {
			if (asset.exifInfo) {
				await drawMap(asset.exifInfo.latitude, asset.exifInfo.longitude);
			}
		}
	});

	async function drawMap(lat: number, lon: number) {
		if (!leaflet) {
			// @ts-ignore
			leaflet = await import('leaflet');
		}

		if (!map) {
			map = leaflet.map('map');
			leaflet
				.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
					attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',
				})
				.addTo(map);
		}

		if (marker) {
			map.removeLayer(marker);
		}

		map.setView([lat || 0, lon || 0], 17);

		marker = leaflet.marker([lat || 0, lon || 0]);
		marker.bindPopup(`${lat || 0},${lon || 0}`);
		map.addLayer(marker);
	}
```


I hope this helps, and let me know if you have any problem.

**Comment by matthinc** [comment]
Again, thank you very much for the explanation. I applied your suggestion to the PR and it seems to work fine.

**Pull request merged**
