### PR TITLE
chore(docs): refactor pages

### PR DESCRIPTION
**Pull request by jrasm91**
Update the organization of the docs.

### CODE REVIEW

**Comment by alextran1502** [comment]
FYI 
image

**Comment by alextran1502** [comment]
I think the Post Install Steps now force the user to click many times instead of a coherent place to follow the flow of the application. Is there a better way to structure this information?

**Comment by jrasm91** [comment]
Sounds good. I'm not sure what the best way to do it is. I can put back the content into a single page if you think that is better. To me it seemed like there was quite a bit of overlap with some features that deserved their own page with more details and it didn't seem like a great idea to have too much content duplicated/copied in multiple places.

We could have a "short" version of the steps like you had it before and longer "detail" versions on their own pages like we do now. Then link to those from the shorter sections in the post install steps.

**Comment by alextran1502** [comment]
> We could have a "short" version of the steps like you had it before and longer "detail" versions on their own pages like we do now. Then link to those from the shorter sections in the post install steps.

This works!

**Comment by jrasm91** [comment]
Ended up just moving the different sections into a common file that could be imported in both places :+1:.

**Pull request merged**
