### PR TITLE
docs: Document admin-only library change

### PR DESCRIPTION
**Pull request by etnoy**
Is to be merged after the next release in order to document admin-only libraries

Relevant changes are in #7237

### CODE REVIEW

**Comment by jrasm91** [comment]
I'm not sure what this PR is, but it includes lots of non-doc changes. Can you update it to only include changes to the `docs/` folder?

**Comment by etnoy** [comment]
> I'm not sure what this PR is, but it includes lots of non-doc changes. Can you update it to only include changes to the `docs/` folder?

I based this pr on #7237, as soon as that is merged this will make more sense

**Comment by jrasm91** [comment]
Yes, it is true you can 

> > I'm not sure what this PR is, but it includes lots of non-doc changes. Can you update it to only include changes to the `docs/` folder?
> 
> I based this pr on #7237, as soon as that is merged this will make more sense

That's kind of annoying IMO, but I guess it is fine. I will mark it as draft since there isn't anything to be done until there's a usable diff.

**Comment by etnoy** [comment]
Will fix better PR tomorrow

**Pull request closed without merging**
