### PR TITLE
Add integration tests for the login process

### PR DESCRIPTION
**Pull request by matthinc**

### CODE REVIEW

**Comment by matthinc** [comment]
@alextran1502 Flutter tests are now called `mobile-unit-tests` and `mobile-integration-tests`, I think you have to update the required statuses

**Comment by alextran1502** [comment]
> @alextran1502 Flutter tests are now called `mobile-unit-tests` and `mobile-integration-tests`, I think you have to update the required statuses

Done

**Comment by alextran1502** [comment]
But maybe only applicable after merging this PR?

**Comment by matthinc** [comment]
Closed and re-created beacause of CI problems.

**Pull request closed without merging**
