### PR TITLE
chore(web): font changes and refinement

### PR DESCRIPTION
**Pull request by alextran1502**
Overpass font has the limitation of a font height mismatch when used with a logo, which causes an unpleasant look. The font is also on the thin side, and some users complain about its readability. 

The new font is "Be Vietnam Pro" which has characteristics similar to those of Google Sans fonts. It is easier to read, and the characters are displayed clearly.

The new font also has a softer touch to the interface, while Overpass font has a more technical, rigid feel

Some screenshots of the new fonts

### Server info

| Immich | the other app |
| - | - |
|image| image |

### Job card
image

### Info panel

| Immich | the other app |
| - | - |
|image| image |

### Album cards

image

### Usage with logo

| Immich | the other app |
| - | - |
|image| image |

### CODE REVIEW

**Review by jrasm91 — APPROVED** [review]
I don't know if I _love_ the font, but the spacing definitely is better.

**Comment by alextran1502** [comment]
> I don't know if I _love_ the font, but the spacing definitely is better.

Fair, I have been trying with the font on my instance for a few months. I think it is a bit wide, but overall, maybe the best option after Overpass tne the previous font

**Comment by alextran1502** [comment]
@Tyree, I am curious about what you think about this font.

**Comment by Tyree** [comment]
I agree this is much better than the original font. Much easier to read, less awkward, and is "friendlier." The round, single-storey "a" is usually a good indicator of the font author's intent to soften things up.
What's your pool? Google Fonts?

Fonts are just one of those things that get into the realm of subjective real quick. I think this one is objectively better in every way than previous. Is it THE best choice? Maybe not (again, probably subjective). I'm not sure it's worth your time to beat the bushes for an even better choice at this point. Maybe it's something you revisit down the road when more of your wish list is accomplished. (Though I'm sure this sort of update can be a nice change of pace over staring at lives of code.)

I think this one is a fine choice, even if it doesn't end up being a permanent one.

Apologies for rambling. I'm writing this on my phone at 4am and letting my insomnia win. 😄
I'm glad to look at this closer if you feel it's warranted. Let me know how I can help.

**Comment by crash123** [comment]
nó trông rất tuyệt

**Comment by alextran1502** [comment]
@Tyree Thank you for the input, and no worry about the rambling at all 😄 My pool right now is Google Fonts, but I am open to looks elsewhere that can be used for the app

**Review by danieldietzler — APPROVED** [review]
I actually like this font. It's easy on the eyes and has a nice, modern look imo :)

**Review by michelheusschen — COMMENTED** [review]
Looks good and I find it easier to read. However, can we use woff2 format instead of ttf?

**Comment by waclaw66** [comment]
I like the original Overpass font more at the first impression, but I give a chance to the new one.

**Pull request closed without merging**
