### PR TITLE
feat(web): improve and refactor thumbnails

### LINKED ISSUE #958: [BUG] [WEB] Video previews in Gridview keep downloading, even if they are not visible anymore (reopen)
**Describe the bug**
If I scroll through my assets and hover over an video, it starts to download and preview it, which is a great feature.

The Prolbem is, that it does not stop to download the video, even, if I scrolled away from that video, which makes previewing images very slow, since it blocks my bandwidth.

**To Reproduce**
1. I installed Immich through docker-compose
2. Placed an Nginx reverse proxy for ssl in front of it.
3. Upload assets from my phone
4. In Web: Hover over an video and scroll down. Keep an eye on networktraffic of my machine.

**Expected behavior**
The download of the video stops, as soon as I stop hovering with my mouse over an video (or at least as soon, as it is no longer visible in the browser through scrolling.

**Screenshots**

**System**
- Server Version: `<1.35>`
- Mobile App Version: `<1.35>`

**Additional context**
Browser is Firefox on MacOS 13

This is a reopened Ticket for  #875

### LINKED ISSUE #1944: [BUG] When selecting a video, the border disappears when hovering the video on web
### The bug

When I select a video in the browser and I hover over it, the border that marks the selected item, disappears.

### The OS that Immich Server is running on

Synology DSM 7.2

### Version of Immich Server

v1.50.1

### Version of Immich Mobile App

v1.50.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy

services:
  immich-server:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    networks:
      - traefik_proxy
      - default
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - sockets:/sockets
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always
    labels:
      traefik.enable: "true"
      traefik.docker.network: traefik_proxy
      traefik.http.services.immich-api-svc.loadbalancer.server.port: "3001"
      traefik.http.routers.immich-api-rtr.rule: "Host(`immich.$DOMAINNAME`) && Pathprefix(`/api`)"
      traefik.http.routers.immich-api-rtr.priority: 20
      traefik.http.middlewares.immich-api-strip.stripprefix.prefixes: "/api"
      traefik.http.routers.immich-api-rtr.middlewares: immich-api-strip,chain-basic@file
      traefik.http.routers.immich-api-rtr.service: immich-api-svc
      traefik.http.routers.immich-api-rtr.tls: true
      traefik.http.routers.immich-api-rtr.tls.certresolver: dns-cloudflare
      traefik.http.routers.immich-api-rtr.entrypoints: https

  immich-microservices:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    networks:
      - default
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - sockets:/sockets
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    build:
      context: $DOCKERDIR/immich/immich-ml
      dockerfile: Dockerfile
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    networks:
      - default
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - database
    restart: always

  immich-web:
    image: altran1502/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    networks:
      - default
      - traefik_proxy
    env_file:
      - .env
    restart: always
    labels:
      traefik.enable: "true"
      traefik.docker.network: traefik_proxy
      traefik.http.services.immich-svc.loadbalancer.server.port: "3000"
      traefik.http.routers.immich-rtr.rule: "Host(`immich.$DOMAINNAME`)"
      traefik.http.routers.immich-rtr.priority: 10
      traefik.http.routers.immich-rtr.service: immich-svc
      traefik.http.routers.immich-rtr.middlewares: chain-basic@file
      traefik.http.routers.immich-rtr.tls: true
      traefik.http.routers.immich-rtr.tls.certresolver: dns-cloudflare
      traefik.http.routers.immich-rtr.entrypoints: https

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always
    networks:
      - default
    command: redis-server /etc/redis.conf
    volumes:
      - sockets:/sockets
      - $DOCKERDIR/immich/redis.conf:/etc/redis.conf
      - /etc/TZ:/etc/timezone:ro
      - $DOCKERDIR/immich/redisdb:/db

  database:
    container_name: immich_postgres
    image: postgres:14-bullseye
    user: 1026:100
    command: postgres -c unix_socket_directories='/var/run/postgresql/,/sockets/'
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
      PGPORT: ${DB_PORT}
    volumes:
      - $DOCKERDIR/immich/pgdata:/var/lib/postgresql/data
      - sockets:/sockets
    restart: always

volumes:
  sockets:
    external: true
```

### Your .env content

```Shell
DB_HOSTNAME=/sockets
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich
DB_PORT=5433
REDIS_PASSWORD="redispassword"
REDIS_SOCKET=/sockets/immich_redis.sock
UPLOAD_LOCATION=/uploads
JWT_SECRET=jwtsecret
REVERSE_GEOCODING_PRECISION=3
```

### Reproduction steps

```bash
1. Select a video in the browser.
2. Hover over the video with your cursor.
3. See error
```

### Additional information

Recording of the issue:
(Download the video and play it in VLC if it's not playable in the browser, because it's HEVC)

https://user-images.githubusercontent.com/47184046/222965467-dfd80384-e401-49bf-a1be-579a87c740b6.mp4

### PR DESCRIPTION
**Pull request by michelheusschen**
The following changes are made:
- Shrink the whole thumbnail when selected, except for the select button
- Improved animation when selecting thumbnail
- Allow video playback while the thumbnail is selected
- Provide methods on the API class for getting file and thumbnail URLs
- Show error icon when video loading fails
- Live photos would only play when hovering the top right icon, now plays when hovering anywhere (same as video)

And the following bugs are fixes:
- Selection border disappears when hovering video thumbnail, fixes #1944
- Video duration with less than 10 seconds would appear as `0:5` instead of `0:05`
- Video duration shows incorrectly for some duration before this was merged #2058
- Cancel video buffering when not hovering thumbnail anymore. Potentially fixes #958, might need validation

Currently there's some detection for horizontal and vertical asset orientation and sets the height/width accordingly. But I don't think exif data is actually present in a lot of cases and I'm not certain orientations like `Rotate 90 CW` are valid. Anyway, that still needs to be looked into further, but that's probably for a future PR.

### CODE REVIEW

**Comment by alextran1502** [comment]
> Live photos would only play when hovering the top right icon, now plays when hovering anywhere (same as video)

This is the intended behavior for LivePhoto to play when hover on the icon

**Comment by michelheusschen** [comment]
> > Live photos would only play when hovering the top right icon, now plays when hovering anywhere (same as video)
> 
> This is the intended behavior for LivePhoto to play when hover on the icon

I understand, that's why I noted it as a change rather than a fix. Hovering over the icon to start playing live photos feels unintuitive to me, that's why I changed it. If you want however, it can be reverted.

**Comment by alextran1502** [comment]
> > > Live photos would only play when hovering the top right icon, now plays when hovering anywhere (same as video)
> 
> > 
> 
> > This is the intended behavior for LivePhoto to play when hover on the icon
> 
> 
> 
> I understand, that's why I noted it as a change rather than a fix. Hovering over the icon to start playing live photos feels unintuitive to me, that's why I changed it. If you want however, it can be reverted.

Yes please, I would like to treat it as a normal photo, the motion part is extra and only run when you specifically want to

**Comment by jrasm91** [comment]
Looks good!

**Review by jrasm91 — APPROVED** [review]
Looks good!

**Pull request merged**
