### PR TITLE
chore(server,mobile): remove device info entity

### PR DESCRIPTION
**Pull request by jrasm91**
Merge after #1526.

### CODE REVIEW

**Comment by jrasm91** [comment]
@alextran1502 or @fyfrey - there are some references to `DeviceTypeEnum` in the mobile codebase that need to be migrated. The enum no longer exists in the open-api specification (no references to it). Can this be replaced with a local enum instead?

**Comment by fyfrey** [comment]
> @alextran1502 or @fyfrey - there are some references to `DeviceTypeEnum` in the mobile codebase that need to be migrated. The enum no longer exists in the open-api specification (no references to it). Can this be replaced with a local enum instead?

Maybe we can simply delete all that? Or do we now need this for the active devices? I guess we don't need the enum in the app at all..

**Comment by jrasm91** [comment]
It was unclear to me. There were some places it was being used so I figured I'd ask the pros. If you have time can you fix it in this PR @fyfrey?

**Comment by alextran1502** [comment]
Don't we want to drop the `device_info` table as well?

**Comment by jrasm91** [comment]
Good point. Let me add a migration for it.

**Pull request merged**
