### PR TITLE
refactor(web): disable shortcut when writting

### PR DESCRIPTION
**Pull request by martabal**
Following https://github.com/immich-app/immich/pull/4053#discussion_r1321408726

### CODE REVIEW

**Review by jrasm91 — COMMENTED** [review]
Looks a lot better. I think we have had variations of this issue on different pages, and some of them use different solutions as well. Can you find all places where we use `document.addEventListener` to handle keyboard shortcuts and make sure this new if(disableKeyboard(event)) { return }` is used on all of them?

To me, `shouldDisableShortcut` sounds like the keyboard shortcuts should become "disabled", which makes me think they need to be re-enabled in the future. In reality this is just checking the source of the event and determining if it applies to shortcuts or not (whether it should be handled or skipped). Something like `isKeyboardShortcut(event)` or `shouldIgnoreShortcut(event)` makes more sense to me.

**Comment by martabal** [comment]
Yes `shouldIgnoreShortcut()` is a lot better !

**Review by jrasm91 — APPROVED** [review]
Nice! Looks good to me. Did you test all the shortcuts still work and all the text boxes input fields also still work?

**Comment by martabal** [comment]
Yes, everything works as expected.

**Review by alextran1502 — APPROVED** [review]

**Pull request merged**
