### PR TITLE
feat(server,web): server config

### LINKED ISSUE #3994: [BUG] `oauth.buttonText` is not taken into account
### The bug

In the log-in screen, the OAuth button text setting is not taken into account anymore.
The settings UI allows to change it, but its not reflected in the login screen. Previous versions worked as expected.

### The OS that Immich Server is running on

Cloudron

### Version of Immich Server

v1.77.0

### Version of Immich Mobile App

does not apply

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
does not apply
```

### Your .env content

```Shell
does not apply
```

### Reproduction steps

```bash
1. Setup OAuth
2. Change button text
3. Open Login view
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jrasm91**
Fixes #3994

In this PR:
- Add map settings to admin UI
- Add option to change the tile map server url
- Expose non-boolean config via a new endpoint `GET /server-info/config`, which can be used with `GET /server-info/features`. Maybe merge the two endpoints in the future?
- Expose `oauth.buttonText`, so it can be used (again) on the login page
- Move the login page message to server config. In the future this can be saved/set in admin settings as well.
- Sort admin settings alphabetically

Tested scenarios:
- Disable map, map tab disappears in sidebar (after a refresh), map is hidden in the detail panel
- Set custom OAuth button text, view it in on the login page

Future plans:
- Use websockets to emit changes in feature flags / configurations
- Add new admin setting option for login page message (instead of env variable)
- Add more e2e tests to verify system config / server config is working correctly.

### CODE REVIEW

**Comment by bo0tzz** [comment]
Related: #3866

**Comment by alextran1502** [comment]
Why do we want to set the map as a configurable option?

**Comment by jrasm91** [comment]
Well, we want to eventually make it possible to use alternative map providers for sure and having that configuration be in these settings seemed like a logical place for it. Specifically letting users use their own tile server or a paid one should now be possible.

Since I was adding that, I thought I might as well make it possible to disable it entirely, consistent with the rest of the feature related settings like machine learning, etc.

**Comment by alextran1502** [comment]
Thank you for working on this PR. One thing I notice is that when map is disabled, you can still access the map view with `/map` path

**Comment by jrasm91** [comment]
Oh, nice catch. I'll take a look at that.

**Comment by jrasm91** [comment]
@alextran1502 - it will redirect to the photos page in this situation now.

When a setting is changed (like the map one), should I add code to auto-load the feature flags? Or should we wait until we have websockets to push that change instead? I was thinking of waiting. Do you have a preference?

**Comment by alextran1502** [comment]
@jrasm91 We can wait until websocket. Feel free to merge if there is nothing else you want to add

**Review by alextran1502 — APPROVED** [review]

**Pull request merged**
