### PR TITLE
feat(web): loop video thumbnails

### PR DESCRIPTION
**Pull request by lukashass**
Feels a lot more natural IMO.

### CODE REVIEW

**Review by zackpollard — APPROVED** [review]

**Comment by alextran1502** [comment]
so it will loop like a gif?

**Comment by zackpollard** [comment]
LGTM, seems like a nice change

> so it will loop like a gif?

Yea it will just play again once it ends, LGTM

**Comment by Krolitian** [comment]
What if we have it enable looping only after clicking the restart button at the end of a video, and then it loops endlessly? It lets people enable looping videos without an additional toggle and lets other people not have their videos loop by default.

**Review by jrasm91 — APPROVED** [review]
We could also add this to a user setting (whether to auto-loop videos or not) and then just reference the store here.

**Pull request merged**
