### PR TITLE
Add service provider

### PR DESCRIPTION
**Pull request by xpwmaosldk**
The service doesn't seem to need multiple instances.
So I let the Riverpod manage the instances.
Later, I plan to change to lazy loading and better chaining(in Riverpod way).

### CODE REVIEW

**Comment by xpwmaosldk** [comment]
I'm Riverpod newbie, so I don't know if it's the wrong way

**Comment by alextran1502** [comment]
Your implementation is great! I like it. I think this is Riverpod's way to manage instances. The original implementation philosophy is that I put everything that handles UI's state changes as a Provider. Anything related to business logic changes that don't require UI change as a Service. 

The only thing I think we can change is to change ref.watch to ref.read when getting the provider of a service, since the service doesn't change 

```dart
final assetServiceProvider =
    Provider((ref) => AssetService(ref.watch(networkServiceProvider)));

**Comment by alextran1502** [comment]
Is this branch ready to merge? I see you keep pushing more changes to it. Let me know

**Comment by xpwmaosldk** [comment]
Oh, Sorry I forget branch.
It's done.

**Pull request merged**
