### PR TITLE
fix(web): album list padding

### PR DESCRIPTION
**Pull request by waclaw66**
Album properties are missaligned to their column headers.

### CODE REVIEW

**Comment by jrasm91** [comment]
Can you add screenshots to the description of before and after?

**Comment by waclaw66** [comment]
before:
obrazek

after:
obrazek

**Comment by waclaw66** [comment]
What's wrong with the formatting check?

**Comment by jrasm91** [comment]
Run `npm run format:fix` in the web directory.

**Review by alextran1502 — APPROVED** [review]

**Pull request merged**
