### PR TITLE
fix(server): search for terms separated by hyphens and/or underscores in asset search

### PR DESCRIPTION
**Pull request by ochen1**

### CODE REVIEW

**Review by jrasm91 — COMMENTED** [review]
You will have to change line 3 to be version 9.

**Comment by ochen1** [comment]
Done! @jrasm91

**Comment by daniele-athome** [comment]
Can underscore really be a token separator in natural language? If I understand the purpose of this change correctly.

**Comment by ochen1** [comment]
This PR originates from Discord and attempts to fix searching by file names, which are typically not considered natural language. For example, I should be able to search MyName and get the result "123_MyName_Last-1.png"

Similar naming conventions are pretty standard for photography companies. Space is a character that should be avoided in filenames.

I don't believe this will cause any problems with other use cases?

**Comment by daniele-athome** [comment]
Thank you, I wasn't thinking about filenames.

**Review by alextran1502 — APPROVED** [review]

**Pull request merged**
