### PR TITLE
feat/docker-build: clean-up and permission checks

### PR DESCRIPTION
**Pull request by PixelJonas**
This PR improves no multiple topics during the docker build

- add LICENSE file to the images
- use non-root user for server, microservices, and machine-learning
- ensure non-root user has to write permissions to all app-folders
- add clean-up after package installation

Signed-off-by: PixelJonas <5434875+PixelJonas@users.noreply.github.com>

### CODE REVIEW

**Comment by PixelJonas** [comment]
I've tested the images locally, can someone else confirm, that it's working on their machine as well?

**Comment by bertmelis** [comment]
I know nothing about Dockers privileges but I assume this is a breaking change at least for Podman users. This will make the images run full rootless (albeit you add node to the root group) and the ownership of the uploaded files will be different.

Not something that can't be overcome but there is a minor gotcha: at this moment the node user has uid 1000 (from the base image). If they for some reason decide to change this, it will break Immich for Podman users.

**Comment by PixelJonas** [comment]
@bertmelis can you explain why it will break for podman users? I developed it using podman and did not encounter any issues 🤔 Only thing I could imagine is permissions on the library files (if they were created using `root` and are now inaccessible by the `node` user.

I opted to use the `node` user and give him the `root` group, so that if they change the userID of `node` there shouldn't be any issues as all we also allow `group` the same permissions as `user`.

**Comment by bertmelis** [comment]
Nevermind, I had a moment of confusion. The base image already has the 'node' user.

**Comment by alextran1502** [comment]
@PixelJonas  Shoot, I forgot, if you forked it then it can't be pushed to the Dockerhub. Would it be possible for you to create a new branch directly from main now that you have permission?

I would like to test this in the production environment to make sure things are ok in the Docker world.

**Comment by alextran1502** [comment]
@PixelJonas Can we open a branch directly from a repo with this change for a new PR? I would like to formerly test this before a release in a production environment

**Pull request closed without merging**
