### PR TITLE
fix(mobile): use a valid OAuth callback URL

### LINKED ISSUE #2932: [BUG] OAuth login wouldn't get redirected on tablet android devices
### The bug

According to our discussion, i'm opening this issue. I have 3 Android tablet devices at home from which none is able to login with OAuth. After i enter correct URL as target server and click `Login with OAuth` (and in case of having multiple google accounts log in, selecting correct google account), Chrome embeded browser will just close (as it should) and Immich will show the initial screen with target server URL again without properly log me in.

It only happens on tablet devices, not mobile-format one. I've tested it on Android 13, 11 and 7.1.1. I've also did same test on emulated android tablet device and there it worked perfectly. In fact, i've been able to log in with Android 11 tablet device once after disabling `Blokada 5` (which is Ad-blocking app for android). Then i logged off and tried the same thing with having Blokada turned on. After this weird bug appearing again, i turned off the Blokada again and tried the login process. Yet the behavior didn't change unexpectedly.

### The OS that Immich Server is running on

Ubuntu Server 22.04 LTS

### Version of Immich Server

v1.63.0 (first time spotted on v1.62.0)

### Version of Immich Mobile App

1.63.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "com.centurylinklabs.watchtower.enable=false"
    depends_on:
      - redis
      - database
      - typesense
    networks:

      - immich
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    depends_on:
      - redis
      - database
      - typesense
    networks:
      - immich
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /home/docker/docker_immich/model-cache:/cache
    env_file:
      - stack.env
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    networks:
      - immich
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - stack.env
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    networks:
      - immich
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.0
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    logging:
      driver: none
    volumes:
      - /home/docker/docker_immich/tsdata:/data
    networks:
      - immich
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    networks:
      - immich
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - stack.env
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      - immich
    volumes:
      - /home/docker/docker_immich/pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
      - "traefik.enable=true"
      - "traefik.http.routers.immich-local.rule=Host(`immich.local.example.eu`)"
      - "traefik.http.routers.immich-local.entrypoints=web, websecure"
      - "traefik.http.routers.immich-local.tls=true"
      - "traefik.http.routers.immich-local.tls.certresolver=cloudflare"
      - "traefik.http.routers.immich-local.tls.domains[0].main=local.example.eu"
      - "traefik.http.routers.immich-local.tls.domains[0].sans=*.local.example.eu"
      - "traefik.http.routers.immich.entrypoints=web, websecure"
      - "traefik.http.routers.immich.rule=Host(`immich.services.example.eu`)"
      - "traefik.http.routers.immich.tls=true"
      - "traefik.http.routers.immich.tls.certresolver=staging"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - immich
    ports:
      - 2283:8080
    depends_on:
      - immich-server
    restart: always

networks:
  immich:
  proxy:
    external: true
```

### Your .env content

```Shell
DB_HOSTNAME=redacted
DB_USERNAME=redacted
DB_PASSWORD=redacted
DB_DATABASE_NAME=redacted
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=/mnt/Backups/immich
TYPESENSE_API_KEY=redacted
PUBLIC_LOGIN_PAGE_MESSAGE="It works!"
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
TZ=Europe/Bratislava
```

### Reproduction steps

```bash
1. Deploy Immich v1.63.0 with Google OAuth
2. Login with mobile-format android device (Working fine)
3. Login with tablet-format android device (Redirecting issue)
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by qrkourier**
> [!WARNING]
> ## Breaking changes
>
> Replace `app.immich:/` with `app.immich:///oauth-callback` as the Redirect URIs in your OAuth provider settings

I get the expected result with the APK build on my Pixel 6 Pro w/ Android 14. Resolves #2932 

To test, I used an Auth0 generic web app with allowed callback `app.immich:///`, which represents a request for the root `/` resource from `app.immich` with a standard `://` separator between scheme and resource.

It's my first contribution so I'll be orienting myself to testing norms after I see what fires off with this submission.

Happy to iterate on this. It will be a breaking change for anyone using mobile OAuth. The fix for them is to modify their IdP to allow callback `app.immich:///`. If they're using the mobile callback override URI then it might go unnoticed if `app.immich:/` was successfully launching the app and concluding the login flow. It's not clear to me whether this is currently broken for everyone.

### CODE REVIEW

**Comment by qrkourier** [comment]
:thinking: I've got some unexpected localization edits in there. Maybe upstream history changed. I'll reconcile those.

**Review by qrkourier — COMMENTED** [review]
I've reverted the unexpected changes.

**Comment by alextran1502** [comment]
FYI, in the future, for mobile translation, you only need to modify the `en-US.json` file

**Comment by zackpollard** [comment]
You have some prettier failures, if you could fix those then we can look at this PR

**Comment by qrkourier** [comment]
@zackpollard :volleyball:

**Comment by alextran1502** [comment]
Hello, circle back on this. Can you let me know which device you have tested on?

**Review by jrasm91 — APPROVED** [review]

**Comment by qrkourier** [comment]
> Hello, circle back on this. Can you let me know which device you have tested on?

Hi @alextran1502,  I tested my changes with a Pixel 6 Pro running Android 14 with Auth0 identity provider. This allowed the OAuth login flow to succeed, whereas it had always failed for me before. The symptom was the Immich Android app would launch but remain logged out.

I can't explain why OAuth login works for some Android devices _without_ this change or why it still fails on some Android tablet devices _despite_ this change, as reported by @Pheggas in the associated Issue.

**Review by danieldietzler — APPROVED** [review]

**Comment by jrasm91** [comment]
Changed the url to `app.immich:///oauth-callback` so we use use different activity filters in the future. I also did confirm the third `/` is needed to `oauth-callback` to be considered a `path` instead of path of the host/port (authority).

**Pull request merged**
