### PR TITLE
add env_file to all docker services for timezone consistency

### PR DESCRIPTION
**Pull request by cwallace**
This PR adds env_file to all Docker containers to ensure timezone settings are consistent throughout the stack. By centralizing the environment configurations, we avoid any potential issues caused by mismatched timezones between services.

### CODE REVIEW

**Comment by bo0tzz** [comment]
The redis container definitely isn't involved in any (user-facing) timezone stuff.

I'm not all too stoked about just blanket passing all the env vars to containers that don't need them. If the Postgres container can meaningfully make use of the TZ env var then we should pass it explicitly instead.

**Comment by jrasm91** [comment]
Feel free to add environment entries to specific containers but we're not going to add the env to any other container.

**Comment by Phlogi** [comment]
@bo0tzz and @jrasm91 The env_file entry is missing on latest release on the database service: https://github.com/immich-app/immich/blob/v1.118.0/docker/docker-compose.yml

Why? Please re-apply this change.

**Comment by bo0tzz** [comment]
What do you mean re-apply? The PR was closed and we didn't add this change.

**Pull request closed without merging**
