### PR TITLE
fix(server): empty tag responses should be considered valid

### LINKED ISSUE #2883: [BUG] Tags generated but not stored
### The bug

I'm deploying machine learning container on a separate machine.  I have set up the addresses and ports and everything seems to work right, I can see on the dockecr logs of the machine learning containers how things are happening: `
```
INFO:     10.253.0.1:45650 - "POST /image-classifier/tag-image HTTP/1.1" 200 OK
INFO:     10.253.0.1:45660 - "POST /image-classifier/tag-image HTTP/1.1" 200 OK
INFO:     10.253.0.1:45638 - "POST /image-classifier/tag-image HTTP/1.1" 200 OK
INFO:     10.253.0.1:45668 - "POST /image-classifier/tag-image HTTP/1.1" 200 OK
INFO:     10.253.0.1:45640 - "POST /image-classifier/tag-image HTTP/1.1" 200 OK
INFO:     10.253.0.1:45618 - "POST /image-classifier/tag-image HTTP/1.1" 200 OK
INFO:     10.253.0.1:45690 - "POST /image-classifier/tag-image HTTP/1.1" 200 OK
INFO:     10.253.0.1:45706 - "POST /image-classifier/tag-image HTTP/1.1" 200 OK
INFO:     10.253.0.1:45712 - "POST /image-classifier/tag-image HTTP/1.1" 200 OK
INFO:     10.253.0.1:45726 - "POST /image-classifier/tag-image HTTP/1.1" 200 OK
INFO:     10.253.0.1:45632 - "POST /image-classifier/tag-image HTTP/1.1" 200 OK
```
However after all assets are tagged, If I press the button "missing" (tag missisng assets) it again tags runs for all of them.

I have also checked the database and the `tags` and `tag_asset` seems empty
```
immich=# SELECT * FROM tags;
 id | type | name | userId | renameTagId 
----+------+------+--------+-------------
(0 rows)

immich=# SELECT * FROM tag_asset;
 assetsId | tagsId 
----------+--------
(0 rows)

immich=# 
```

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

v1.62.1

### Version of Immich Mobile App

v1.62.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
on the machine leaerning server:

version: "3.8"

services:
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    ports:
      - 3003:3003
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

on the main server
```
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    ports:
      - 3001:3001
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

      #  immich-machine-learning:
      #    container_name: immich_machine_learning
      #    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
      #    volumes:
      #      - model-cache:/cache
      #    env_file:
      #      - .env
      #    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    ports:
      - 3000:3000
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    logging:
      driver: none
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```
```


### Your .env content

```Shell
###################################################################################
# Database
###################################################################################

# NOTE: The following four database variables support Docker secrets by adding a *_FILE suffix to the variable name
# See the docker-compose documentation on secrets for additional details: https://docs.docker.com/compose/compose-file/compose-file-v3/#secrets
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich

# Optional Database settings:
# DB_PORT=5432

###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=immich_redis

# Example for Sentinel
# {"sentinels":[{"host":"redis-sentinel-node-0","port":26379},{"host":"redis-sentinel-node-1","port":26379},{"host":"redis-sentinel-node-2","port":26379}],"name":"redis-sentinel"}
# REDIS_URL=***

# Optional Redis settings:

# Note: these parameters are not automatically passed to the Redis Container
# to do so, please edit the docker-compose.yml file as well. Redis is not configured
# via environment variables, only redis.conf or the command line

# REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_USERNAME=
# REDIS_PASSWORD=
# REDIS_SOCKET=

###################################################################################
# Upload File Location
#
# This is the location where uploaded files are stored.
###################################################################################

UPLOAD_LOCATION=/mnt/user/Media/immich

###################################################################################
# Typesense
###################################################################################
TYPESENSE_API_KEY=***
# TYPESENSE_ENABLED=false
# TYPESENSE_URL uses base64 encoding for the nodes json.
# Example JSON that was used:
# [
#      { "host": "typesense-1.example.net", "port": "443", "protocol": "https" },
#      { "host": "typesense-2.example.net", "port": "443", "protocol": "https" },
#      { "host": "typesense-3.example.net", "port": "443", "protocol": "https" },
# ]
# TYPESENSE_URL=***
###################################################################################
# Reverse Geocoding
#
# Reverse geocoding is done locally which has a small impact on memory usage
# This memory usage can be altered by changing the REVERSE_GEOCODING_PRECISION variable
# This ranges from 0-3 with 3 being the most precise
# 3 - Cities > 500 population: ~200MB RAM
# 2 - Cities > 1000 population: ~150MB RAM
# 1 - Cities > 5000 population: ~80MB RAM
# 0 - Cities > 15000 population: ~40MB RAM
####################################################################################

# DISABLE_REVERSE_GEOCODING=false
# REVERSE_GEOCODING_PRECISION=3

####################################################################################
# WEB - Optional
#
# Custom message on the login page, should be written in HTML form.
# For example:
# PUBLIC_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i>demo@demo.de</i><br>Password: <i>demo</i>"
####################################################################################

PUBLIC_LOGIN_PAGE_MESSAGE="Welcome to my self-hosted <a href=\"https://documentation.immich.app/\">Immich</a> instance, a FOSS replacement of Google Photos."

####################################################################################
# Alternative Service Addresses - Optional
#
# This is an advanced feature for users who may be running their immich services on different hosts.
# It will not change which address or port that services bind to within their containers, but it will change where other services look for their peers.
# Note: immich-microservices is bound to 3002, but no references are made
####################################################################################

IMMICH_WEB_URL=http://immich_web:3000
IMMICH_SERVER_URL=http://immich_server:3001
IMMICH_MACHINE_LEARNING_URL=http://10.253.0.8:3003


####################################################################################
# Alternative API's External Address - Optional
#
# This is an advanced feature used to control the public server endpoint returned to clients during Well-known discovery.
# You should only use this if you want mobile apps to access the immich API over a custom URL. Do not include trailing slash.
# NOTE: At this time, the web app will not be affected by this setting and will continue to use the relative path: /api
# Examples: http://localhost:3001, http://immich-api.example.com, etc
####################################################################################

#IMMICH_API_URL_EXTERNAL=http://localhost:3001

###################################################################################
# Immich Version - Optional
#
# This allows all immich docker images to be pinned to a specific version. By default,
# the version is "release" but could be a specific version, like "v1.59.0".
###################################################################################

#IMMICH_VERSION=
```

### Reproduction steps

```bash
1. deploy machine learning on separate machine
2. run tag assets
3. no tags
...
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mertalev**
## Description

This PR changes the handling of empty tag responses so they're treated the same as non-empty responses. 

The current behavior is problematic in two ways:

1. It can lead to the same images being processed whenever a "missing" job is run. This is because if none of the tags pass the score threshold for an image, then the `tags` field of an asset's `smartInfo` always stays null.
2. If the response for an image changes (by raising the score threshold, changing the model, etc.), stale tags are not removed if the new response is an empty tag response. The behavior I would expect is to replace them with the new set of tags, even if this means the image no longer has any tags associated with it.

## Testing

For these steps to be meaningful, they need to be done in an environment where at least some of the images haven't run tagging yet. Otherwise, it's possible for all images to already have tags beforehand.

1. Set `MACHINE_LEARNING_MIN_TAG_SCORE=1.0` in the ML environment. This is to ensure that all responses are empty. 
2. Run "all" for "tag objects" in the job dashboard.
3. Run "without" for "tag objects" in the job dashboard.

Step 3 should not query for any images as all of them should be considered completed.

Fixes #2883, #2888

### CODE REVIEW

**Comment by alextran1502** [comment]
I think the issue is the query was considering the `object` column in the `smart_info` table. Since we remove object detection, they won't be populate anymore

**Comment by mertalev** [comment]
I noticed the `objects` property but it doesn't seem to be used in `getWithout`. The relevant section only looks at `tags`:
```
case WithoutProperty.OBJECT_TAGS:
        relations = {
          smartInfo: true,
        };
        where = {
          resizePath: Not(IsNull()),
          isVisible: true,
          smartInfo: {
            tags: IsNull(),
          },
        };
        break;
```

**Review by jrasm91 — APPROVED** [review]

**Comment by klejejs** [comment]
@mertalev thank you for the PR. Regarding the #2888, would it also be possibe to do the same for the face recognition job?

**Comment by mertalev** [comment]
> @mertalev thank you for the PR. Regarding the #2888, would it also be possibe to do the same for the face recognition job?

This is a little more complicated because faces are stored differently and `getWithout` handles them differently as well. It's doable, but I'd have to look deeper into it.

**Pull request merged**
