### PR TITLE
feat(cli): server-info command prints url and user email

### PR DESCRIPTION
**Pull request by mio-19**
I have multiple accounts on the server and I forget which account was logged in from time to time.

### CODE REVIEW

**Comment by JW-CH** [comment]
Can you fix the formatter issues?

**Comment by jrasm91** [comment]
There are a few other things wrong with this, but I can take care of them. I've changed the output to look like this instead. I assume that is fine:


```
immich server-info
Server Info (via jrasm91@gmail.com)
  Url: http://127.0.0.1:2283/api
  Version: 1.99.0
  Image Types: 3fr,ari,arw,avif,bmp,cap,cin,cr2,cr3,crw,dcr,dng,erf,fff,gif,heic,heif,hif,iiq,insp,jpe,jpeg,jpg,jxl,k25,kdc,mrw,nef,orf,ori,pef,png,psd,raf,raw,rw2,rwl,sr2,srf,srw,svg,tif,tiff,webp,x3f
  Video Types: 3gp,avi,flv,insv,m2ts,m4v,mkv,mov,mp4,mpg,mts,webm,wmv
  Statistics:
    Images: 8
    Videos: 0
    Total: 8
```

**Comment by jrasm91** [comment]
@mio-19 if you allow contributors to push to your repository, I have fixed all the issues and it can be merged.

**Comment by mio-19** [comment]
> @mio-19 if you allow contributors to push to your repository, I have fixed all the issues and it can be merged.

I don't know how to configure github to allow this. Maybe I can pull your changes or open a new PR

**Comment by jrasm91** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by mio-19** [comment]
> https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

I am using an org to hold my forks so the guide for repos under personal account doesn't apply

**Comment by jrasm91** [comment]
Moved to #8307.

**Pull request closed without merging**
