### PR TITLE
fix(web): trash link wrongly wrapped

### LINKED ISSUE #4585: [BUG] Trash link inside another link in web app navigation
### The bug

Web app has a trash link that is nested into archive link.

Simplified scenario;
```
<a href="...">
      <div>Archive...</div>
      <a href="...">
          <div>Trash</div>
      </a>
</a>
```

Screenshot:
Demo page with dev tools that reveal same situation as in the simplified scenario (link inside link)

We need to move Trash out of Archive.

### The OS that Immich Server is running on

All

### Version of Immich Server

Latest

### Version of Immich Mobile App

Latest|

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
NA
```

### Your .env content

```Shell
NA
```

### Reproduction steps

```bash
1. open https://demo.immich.app/photos
2. check #sidebar that includes Archive link and Trash link
3. open developer tools and inspect Archive link
...
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by BogdanCerovac**
Fix #4585

### CODE REVIEW

**Comment by jrasm91** [comment]
Can you name your titles with a conventional commit message?

**Comment by BogdanCerovac** [comment]
@jrasm91 - sorry, just found that I made multiple small fixes and improvements that are related to other things.

Do I need to make separate pull requests or is it OK considering how small they are?

**Comment by jrasm91** [comment]
A single PR with a variety of related small fixes is fine.

**Review by jrasm91 — APPROVED** [review]
LGTM

**Pull request merged**
