### PR TITLE
fix(web): scrollbar not showing year

### PR DESCRIPTION
**Pull request by alextran1502**
Before & After

<p>
 

</p>

### CODE REVIEW

**Review by jrasm91 — APPROVED** [review]

**Comment by waclaw66** [comment]
This PR causes showing less years than previously...
|before|after|
|-|-|
|obrazek|obrazek|

Btw. the original font looks better IMHO.

**Comment by alextran1502** [comment]
@waclaw66 I changed the font so that the text has a fixed width for consistency. Regarding the logic, it is to prevent cases like this 
image

**Comment by waclaw66** [comment]
@alextran1502 I understand, however there are still missing a plenty of year labels in my case above.

**Comment by alextran1502** [comment]
@waclaw66 yeah this is the best I could think of how to handle these scenarios based on the nature of the variation of the year position on the timeline. Do you have any proposal?

**Comment by waclaw66** [comment]
I would consider counting sum of `segment.height` to render year label when it's far enought from the previous one.

**Pull request merged**
