### PR TITLE
(server) Allow setting the host address for the server & microservices

### PR DESCRIPTION
**Pull request by yparitcher**
Default to listen on all interfaces as per the current behavior.

### CODE REVIEW

**Comment by alextran1502** [comment]
What problem, issue are you trying to solve with this additional option?

**Comment by yparitcher** [comment]
> What problem, issue are you trying to solve with this additional option?

Sorry,
The node.js default is to listen on all interfaces, so anyone on rhe network can access immich. This PR allow me to have immich only listen on localhost, (and only be accessed through my reverse proxy) for better security. (I have immich installed on bare-metal, not with docker).

The only way to change this is by passing a host argument to app.listen, there are no env flags that node will use to change it's behavior.

**Comment by bo0tzz** [comment]
I was under the impression that it's already possible to pass the host with eg `SERVER_PORT="127.0.0.1:3001"`, have you tried that?

**Comment by yparitcher** [comment]
I did not, but in https://github.com/immich-app/immich/blob/3c7f70ec303fbf81da4e49a79c20a836e351dcc8/server/src/main.ts#L33 we explicitly set port to a number, so i doubt that will work
```
  const port = Number(process.env.SERVER_PORT) || 3001;
```

Thanks for the quick reply :)

**Review by jrasm91 — APPROVED** [review]

**Pull request merged**
