### PR TITLE
feat(mobile): use app without storage permission

### LINKED ISSUE #1905: [BUG] Can not use the mobile app on Android without the storage permission.
### The bug

Now with v1.50.1 it is not possible to use the android app without granting the storage permission. I use immich as an archive of old family photos. I do not want my personal phone photos showing up in the mobile app. Previously you could deny the storage permission and immich would only show photos from the server. Please allow the old behavior or add a setting to not display local photos in the timeline. 

### The OS that Immich Server is running on

Docker

### Version of Immich Server

v1.50.1

### Version of Immich Mobile App

v1.50.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
NA
```

### Your .env content

```Shell
NA
```

### Reproduction steps

```bash
1. Open the app
2. Be given only the option to allow local storage or logout
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by fyfrey**
fixes #1905

### Changes with this PR

- app is usable without granting storage/photo/video/asset/gallery etc. permissions
- permission is not asked during app startup but only when opening backup screen
- can use app without selecting a single backup album
- no more need for the workaround "create a new device album with a single asset in it and select it" 
- after removing the last backup album, a) all backup tasks are canceled and disabled, b) all local assets&albums are removed from the DB (all merged assets become remote-only)
- expensive `_updateBackupAssetCount` is not executed on every album selection change; it's now only executed once after making any number of album selections and returning to the main backup screen. This makes the album selection process a lot faster/snappier on some devices
- backup screen shows only the "select album for backup" card if no album is selected

### Screenshots

**After tap on backup button:**
image
If the user taps "Back" or navigates back otherwise, the previous page is shown again (e.g. home or library)

**Initial backup screen without any selected albums:**
image

**Select album screen without any selected album is now possible:**
image

**After selecting at least 1 album:**
image

### CODE REVIEW

**Comment by alextran1502** [comment]
Hi @fyfrey, can you help rebasing the PR?

**Comment by fyfrey** [comment]
> Hi @fyfrey, can you help rebasing the PR?

Sure! Already done :)

**Comment by alextran1502** [comment]
Hi Fynn, thank you for the PR. This will help a lot of use cases that don't want to upload anything from the phone.

There are two issues that I am seeing

1. In the album selection screen, selecting/deselecting the album doesn't update the unique asset number on that screen.
2. This issue has been there for a while, but I am bringing this up to this PR since it seems relatable. After selecting album(s) from the backup screen, returning to the Photos page doesn't trigger the index/rebuild until you pull the refresh. Are you seeing the same thing?

**Comment by fyfrey** [comment]
> 1. In the album selection screen, selecting/deselecting the album doesn't update the unique asset number on that screen.

Can we simply remove this information from the screen? It's still shown if the user goes back to the main backup screen. If not, we are back to computing this **very** expensive number (takes multiple seconds for large numbers of assets) on each tap.

> 2. This issue has been there for a while, but I am bringing this up to this PR since it seems relatable. After selecting album(s) from the backup screen, returning to the Photos page doesn't trigger the index/rebuild until you pull the refresh. Are you seeing the same thing?

I'll take a look. I guess this simply needs to trigger a refresh of the device assets/albums after coming back from the backup album selection screen.

**Comment by alextran1502** [comment]
> Can we simply remove this information from the screen? It's still shown if the user goes back to the main backup screen. If not, we are back to computing this very expensive number (takes multiple seconds for large numbers of assets) on each tap.

@fyfrey, yes that is fine, let's remove it

**Review by alextran1502 — APPROVED** [review]

**Pull request merged**
