### PR TITLE
fix(server): individual shared link not showing thumbnail

### PR DESCRIPTION
**Pull request by alextran1502**

### CODE REVIEW

**Comment by alextran1502** [comment]
@jrasm91 Can you help explain why when the property `resized` of the Asset's response is false then the thumbnail cannot be rendered?

**Review by jrasm91 — APPROVED** [review]

**Comment by jrasm91** [comment]
Ask me tomorrow

**Comment by alextran1502** [comment]
@jrasm91 it is now tomorrow

**Comment by jrasm91** [comment]
#11983

**Pull request closed without merging**
