### PR TITLE
Offer the same album sorting options on mobile as on web

### PR DESCRIPTION
**Pull request by agross**
I've added the "Most recent photo" and "Last modified" options to the album list.

There is a quirk regarding the API which only returns `lastModifiedAssetTimestamp` for `/api/albums`, but not `/api/albums/:id`. This could be fixed.

Since the `lastModifiedAssetTimestamp` is nullable safe comparisons are ...not easy.

I'm not a Dart developer by trade but found my way around. If you have any comments, please let me know. I've debugged this through to the best of my knowledge.

### CODE REVIEW

**Comment by alextran1502** [comment]
Hello, you only need to add translation key to the EN_US json file, the other files will eventually be autogenerated

**Comment by agross** [comment]
@alextran1502 I wasn’t aware of that. Should I change something?

**Comment by alextran1502** [comment]
You can revert the changes of all the other languages beside the english file

**Comment by alextran1502** [comment]
The changes to other language will need to be done over the Localizely platform

**Comment by agross** [comment]
OK, better now?

**Comment by agross** [comment]
Can I please get a CI build?

**Comment by agross** [comment]
Do I need to request CI builds on a commit-by-commit basis?

**Comment by jrasm91** [comment]
They don't run automatically for first time contributors.

**Comment by agross** [comment]
How get I get this closer to production?

**Comment by agross** [comment]
Anyone?

**Comment by jrasm91** [comment]
Alex is on vacation and he is one of only a few mobile developers. I don't think there is anything for you to do besides just wait a bit longer unfortunately.

**Comment by waclaw66** [comment]
There is still missing option to sort albums chronologically. That is most likely option "Most recent photo" - albums with the most recent photos, not most recently edited photos. If a single photo is edited by some graphics app a replaced within an old album, it immediately appers above albums with much newer photos. Please fix that.

**Review by alextran1502 — APPROVED** [review]

**Comment by agross** [comment]
Thanks!

**Pull request merged**
