### PR TITLE
fix(cli): `--ignore` getting ignored

### PR DESCRIPTION
**Pull request by mertalev**
## Description

The internal typing for this flag expects `exclusionPatterns`, so it will always consider it to be `undefined`.

## How Has This Been Tested?

Tested that it actually ignores the pattern specified in the command.

### CODE REVIEW

**Review by jrasm91 — APPROVED** [review]
Can you add an e2e test for this?

**Comment by mertalev** [comment]
It turns out there was more than one issue here:
- `--ignore` has confusing behavior: it's sensitive to the order of the flags (particularly whether it comes before or after the upload path(s)) because it can take multiple arguments. The behavior is predictable if it can only accept one string.
- The behavior is different when a search pattern has `..`: it ignores the `--ignore` flag in this case. Resolving the path fixes this.
- Lastly, the `glob` library still failed to ignore files even with the above changes. `fast-glob` does behave as expected. As a nice bonus, it seems something else depends on `fast-glob` anyway so replacing `glob` with it shrunk the build by about 65kb.

**Review by danieldietzler — APPROVED** [review]

**Review by jrasm91 — APPROVED** [review]

**Comment by TransRapid** [comment]
immich upload -n -i **/Recently/** -r /media/Vault/Apple\ iCloud\ Photos/7/iCloud\ Photos\ Part\ 68\ of\ 68/
Crawling for assets...
Checking files | ████████████████████████████████████████ | 100% | ETA: 0s | 2/2 assets
Found 2 new files and 0 duplicates
Would have uploaded 2 assets (9.5 MB)

Expected behavior would be 0 assets as the only 2 things are in a folder titled. _Recently Deleted_

**Comment by danieldietzler** [comment]
The CLI does not randomly ignore folders because of their name. And IMO that's a good thing, in case that's what you're referring to @TransRapid

**Comment by TransRapid** [comment]
No, the issue is the `--ignore` just does not work as described . The ignore pattern does not ignore using the CLI, it does however work using the GUI.

**Comment by mertalev** [comment]
Can you confirm that you're actually using a CLI build that has the fixes in this PR? It isn't in the latest CLI release.

**Comment by macross5** [comment]
Do we know when the fix will be released?

**Comment by JustABoringUser** [comment]
Tried with the most recent release of CLI tool but --ignore patterns do not work as soon as I add more than just a single pattern.

Works:
`docker exec -it immich_server immich upload --ignore **/*.arw --recursive "import_ds218/pics"`

Nothing of this works:
`docker exec -it immich_server immich upload --ignore **/*.{arw,dng} --recursive "import_ds218/pics"`

`docker exec -it immich_server immich upload --dry-run --ignore **/*.arw **/*.dng --recursive "import_ds218/pics"`

`docker exec -it immich_server immich upload --dry-run --recursive "import_ds218/pics" --ignore **/*.{arw,dng}`

`docker exec -it immich_server immich upload --dry-run --recursive "import_ds218/pics" --ignore **/*.arw **/*.dng`

**Comment by mertalev** [comment]
That's because multiple `--ignore` patterns isn't supported. But you can use any pattern that [micromatch](https://github.com/micromatch/micromatch) supports, including [extglobs](https://github.com/micromatch/micromatch?tab=readme-ov-file#extglobs).

**Comment by mmvr65** [comment]
@mertalev Can you give a command line example how to exclude *.nef and *.raw please ?
I can't figure out how to put it together.
Thanks in advance.
Mike

**Pull request merged**
