### PR TITLE
fix(web): Uses asset exif info for desc in asset viewer

### LINKED ISSUE #4073: [BUG] Image description missing on shared album
### The bug

I have added descriptions to images in my library. Then I created a share link for the library (including all perms, exif, upload, download). But the images don't have a description when viewing that shared album. For guests it shows nothing, for owner it shows a blank field.

In this picture we have:
Left: Asset owner just on immich home page
Middle: Anonymous guest viewing shared album
Right: Asset owner viewing shared album

image

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.77.0

### Version of Immich Mobile App

v1.77.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    command: ["start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    image: ghcr.io/immich-app/immich-server:release
    command: ["start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
      - typesense
    restart: always


  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    command: [ "python", "src/main.py" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - model-cache:/cache
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    depends_on:
      - database
    restart: always

  immich-web:
    image: ghcr.io/immich-app/immich-web:release
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:release
    ports:
      - 2283:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always
    
  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.0
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data

    logging:
      driver: none
    volumes:
      - tsdata:/data
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=/mnt/hdd/media/Photos
LOG_LEVEL=simple
JWT_SECRET=<redacted>
TYPESENSE_API_KEY=<api-key>
```

### Reproduction steps

```bash
1. Add a description to an image
2. Add that image to an album and create a share link.
3. Access the album via that link anonymously and the image has no description
```

### Additional information

_No response_

### LINKED ISSUE #6244: [BUG] Photo descriptions missing from shared links
### The bug

Much like described in #4073, if I add descriptions to photos, add them to an album, create a shared link, the anonymous viewers can't see the descriptions. This nearly defeats the usefulness of shared links for most purposes. I was waiting for 1.92 to come out to fix the other breakage related to shared links, so I'm not sure if this was working before. Still really hoping to replace my use of google photos with immich, but shared links with photo descriptions is the minimum bar :)

Here's an image as viewed by the album owner:
image

Here's the same one viewed by an anonymous viewer via share link:
image

### The OS that Immich Server is running on

Ubuntu 22.04, via docker

### Version of Immich Server

1.92

### Version of Immich Mobile App

n/a

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /danplanet/Media/Pictures:/mnt/media/pictures:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/Pictures:/mnt/media/pictures:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Set a description on a photo
2. Add to album
3. Share album with link
4. Open a private browser window, go to the link
5. See the description is missing
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sellnat77**
## Description
  - Attempts to use the current `asset`'s exifInfo.description in the bound description (When it exists)
  - This approach will set a default value for the description if we have it and differs from the previous approach of trying to set the value of the text area

Fixes #4073
Fixes #6244

## How Has This Been Tested? 
sorry for the buggy PR @waclaw66 Any other test paths you want me to exercise?

- [x] Upload image -> Add description -> Add to shared album -> Open image as photo owner -> Open shared link as photo owner -> open shared link in incognito tab(anon user) -> Verify photo description is visible across all viewing methods
- [x] Upload image AFTER testing above ^ -> Verify existing descriptions are maintained and web doesnt crash
- [x] Add image without description to shared album -> Verify asset detail is correct
- [x] Modify image description after upload -> Verify description is maintained in standard view + album views 

## Screenshots (if appropriate):
Left: As Photo Middle: As photo owner through shared link Right: As anon user in incognito
banana_test
Tested the photo detail when people are present to exercise the code within the if statement
with_people
After editing description just to make sure the detail is updated properly
post_edit

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation if applicable

### CODE REVIEW

**Comment by jrasm91** [comment]
Did you test navigating to the next/previous assets, opening and closing the asset in each view?

**Comment by sellnat77** [comment]
Ohhhhh nice catch ty! next/prev doesnt show the description, working on it

**Comment by jrasm91** [comment]
Stale, closing. Feel free to re-open if you find a way to make this work correctly.

**Comment by jrasm91** [comment]
Oh you know what, I mis-read that you had actually already fixed my comment. I tested this and it does indeed allow for descriptions in shared links.

**Review by jrasm91 — APPROVED** [review]

**Pull request merged**
