### PR TITLE
Greek translation

### PR DESCRIPTION
**Pull request by MaximosPr**
Worked further in translating to the Greek language. Some assets are still left in English and contain mostly technical language that the average user will no encounter or are of such nature that only the admin can take care of.

### CODE REVIEW

**Comment by MaximosPr** [comment]
Ah sorry, first time I commit anything and just thought I would need to place it in the same spot

**Comment by alextran1502** [comment]
Can you shoot me your email address? I can send you an invitation link

**Comment by VelocityRa** [comment]
Can I have an invite as well?

**Comment by MaximosPr** [comment]
> Can I have an invite as well?

I do it from this place now
https://hosted.weblate.org/projects/immich/immich/el/

**Comment by danieldietzler** [comment]
> > Can I have an invite as well?
> 
> I do it from this place now [hosted.weblate.org/projects/immich/immich/el](https://hosted.weblate.org/projects/immich/immich/el/)

That is only for web translations (for now)

**Comment by danieldietzler** [comment]
@VelocityRa do you want to contribute to mobile translations? If so, in which language?

**Comment by MaximosPr** [comment]
@danieldietzler I want Greek for mobile, working only for web currently.

**Comment by danieldietzler** [comment]
@MaximosPr Greek is already supported, there are just no translations for it. If you throw me your email somehow (discord if you don't want to share it publicly) I can add you so that you can translate into Greek

**Comment by MaximosPr** [comment]
> If you throw me your email somehow (discord if you don't want to share it publicly) I can add you so that you can translate into Greek
Done in discord, thanks

**Comment by VelocityRa** [comment]
Interested in Greek for Android as well, posted about it in `#translations` a couple days back and received no answer - I'll DM you.

**Pull request closed without merging**
