### PR TITLE
feat(ml): support cuda acceleration

### PR DESCRIPTION
**Pull request by martabal**
Based on @simone-viozzi work, this PR adds support for gpu acceleration for machine-learning. 
Requirements : 
- A nvidia gpu 
- `nvidia-container-toolkit` installed on your machine

AIO image already have nvidia support, you can find some results [here](https://github.com/imagegenius/docker-immich/issues/88#issuecomment-1556800036). 

This image supports gpu acceleration for tag objects, encode clip and recognize faces jobs. Non-compressed image size is ~12gB.

It's not optimized for now : When all jobs are triggered, it uses ~4gB of VRAM 😨, and vram is not freed after computation.

To do: official documentation

### CODE REVIEW

**Comment by mertalev** [comment]
This initially didn't use `CUDAExecutionProvider` for me, but after changing the source image to `11.8.0-cudnn8-runtime-ubuntu22.04` and adding the below lines to the Dockerfile it works! It seems `onnxruntime` doesn't have full compatibility with CUDA 12.* yet.
```
RUN rm -rf /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1 /usr/lib/x86_64-linux-gnu/libcuda.so.1
RUN ln -s /usr/local/cuda/lib64/libnvrtc.so.11.8.89 /usr/local/cuda/lib64/libnvrtc.so
```

**Comment by martabal** [comment]
Does face recognition works for you ?

**Comment by mertalev** [comment]
I didn't try doing inference, but it loaded all of the facial recognition models with CUDAExecutionProvider. I made some other changes with ONNX but couldn't get CUDA to work until I got a working version with that Dockerfile. I debugged from there and have a version with all ONNX compiled models in [this](https://github.com/mertalev/immich/tree/ml-accel) branch. I haven't done any serious profiling yet but it seems to do around 20-25 images/s on my 3080 for image classification and CLIP. The image sizes are a little over 3gb for the CPU version and about 8.4gb for the CUDA version.

**Comment by martabal** [comment]
Reduced image size to 8.6gB

**Comment by alextran1502** [comment]
Continuing in #2574

**Pull request closed without merging**
