### PR TITLE
feat(web,server): run jobs for specific assets

### PR DESCRIPTION
**Pull request by jrasm91**
Add overflow menu items to the asset view and multi-select action bar to:
- Refresh metadata
- Refresh thumbnails
- Refresh encoded videos

image

As of now this is only added to the multi-select actions on the main timeline. We can possibly add it to the rest.

TODO:
- [ ] Possibly administration setting to disable this feature for non-admins

### CODE REVIEW

**Comment by martabal** [comment]
Can we limit to admins ?

**Comment by jrasm91** [comment]
Why?

**Comment by martabal** [comment]
I prefer that my users cannot spam these jobs which use a lot of resources (especially transcoding video and generating thumbnail)

**Comment by jrasm91** [comment]
Is it any different than uploading new assets?

**Comment by alextran1502** [comment]
I think @martabal's concern is valid. Should we add a setting in the job page to toggle this feature for users?

**Comment by jrasm91** [comment]
> I think @martabal's concern is valid. Should we add a setting in the job page to toggle this feature for users? 

We can always do that. Imo they can spam resources by reuploading them anyways.

**Comment by alextran1502** [comment]
@martabal I think @jrasm91's point also makes sense. Granted that it can only be run per asset, not in bulk. It shouldn't be an issue

**Comment by jrasm91** [comment]
> For me it's not an issue, just a preference. If my users have issues with their assets, I prefer they contact me instead of spamming the server.

Fair enough. I'm fine with making it configurable.

**Review by alextran1502 — APPROVED** [review]

**Comment by waclaw66** [comment]
Could you please add those menu items to the menu of selected album items?

**Pull request merged**
