### PR TITLE
fix(mobile): Changes in the UI for the image editor pages

### PR DESCRIPTION
**Pull request by Yuvi-raj-P**
This commit brings many changes to the overall layout and user interface of the edit page and the crop page for the Immich mobile app. More Immich colors and better texts! Below are the changes that were made:

**NOTE: This commit required this commit to be merged first to work:**  https://github.com/immich-app/immich/pull/11741

| Before | After |
| ------------- | ------------- |
| <video src="https://github.com/user-attachments/assets/06b5ab0e-0842-4004-a2e1-4540ac702f26">  | <video src="https://github.com/user-attachments/assets/642e721f-f20f-4b6a-bcc9-7d63683f2e60">|

### CODE REVIEW

**Comment by alextran1502** [comment]
Nice work! Thank you

**Comment by Yuvi-raj-P** [comment]
Hey @alextran1502 Do you know why I am getting these tasks failed: `Test / End-to-End Tests (pull_request)`
`Test / Mobile (pull_request)` I dont get any of the errors on when I am testing.

**Comment by alextran1502** [comment]
Here are the errors 

image

**Comment by Yuvi-raj-P** [comment]
Thanks for pointing me to those errors! Its weird how I did not find those on my build.

**Comment by Yuvi-raj-P** [comment]
Hi @alextran1502 , I now get the problem; The issue is that the https://github.com/immich-app/immich/pull/11741 hasn't been merged yet on the actual immich repo therefore all those issues. I can't reproduce these errors on my side which I think is because I already got the past commit changes added to my current repo. So we gotta merge that past commit first and see if the issue still persists.

**Pull request closed without merging**
