### PR TITLE
fix(web): Timeline scrollbar shown over menu

### LINKED ISSUE #3735: [BUG] timeline scrollbar shown over menu
### The bug

album
obrazek
obrazek

face
obrazek
obrazek

### The OS that Immich Server is running on

Fedora 38

### Version of Immich Server

1.73.0

### Version of Immich Mobile App

1.73.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
not relevant
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by danieldietzler**
This PR fixes #3735.

### Before
Screenshot 2023-09-12 at 16 26 08

### After
Mouse on the button
Screenshot 2023-09-12 at 16 27 30

Mose below the button, timeline text not overflowing
Screenshot 2023-09-12 at 16 27 38

### CODE REVIEW

**Comment by alextran1502** [comment]
Hello, can you help showing the screenshots of before/after the changes?

**Comment by danieldietzler** [comment]
> Hello, can you help showing the screenshots of before/after the changes?

Yes sorry, I forgot.

**Review by jrasm91 — APPROVED** [review]
LGTM!

I tested this on the album page (setting new thumbnail), person page (setting new thumbnail), photos page (behind account menu, upload info box), still shows up behind asset viewer and notifications.

**Comment by waclaw66** [comment]
This fix causes that album and face context menu is rendered under dots button...

obrazek
obrazek

**Pull request merged**
