### PR TITLE
chore: remove watcher polling option

### PR DESCRIPTION
**Pull request by etnoy**
Polling for the library watcher only seems to bring problems. If users want to rescan libraries automatically we should probably have them use the cron feature instead.

### CODE REVIEW

**Review by jrasm91 — APPROVED** [review]

**Comment by jrasm91** [comment]
We should maybe include a migration to delete the option from the database

**Comment by etnoy** [comment]
> We should maybe include a migration to delete the option from the database

Totally forgot about that

**Review by danieldietzler — APPROVED** [review]
Nice! Seeing such a diff always makes me happy :)
If most people won't use it anyways I think removing this makes sense.

**Comment by etnoy** [comment]
> We should maybe include a migration to delete the option from the database

Is there an easy way to create a migration for a config change? Typeorm doesn't see any changes

**Comment by alextran1502** [comment]
This is a breaking chance because we removed a feature. There is no breaking changes on database level or deployment method, correct?

**Comment by jrasm91** [comment]
There are no schema changes, you just need to write a migration that will delete the key if it has been set. Take a look at:

`server/src/infra/migrations/1674263302005-RemoveVideoCodecConfigOption.ts`

You can generate an empty migration with `npm run typeorm:migrations:create`

**Comment by figadore** [comment]
Can you link to the issue(s) where these problems were detailed?

**Pull request merged**
