### PR TITLE
chore(server): Update local-reverse-geocoder to 0.15.0

### LINKED ISSUE #1963: [BUG]: Corrupted Reverse Geocoding CSV File
https://github.com/tomayac/local-reverse-geocoder/issues/63

Possible solutions:
- Fix upstream
- Detect the issue, delete the csv file/directory, and try again

### PR DESCRIPTION
**Pull request by bo0tzz**
Fixes #1963

### CODE REVIEW

**Review by jrasm91 — APPROVED** [review]

**Comment by alextran1502** [comment]
The server build is broken with this change, hmm 🤔

**Comment by bo0tzz** [comment]
> Fatal javascript OOM in GC during deserialization

Very strange 🤔 The tests do work, both locally and in CI. Any ideas?

**Comment by alextran1502** [comment]
I think the new version might have something to do with it, can you update to a different version than this one and main and try to push it

**Comment by bo0tzz** [comment]
The amd64 build is working fine, it seems to be the emulated ARM ones that are having problems. I ran it on the demo vm (which is ARM) to check and that was fine.

**Comment by bo0tzz** [comment]
I can't move the geocoder dependency down any versions because the fix we need is only in the latest version. It came with a patch bump of the transient csv-parse dep. I really don't think that's likely to be causing the issue, but I've forced it back down just to experiment. If that doesn't help, I'm not really sure where else to investigate 😕

**Comment by jrasm91** [comment]
Can we disable the post install script?

**Comment by bo0tzz** [comment]
Closing in favour of #2242

**Pull request closed without merging**
