### PR TITLE
docs: update mobile screenshot

### PR DESCRIPTION
**Pull request by aaronjrodrigues**
This is to help make the docs more up to date as under "Login" at https://immich.app/docs/features/mobile-app it still displays the old immich logo. I took a new screenshot with the newer logo. I've attached the logo that I've added.

sign-in-phone

### CODE REVIEW

**Comment by alextran1502** [comment]
Can you help with the Immich color for the screenshot as well? I am seeing you are using a different material color here

**Review by jrasm91 — APPROVED** [review]

**Comment by aaronjrodrigues** [comment]
> Can you help with the Immich color for the screenshot as well? I am seeing you are using a different material color here

Oh my bad I just realized, going to upload the one with the default custom scheme right now.

**Comment by aaronjrodrigues** [comment]
sign-in-phone
@jrasm91 here's the updated version

**Comment by aaronjrodrigues** [comment]
had to reupload because the updated screenshot contained my domain name used for immich.

**Pull request merged**
