### PR TITLE
Feature chinese android app

### PR DESCRIPTION
**Pull request by chen3stones**
add Chinese for Android app, process 90%.

### CODE REVIEW

**Comment by alextran1502** [comment]
Can you send me your email, we have a platform to manage translation

**Comment by chen3stones** [comment]
***@***.***
&nbsp;is my email, thanks

---Original---
From: ***@***.***&gt;
Date: Thu, Dec 15, 2022 23:06 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [immich-app/immich] Feature chinese android app (PR #1108)




 
Can you send me your email, we have a platform to manage translation

**Comment by alextran1502** [comment]
Can you send me your email either through discord or to my email? GitHub doesn't show email addresses here

image

**Comment by alextran1502** [comment]
Merged using localizely

**Pull request closed without merging**
