### PR TITLE
fix(server): wrong video rotation with QSV and RKMPP decoding

### LINKED ISSUE #9252: Video rotation wrong when played back.
### The bug

Videos recorded in portrait mode are played back in landscape mode in  both web and app.
Preview image is the correct rotation.

Downloading the video then playing locally is played back correctly.

### The OS that Immich Server is running on

Armbian

### Version of Immich Server

1.103.1

### Version of Immich Mobile App

1.103.1

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
#   network_mode: "host"
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
      file: hwaccel.transcoding.yml
      service: rkmpp # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
#   network_mode: "host"
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.ml.yml
      service: armnn # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
#   network_mode: "host"
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:afb290a0a0d0b2bd7537b62ebff1eb84d045c757c1c31ca2ca48c79536c0de82
#   network_mode: "host"
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
#   network_mode: "host"
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. record video on phone in portrait mode
2. play back in app or web and its the wrong orientation.
3.
...
```

### Relevant log output

_No response_

### Additional information

_No response_

### LINKED ISSUE #10498: Recoded video - rotation wrong
### The bug

With 1.106.4 if have an issue with the recoded videos being the wrong orientation.
It affects HEVC encoded videos in 1080p or 4k from iPhone 13 and 15.
Videos in portrait orientation are rotated to landscape. Videos in landscape are rotated 180°.
The videos do not just play that way in the browser but also when I download the recoded videos with Chrome to my local disk.

recode config is:

> "ffmpeg": {
>     "crf": 28,
>     "threads": 0,
>     "preset": "medium",
>     "targetVideoCodec": "hevc",
>     "acceptedVideoCodecs": [
>       "hevc"
>     ],
>     "targetAudioCodec": "aac",
>     "acceptedAudioCodecs": [
>       "libopus",
>       "mp3",
>       "aac"
>     ],
>     "targetResolution": "720",
>     "maxBitrate": "2500",
>     "bframes": -1,
>     "refs": 0,
>     "gopSize": 0,
>     "npl": 0,
>     "temporalAQ": false,
>     "cqMode": "auto",
>     "twoPass": true,
>     "preferredHwDevice": "auto",
>     "transcode": "required",
>     "tonemap": "hable",
>     "accel": "qsv",
>     "accelDecode": true

### The OS that Immich Server is running on

Ubunti 24.04

### Version of Immich Server

1.106.4

### Version of Immich Mobile App

v.106

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
default
```

### Your .env content

```Shell
default
```

### Reproduction steps

```bash
see above
```

### Relevant log output

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by apeman76**
This should fix #10634 , #10498 and #9252. Could possibly also fix photos having the same issue if hardware recoding? i.e. #8355
nvenc already had the option, but QSV and RKMPP was missing it
```
Example: Input has a raster size of 1920x1080 with 90° clockwise rotate side data. 
Running ffmpeg -i input.mp4 output.mp4 will result in the video being rotated 90° clockwise according to the rotate side data. 
The output will be 1080x1920 with the rotate side data removed.
```
from https://stackoverflow.com/a/69396105

Fixes #10634
Fixes #10498
Fixes #9252

### CODE REVIEW

**Comment by mertalev** [comment]
Thanks for the PR! You'll want to update the tests as well to include this flag.

**Comment by apeman76** [comment]
> Thanks for the PR! You'll want to update the tests as well to include this flag.

Should be added now, let me know if it's correct :)

**Comment by mertalev** [comment]
Running `npm run format:fix` should take care of that failed check.

**Review by mertalev — APPROVED** [review]
Looks great!

**Comment by alextran1502** [comment]
@apeman76 Can you help fix the test by running `npm run format:fix`? Somehow I cannot push the fix to your branch

**Pull request merged**
