### PR TITLE
fix/(web) Set the alias of zh-CN to zh-Hans

### PR DESCRIPTION
**Pull request by fa1seut0pia**
fix browser does not display local settings Chinese. #13401

### CODE REVIEW

**Review by danieldietzler — COMMENTED** [review]
This PR does not make sense to me. We already distinguish `code` and `weblateCode` in line 317 and 323 of the `constants.ts` file respectively. So clearly, weblate uses `zh_SIMPLIFIED` and not `zh-Hans`, and the browser uses `zh-Hans`, right?

**Comment by fa1seut0pia** [comment]
No，browser uses `zh-CN`

image

**Comment by danieldietzler** [comment]
I meant "browser" as in, the code immich uses in web.

**Comment by danieldietzler** [comment]
Try setting `code: 'zh-CN` in line 323 and undo all your other changes.

**Pull request closed without merging**
