### PR TITLE
Web Photo Editor

### PR DESCRIPTION
**Pull request by dfcowell**
Based on the work started by @faupau03 here: https://github.com/immich-app/immich/pull/3271

The vast majority of the work is theirs, opening a new PR so that I can keep up-to-date with upstream.

There's a bit of work required to get this ready for review. I'm going to focus on some refactoring for maintainability and tests, and finishing off the crop feature before submitting for review.

TODO:

- [ ] Refactor UI components to use reactive Svelte conventions (in progress)
- [ ] Unit tests for editor logic
- [ ] Get crop handles working

Out of scope for this version:

- Auto-adjust/smart filters
- Mobile/touch-compatible UI (targeting desktop use only with a strong preference for mouse input)

### CODE REVIEW

**Comment by bo0tzz** [comment]
Closing as stale/superseded by #10989

**Comment by alextran1502** [comment]
Will reopen when the work restart

**Comment by byjlw** [comment]
how come this got closed?

**Comment by alextran1502** [comment]
@byjlw as stated above, there is an opened pr that address this feature and likely to be merged

**Comment by lex-obrien** [comment]
Good Afternoon!  I know this is an old PR, but I was trying to understand if there is an active plan to add basic edit mode (crop/rotate) to the web version and NOT just the mobile version?  Or is there, and I just missed it?

The referenced PR ( #10989 ) seems to be mobile only.

Thanks!  ~Lex

**Comment by stephen304** [comment]
@lex-obrien If I've been following along correctly, #11074 already added a (hidden for now) web editor, which is waiting for a server side implementation to save edited photos, which is a draft in #11658 so that's where I'm following along.

**Pull request closed without merging**
